### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by linsui** [MetaCubeX/Clash.Meta#101]
请问是否可以在 F-Droid 发布 [ClashMetaForAndroid](https://github.com/MetaCubeX/ClashMetaForAndroid)？

**Comment by MetaCubeX** [comment]
随意

**Comment by linsui** [comment]
谢谢

**Comment by linsui** [comment]
请问我可以在这里添加 Fastlane 格式的应用描述吗？F-Droid 可以从这里抓取。

**Comment by MetaCubeX** [comment]
@linsui pr看看

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11293 MR 已合并，大概一周内会进入存储库。我不懂软件安全，这个mobsf的扫描结果如果感兴趣可以看看。https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11293#note_1021534776 谢谢！
