### ISSUE TITLE
可以考虑支持 HTTP/Socks 根据用户分流吗?

### ISSUE THREAD

**Issue by fcying** [MetaCubeX/Clash.Meta#103]
同端口可以根据连接用户的不同, 分流到不同的地方. 

这功能上游有一个PR, 不过没合入[Dreamacro#1584](https://github.com/Dreamacro/clash/pull/1584)

**Comment by silverzhaojr** [comment]
clash.meta 最近加了个 `listeners`，你可以看下是否是你想要的：https://github.com/MetaCubeX/Clash.Meta/blob/32c53b9584229f8a7b19a6306533758218bbe368/docs/config.yaml#L724

**Comment by fcying** [comment]
> clash.meta 最近加了个 `listeners`，你可以看下是否是你想要的：
> 
> https://github.com/MetaCubeX/Clash.Meta/blob/32c53b9584229f8a7b19a6306533758218bbe368/docs/config.yaml#L724

listeners 就是多监听了几个端口, 然后在这些端口进行分流吗?

这个可以满足需求了
