### ISSUE TITLE
Android 上导入配置出现 proxy 0: key 'up' missing

### ISSUE THREAD

**Issue by sanyuzi** [MetaCubeX/Clash.Meta#105]
在Android上导入hysteria.yml配置时不成功，出现 proxy 0: key 'up' missing 提示

**Comment by sanyuzi** [comment]
proxies:
  - name: "hysteria"
    type: hysteria
    server: hysteria.com
    port: 
    auth_str: 0123456
    #obfs: yourpassword
    alpn: h3
    protocol: wechat-video          #支持udp/wechat-video/faketcp
    up_mbps: 50
    down_mbps: 100
    #sni: server.com
    #skip-cert-verify: false
    #recv_window_conn: 12582912
    #recv_window: 52428800
    #auth: "[BASE64]"
    #auth_str: "yubiyubi"
    #ca: "./my.ca"
    #ca_str: "xyz"
    #disable_mtu_discovery: true

**Comment by sanyuzi** [comment]
填了大佬，写的有什么不对吗？

**Comment by Skyxim** [comment]
@sanyuzi up_mbps: 50 
    down_mbps: 100  写成up/down

**Comment by sanyuzi** [comment]
好的，非常感谢！
