### ISSUE TITLE
vmess节点使用V2RayN连接正常，clash meta连不上

### ISSUE THREAD

**Issue by msbtx** [MetaCubeX/Clash.Meta#107]
clash meta使用最新的alpha版本也不行，打开debug级别打印访问google如下：
![QQ截图20220701213656](https://user-images.githubusercontent.com/6949433/176905493-28ee8c48-de54-45e1-a57e-68a052917a33.png)

`

**Comment by Skyxim** [comment]
@msbtx dns部分配置发下

**Comment by msbtx** [comment]
> @msbtx dns部分配置发下
![QQ截图20220701213939](https://user-images.githubusercontent.com/6949433/176906016-8a801819-645f-4c8f-952e-204daea26036.png)
用的是梅林的clash插件一键订阅的V2rayN的分享URL

**Comment by msbtx** [comment]
![1](https://user-images.githubusercontent.com/6949433/176906932-c2bba40f-9757-4fcd-9866-2fce1a20f0d4.png)

不好意思，刚图没发全

**Comment by Skyxim** [comment]
@msbtx 尝试删除fallback dns是否能够正常使用

**Comment by Skyxim** [comment]
@msbtx fallback不要放入完全不能使用的dns 如果触发fallback，且fallback无法查询则无法获取IP；从而你无法直连

**Comment by msbtx** [comment]
@Skyxim 谢谢，大概知道了，这应该是那个插件的订阅插件自动加的配置

**Comment by msbtx** [comment]
@vj23456 看起来是的，如果我设置redir-host模式，只有一个节点，不设置fallback应该也没关系吧？
