### ISSUE TITLE
问下，clash 内核的 "Script Shortcut"  Meta 现在支持吗？

### ISSUE THREAD

**Issue by Se7enMuting** [MetaCubeX/Clash.Meta#109]
这个东东：
https://lancellc.gitbook.io/clash/clash-config-file/script/script-shortcut
有支持吗现在？
我用 openclash，里面如果加了 Script Shortcut 字段就无法启动Meta内核，想先来问问 Meta 有支持吗？如果支持的话，我就去问问 openclash 那边

**Comment by angelknight007** [comment]
我记得不支持，meta用规则把很多script 的功能实现了

**Comment by Se7enMuting** [comment]
好像确实不支持，结案

**Comment by fxchby** [comment]
不支持，希望后续版本可以加入
