### ISSUE TITLE
和Clash的订阅不通用

### ISSUE THREAD

**Issue by gbaoye** [MetaCubeX/Clash.Meta#111]
无论是电脑还是路由器，都出现了问题

**Comment by MetaCubeX** [comment]
?

**Comment by aoligei-max** [comment]
?

**Comment by xishang0128** [comment]
?

**Comment by aoligei-max** [comment]
![image](https://user-images.githubusercontent.com/62712238/177672352-ea87479c-d9d6-4f32-8ba3-942336343c6f.png)
