### ISSUE TITLE
clashx.meta可以添加对tun的支持吗？

### ISSUE THREAD

**Issue by skill7899** [MetaCubeX/Clash.Meta#114]
目前MAC端的，没有一个可以开启tun功能。。ORZ

**Comment by Skyxim** [comment]
@skill7899 cfw被吃了？

**Comment by skill7899** [comment]
@Skyxim 支持meta了？

**Comment by Skyxim** [comment]
@skill7899 cfw没支持，但是能换核

**Comment by skill7899** [comment]
@Skyxim 有换核的教程吗？我没有找到入口

**Comment by xishang0128** [comment]
@skill7899 在安装目录的 resources/static/files/win/x64  有一个 clash-x64.exe的文件(大概叫这个),把meta核改成同名,替换进去,即可

**Comment by xishang0128** [comment]
@xishang0128 mac的话,大概是/mac/x64啥的,内核文件应该是叫 darwin 啥的

**Comment by skill7899** [comment]
> @xishang0128 mac的话,大概是/mac/x64啥的,内核文件应该是叫 darwin 啥的

@xishang0128 换了，一样开不成功~~~那个manager也安装了。

**Comment by EkkoG** [comment]
> > @xishang0128 mac 的话，大概是 /mac/x64 啥的，内核文件应该是叫 darwin 啥的
> 
> @xishang0128 换了，一样开不成功～～～那个 manager 也安装了。

不成功的表现是什么呢

写了个替换 CFW 内核的脚本，可以试试 https://gist.github.com/EkkoG/c2bb61656f6beec090bbcdc937585e67

**Comment by skill7899** [comment]
> > > @xishang0128 mac 的话，大概是 /mac/x64 啥的，内核文件应该是叫 darwin 啥的
> > 
> > 
> > @xishang0128 换了，一样开不成功～～～那个 manager 也安装了。
> 
> 不成功的表现是什么呢
> 
> 写了个替换 CFW 内核的脚本，可以试试 https://gist.github.com/EkkoG/c2bb61656f6beec090bbcdc937585e67

@EkkoG 有可能是M1版本有BUG，我没有替换的版本一样是不可以开启tun。已经提了BUG单

**Comment by skill7899** [comment]
最新版本已经实现，并已经良好运行
