### ISSUE TITLE
如何能够获取到上一个版本的alpha核心

### ISSUE THREAD

**Issue by eightsheep67** [MetaCubeX/Clash.Meta#119]
今天更新的这个版本我替换openclash后有问题，无法科学，hysteria也无法测速。

**Comment by Skyxim** [comment]
@eightsheep67 是否使用了skip-cert-verify?如果是已经修复了 等编译完了更新下

**Comment by eightsheep67** [comment]
> @eightsheep67 是否使用了skip-cert-verify?如果是已经修复了 等编译完了更新下

是，那我先替换release核心过度一下

**Comment by eightsheep67** [comment]
顺便问下，compatible核心有什么区别，会因为兼容性牺牲其他功能吗？

**Comment by Skyxim** [comment]
@eightsheep67 没有区别，只是针对老的CPU的指令集进行编译的

**Comment by eightsheep67** [comment]
谢谢大佬解惑！！
