### ISSUE TITLE
希望增加 wireguard 协议的支持

### ISSUE THREAD

**Issue by fscarmen** [MetaCubeX/Clash.Meta#122]
十分感谢 meta 内核的作者们，支持了 hysteria 和 XTLS。如果再支持一下 wireguard，就更 perfect 了。

**Comment by cheng1nuo** [comment]
@fscarmen 还有naiveproxy

**Comment by chenxijun** [comment]
支持

**Comment by wwqgtxx** [comment]
@chenxijun alpha版本早已支持

**Comment by fscarmen** [comment]
有 yaml 文件的模板吗？更新了不会设置。

**Comment by kunish** [comment]
文档可以在alpha分支的[示例文件](https://github.com/MetaCubeX/Clash.Meta/blob/Alpha/docs/config.yaml#L536)找到

**Comment by fscarmen** [comment]
谢谢，可以了。
