### ISSUE TITLE
Can't use nextdns dot/tls dns

### ISSUE THREAD

**Issue by samlux04** [MetaCubeX/Clash.Meta#128]
For some reason nextdns dot won't work
`- tls://clash--meta-fd44f5.dns.nextdns.io`

It says
`[ debug ][DNS Server] Exchange ;user.mngusr.com. IN A failed: all DNS requests failed, first error: remote error: tls: no application protocol`

while DOQ is working fine
`- quic://clash--meta-fd44f5.dns.nextdns.io`

Other DOT seems to work fine
```yaml
- tls://dns.adguard.com
- tls://1.1.1.1
- tls://doh.tiar.app
-```

Tried android system private DNS and sagernet working fine.

**Comment by samlux04** [comment]
> @samlux04 This will be fixed in the next Alpha

Thank you

**Comment by Skyxim** [comment]
It has been fixed. You can try the latest Alpha.

**Comment by samlux04** [comment]
> It has been fixed. You can try the latest Alpha.

Thank you, it's working now.
