### ISSUE TITLE
逻辑判断规则的域名解析顺序

### ISSUE THREAD

**Issue by yaohappiness** [MetaCubeX/Clash.Meta#131]
解析的顺序不应该在规则判断前。对于下面的规则，非 22 端口的流量也会解析域名。

    - AND,((DST-PORT,22),(GEOIP,CN)),DIRECT

我觉得更合理的做法应该是，在不满足第一条规则的情况下再解析域名，判断第二条规则。

（虽然可以加上 no-resolve 不解析，但问题是解析的顺序。）

**Comment by yaohappiness** [comment]
感谢回复。

这会造成判断规则里，只要出现 IP 就解析。

有没有办法在满足前面规则的情况下，才解析？在不满足前面规则的时候，不会多出一条 DNS 查询。

**Comment by sjtuross** [comment]
请问逻辑规则上是否真的可以加no-resolve？我这边加了之后OpenClash提示内核报错

`Parse config error: rules[39] [NOT,((GEOIP,CN)),PROXY,no-resolve] error: proxy [no-resolve] not found`

**Comment by kunish** [comment]
> 请问逻辑规则上是否真的可以加no-resolve？我这边加了之后OpenClash提示内核报错
> 
> `Parse config error: rules[39] [NOT,((GEOIP,CN)),PROXY,no-resolve] error: proxy [no-resolve] not found`

试一下就知道了，如果确定写法没问题，报错就是不支持
