### ISSUE TITLE
在openclash中开启Meta后，在使用加速器的情况下发现多个问题

### ISSUE THREAD

**Issue by LuziJay** [MetaCubeX/Clash.Meta#132]
在路由器固件openclash中使用meta发现以下问题：

问题1.开启openclash redir-host兼容模式（不代理UDP）的同时开启雷神加速器，雷神加速器会频繁报告本地网络异常
问题2.开启openclash redir-host兼容模式（代理UDP）/redir-host混合模式的同时开启UU加速器，UU加速器的测速节点基本无法链接，关掉openclash，或者开启绕过大陆ip后正常。

链接如下：
https://github.com/vernesong/OpenClash/issues/2562
现已确认是开启meta导致出现的问题
在openclash中，仅开启了：使用Meta内核

版本为：alpha-g503b1ef

**Comment by eightsheep67** [comment]
手动换最新的alpha内核试一下吧？

**Comment by LuziJay** [comment]
> 手动换最新的alpha内核试一下吧？

已更换，问题仍然出现
最简单的复现方法：仅启动Meta，打开PC端的UU加速器，英雄联盟-国服-区服/节点选择-可以发现全部超时
![image](https://user-images.githubusercontent.com/91416749/180591014-b64c4a0f-03a3-4584-bb31-6d1e2f4e4f95.png)

**Comment by colufoo** [comment]
> 

我试了一下 问题无法复现，你是不是openwrt安装了docker导致openclash 兼容模式无法正常转发UDP

**Comment by LuziJay** [comment]
> 我试了一下 问题无法复现，你是不是openwrt安装了docker导致openclash 兼容模式无法正常转发UDP？
> 
> > > 手动换最新的alpha内核试一下吧？
> > 
> > 
> > 已更换，问题仍然出现 最简单的复现方法：仅启动Meta，打开PC端的UU加速器，英雄联盟-国服-区服/节点选择-可以发现全部超时 ![image](https://user-images.githubusercontent.com/91416749/180591014-b64c4a0f-03a3-4584-bb31-6d1e2f4e4f95.png)

绝了，还真是docker的问题，把docker卸载即可解决，不过让我感到疑惑的是，tun混合模式+meta也无法正常转发UDP，这就让我感到奇怪。

**Comment by colufoo** [comment]
> > 我试了一下 问题无法复现，你是不是openwrt安装了docker导致openclash 兼容模式无法正常转发UDP？
> > > > 手动换最新的alpha内核试一下吧？
> > > 
> > > 
> > > 已更换，问题仍然出现 最简单的复现方法：仅启动Meta，打开PC端的UU加速器，英雄联盟-国服-区服/节点选择-可以发现全部超时 ![image](https://user-images.githubusercontent.com/91416749/180591014-b64c4a0f-03a3-4584-bb31-6d1e2f4e4f95.png)
> 
> 绝了，还真是docker的问题，把docker卸载即可解决，不过让我感到疑惑的是，tun混合模式+meta也无法正常转发UDP，这就让我感到奇怪。

这应该是某种bug，所以我一般用宽容模式

**Comment by colufoo** [comment]
meta内核的tun模式应该需要用配置文件手动配置，openclash本体的web界面配置好后，修改的配置文件是没有tun:true这行的，应该是两边的开发者某些地方没有沟通好。

**Comment by abigchopstick** [comment]
我把docker也删了试下，谢谢楼上的提示

**Comment by colufoo** [comment]
> 我把docker也删了试下，谢谢楼上的提示

想起来了 meta官方文档显示不支持premium内核某些功能，大概说的就是tun。

**Comment by MetaCubeX** [comment]
@colufoo ？meta有wiki怎么不看看呢

**Comment by abigchopstick** [comment]
docker删了没用，然后TUN可以用的，只是工作不了多久会不正常。

**Comment by coch1** [comment]
> > 我试一下问题无法复现，是不是安装了dockeropenwrt UDP 导致的成功启动模式？
> > > > 手动换最新的alpha内核试一下吧？
> > > 
> > > 
> > > 更换已经，出现最简单的现成方法：只需启动元，打开PC端的UU加速器，英雄联盟-国服-区域服/节点选择-可以发现所有问题![图片](https://user-images.githubusercontent.com/91416749/180591014-b64c4a0f-03a3-4584-bb31-6d1e2f4e4f95.png)
> 
> 绝了，还让docker的问题，把docker真的能轻松解决，不过让我疑惑，tun混合模式+meta也无法正常转向UDP，这让我算了。

需要用docker怎么办

**Comment by TucoBruto** [comment]
> > > 我试一下问题无法复现，是不是安装了dockeropenwrt UDP 导致的成功启动模式？
> > > > > 手动换最新的alpha内核试一下吧？
> > > > 
> > > > 
> > > > 更换已经，出现最简单的现成方法：只需启动元，打开PC端的UU加速器，英雄联盟-国服-区域服/节点选择-可以发现所有问题![图片](https://user-images.githubusercontent.com/91416749/180591014-b64c4a0f-03a3-4584-bb31-6d1e2f4e4f95.png)
> > 
> > 
> > 绝了，还让docker的问题，把docker真的能轻松解决，不过让我疑惑，tun混合模式+meta也无法正常转向UDP，这让我算了。
> 
> 需要用docker怎么办

使用Tun模式
