### ISSUE TITLE
[Feature request]关于支持TUIC

### ISSUE THREAD

**Issue by moranno** [MetaCubeX/Clash.Meta#133]
用了几天的[tuic](https://github.com/EAimTY/tuic)，用下来是一个比[hysteria](https://github.com/HyNetwork/hysteria)更具有普适性的方案。

对比[tuic](https://github.com/EAimTY/tuic)和[hysteria](https://github.com/HyNetwork/hysteria)，
hy使用自己的拥塞控制(?)可以手动设置带宽上限来暴力发包，速度更快，但对VPS不太友好，CPU跑满，IDC可能认为你ddos。
tuic使用BBR等拥塞控制，更克制，更友好，测试下来也有5-10倍的单线程提升（多线程50倍）。

希望Clash meta能增加其支持。

**Comment by Skyxim** [comment]
@moranno 看过tuic没看到他有实现一个bbr的congestion 可能是rust的quic库已经实现了bbr，但是quic-go至今未对bbr进行实现(已经计划了5-6年了)

**Comment by ShoukakuChuuCC** [comment]
+1

**Comment by moranno** [comment]
我可以提供200u资金支持以实现支持tuic。作者或有能力的开发者可以联系我。tg：@missmoranno

**Comment by Skyxim** [comment]
@moranno quic-go 不支持 BBR 流控 TUIC 基于 quinn 自带的实现的几种流控，go这里都没有

**Comment by moranno** [comment]
> @moranno quic-go 不支持 BBR 流控 TUIC 基于 quinn 自带的实现的几种流控，go这里都没有

似乎这并不是太大的问题，作为客户端就算没有用塞控制似乎也可以，因为客户端发包只涉及少量的请求，而服务端发包才是速度的关键。（只是我个人浅薄的理解）

https://github.com/EAimTY/tuic/issues/62#issuecomment-1196877635

> 不同的拥塞控制算法使用不同的方式计算并控制每次发送数据包的大小，具体见 [TCP congestion control](https://en.wikipedia.org/wiki/TCP_congestion_control)
> 
> server 与 client 端都存在这个选项是因为两侧都需要选择算法控制各自发送数据包的大小。通常在“测速”时只会关注 server -> client 的速度，而 client 端设置的拥塞控制算法时用在 client -> server 传输数据的场景，也就是所谓的上行流量，因此对“测速”的影响不大

**Comment by moranno** [comment]
@Skyxim 能否加下我tg：@missmoranno ，我把tuic的作者和meta这边的作者拉个群，希望能对2边都做一些支持。

**Comment by Moexin** [comment]
+1

**Comment by nauxliu** [comment]
Surge 最新的 Beta 版本已经支持 TUIC 了

**Comment by moranno** [comment]
> Surge 最新的 Beta 版本已经支持 TUIC 了

surge支持hy不？

**Comment by wwqgtxx** [comment]
done

**Comment by wwqgtxx** [comment]
修了一天的bug应该可以正常食用了

**Comment by cubemaze** [comment]
@yoohooyoo 已经支持了

**Comment by wwqgtxx** [comment]
> +1 求支持tuic

都写完了，你+1个啥呀

**Comment by Karmylr** [comment]
。。。。

**Comment by yoohooyoo** [comment]
> @yoohooyoo 已经支持了

我测试提示不行呀。
版本 1.13.2。

**Comment by wwqgtxx** [comment]
> > @yoohooyoo 已经支持了
> 
> 我测试提示不行呀。 版本 1.13.2。

用最新alpha版

**Comment by yoohooyoo** [comment]
> 

奥 好的我这就去试试。

**Comment by yoohooyoo** [comment]
确实可以了，感谢感谢。

**Comment by houpi** [comment]
> 

请问怎么写客户端配置？

**Comment by wwqgtxx** [comment]
> 请问怎么写客户端配置？

https://github.com/MetaCubeX/Clash.Meta/blob/1d9e320087b82879d65185bf0458b0e55efd4279/docs/config.yaml#L489-L504

**Comment by houpi** [comment]
> 
    - { name: tuic, type: tuic, server: www.example.com, port: 4340, token: password, udp-relay-mode: quic, alpn: [h3], reduce-rtt: true }
    
我这不可以，用的也是最新版本

![Screenshot_2022-11-30-12-23-11-638_com github metacubex clash meta](https://user-images.githubusercontent.com/42278085/204707279-0c853223-1fb9-4ed0-8439-c2fb4a4f1e2c.jpg)

**Comment by wwqgtxx** [comment]
> ```
> - { name: tuic, type: tuic, server: www.example.com, port: 4340, token: password, udp-relay-mode: quic, alpn: [h3], reduce-rtt: true }
> ```
> 
> 
>      
>   
> 
> 我这不可以，用的也是最新版本
> 
> 
> ![Screenshot_2022-11-30-12-23-11-638_com github metacubex clash meta](https://user-images.githubusercontent.com/42278085/204707279-0c853223-1fb9-4ed0-8439-c2fb4a4f1e2c.jpg)

这里只讨论核心，不考虑cfa之类的客户端
