### ISSUE TITLE
[ Feature Request ] WSS a.k.a WebSocket Secure

### ISSUE THREAD

**Issue by helmiau** [MetaCubeX/Clash.Meta#152]
Please add more websocket secure feature from this commit https://github.com/djoeni/Clash.Meta/commit/9cd0ff7180090a56195487e04ad98158f33fba7e

this commit will allow wss://web.com/ 

thank you

**Comment by Skyxim** [comment]
@helmiau I haven't seen any changes. Now vmess can also use ws+tls, that is, wss.

**Comment by Skyxim** [comment]
Vmess configuration uses tls: true to use wss, now

**Comment by Skyxim** [comment]
@helmiau The trojan transport only support tcp or grpc, in clash

**Comment by Skyxim** [comment]
@helmiau Sorry, I remember the wrong one. Trojan also has ws.

**Comment by lux5am** [comment]
Looking at the patch. It require to patch `gorilla/websocket` to allow a ws/wss scheme in path.

Currently meta will send a request like this
```
GET /ws://some.mask.host/websocket HTTP/1.1
```
With the patch:
```
GET ws://some.mask.host/websocket HTTP/1.1
```

**Comment by Skyxim** [comment]
> Looking at the patch. It require to patch `gorilla/websocket` to allow a ws/wss scheme in path.
> 
> Currently meta will send a request like this
> 
> ```
> GET /ws://some.mask.host/websocket HTTP/1.1
> ```
> 
> With the patch:
> 
> ```
> GET ws://some.mask.host/websocket HTTP/1.1
> ```

No, Websocket is never show the path with prefix  wss/ws,  wss/ws is equivalent to https/http, which is just a user description and used by a parser. When using only Websocket, it is ws.
<img width="477" alt="image" src="https://user-images.githubusercontent.com/70276018/186097942-4d537458-a8f4-4a4d-828a-aa4b08ac51c7.png">
This path is filled in by the user, in the configuration file.
Someone may write `http://xxxx` in the path of HTTP?

**Comment by lux5am** [comment]
> > Looking at the patch. It require to patch `gorilla/websocket` to allow a ws/wss scheme in path.
> > Currently meta will send a request like this
> > ```
> > GET /ws://some.mask.host/websocket HTTP/1.1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > With the patch:
> > ```
> > GET ws://some.mask.host/websocket HTTP/1.1
> > ```
> 
> No, Websocket is never show the path with prefix wss/ws, wss/ws is equivalent to https/http, which is just a user description and used by a parser. As long as you use Websocket, that's ws.. ![image](https://user-images.githubusercontent.com/70276018/186099193-fc1a705b-3c30-4688-b4c5-021e4a9aad0b.png) This path is filled in by the user, in the configuration file. Someone may write `http://xxxx` in the path of HTTP?

Yes, the standard ws protocol will use ws-host and ws-path correctly as above.
But the one proposed by this issue was to trick the isp to reconnect to another node.
Usually they will use tiktok or whatsapp server as a node.
```yaml
  server: v.whatsapp.net
  sni: v.whatsapp.net
  ws-opts:
    path: ws://the.actual.server/ws
```
Yes, this is very special case and can only be used to certain isp with strict rules, sniffing around the sni and to censor or redirect the content.
https://github.com/taamarin/Clash.Meta
