### ISSUE TITLE
想要一个能上天的功能

### ISSUE THREAD

**Issue by justdoiting** [MetaCubeX/Clash.Meta#154]
增加一个自动下载测速

逻辑是用url-test测出延迟，然后取延迟最低的5个节点，5个节点分别下载一个10Mb的测速文件，最后，这5个节点根据延迟和下载速度这两个数据的值进行单位处理并排序（延迟占30%，下载速度占70%），选择最优的那个

自动下载测速的时间和测延迟的时间一致，先测延迟---取延迟最低的5个---5个做下载测速---延迟与下载速度单位处理---选择最优

**Comment by Skyxim** [comment]
@justdoiting 不具有实际价值，切不考虑移动环境的手机卡流量消耗
这里认为MB
5x10x86400/600=7200 
大约7g每天 ，这还是没有考虑主动健康测试。
而且你在哪保证一个拥有全球节点公平的文件提供下载测试

**Comment by justdoiting** [comment]
我再想想其他的方案让这个上天功能有合理性

**Comment by oluceps** [comment]
有合理性也没用，不具备可实践性
