### ISSUE TITLE
[Feature Request]新增关于对ECC圆锥曲线证书的verify支持

### ISSUE THREAD

**Issue by LittleJake** [MetaCubeX/Clash.Meta#156]
服务器采用ZeroSSL签发的ECC-384证书，使用时开启证书验证时会无法连接。

![image](https://user-images.githubusercontent.com/13583702/184175769-93a20268-f752-429d-9899-db4d9e1edf4b.png)

**Comment by Skyxim** [comment]
@LittleJake go 默认 支持ecc384 确保服务器配置正确 或者是 授信证书

**Comment by LittleJake** [comment]
@Skyxim 感谢回答，想先确认一下Clash的Trojan协议能使用 `skip-cert-verify: false` 配置吗，设置为 `false` 的话测试过安卓和linux下都无法连接。
（ps: 已经确认SNI与证书对应。）

**Comment by Skyxim** [comment]
@LittleJake 可以，false将验证证书，还有你可以尝试使用https://github.com/MetaCubeX/Clash.Meta/blob/4ca2d4146bd9b49180b42e542e08d255aebaa9d5/docs/config.yaml#L310 这个配置，说明参考https://github.com/MetaCubeX/Clash.Meta/blob/4ca2d4146bd9b49180b42e542e08d255aebaa9d5/docs/config.yaml#L32，这是为自签证书准备的

**Comment by LittleJake** [comment]
@Skyxim 刚刚开了debug打出来的日志是这个
```
[TCP] dial - (match DomainKeyword/github) to avatars.githubusercontent.com:443 error: - connect error: x509: certificate signed by unknown authority
```

> @LittleJake 可以，false将验证证书，还有你可以尝试使用
> 
> https://github.com/MetaCubeX/Clash.Meta/blob/4ca2d4146bd9b49180b42e542e08d255aebaa9d5/docs/config.yaml#L310
> 
> 这个配置，说明参考
> https://github.com/MetaCubeX/Clash.Meta/blob/4ca2d4146bd9b49180b42e542e08d255aebaa9d5/docs/config.yaml#L32
> 
> 
> 这是为自签证书准备的，不太清楚你的证书为什么过不了验证

证书是acme签发的，如果用 `fingerprints` 的话估计得经常换。

**Comment by Skyxim** [comment]
@LittleJake 你设备没有zerossl的权威证书？

**Comment by Skyxim** [comment]
@LittleJake 你可以试试全链证书

**Comment by LittleJake** [comment]
@Skyxim 应该是证书问题了，zerossl出来比较晚估计老点的设备根证书没被信任，得试试全链证书或者切去别的CA。

**Comment by LittleJake** [comment]
@Skyxim 使用全链证书测试没有问题了，可以之后在wiki提一句建议使用全链证书。

感谢
