### ISSUE TITLE
windows7下无法使用hysteria协议

### ISSUE THREAD

**Issue by TwooSix** [MetaCubeX/Clash.Meta#164]
日志报错 setting DF failed for both IPv4 and IPv6
查阅hysteria原仓库的[issue](https://github.com/HyNetwork/hysteria/issues/327)发现是hysteria早期版本的BUG，不知道meta是否使用了相关的错误代码？

**Comment by Mazeorz** [comment]
请用alpha分支

**Comment by TwooSix** [comment]
> hy仓库的代码修复是27.1版本，这边最新同步的是28.1版本，有问题请用alpha分支再次核实。

alpha分支版本没有任何问题
