### ISSUE TITLE
CI编译的二进制在linux上跑不起来

### ISSUE THREAD

**Issue by zhfish** [MetaCubeX/Clash.Meta#165]
<img width="922" alt="image" src="https://user-images.githubusercontent.com/287033/185087329-420cb31d-3405-40a4-98a0-9319faba6439.png">
位于intel J4125,kvm虚拟机

**Comment by Skyxim** [comment]
@zhfish j4210?

**Comment by zhfish** [comment]
> @zhfish j4210?

记错，已改，intel J4125

**Comment by Skyxim** [comment]
@zhfish J4125 是可以用compatible，不过需要CPU虚化选择host

**Comment by Skyxim** [comment]
@Skyxim 或者穿透avx2指令集

**Comment by zhfish** [comment]
J4125好像没有avx2...难道悲剧了？

**Comment by Skyxim** [comment]
@zhfish 有 你直接修改cpu 虚化类型从kvm改成host吧

**Comment by zhfish** [comment]
谢谢，我试试

**Comment by zhfish** [comment]
@Skyxim 测试J4125没问题了

现在又遇到一个j1900
应该是没有avx2
并且装的爱快，在爱快里跑的kvm，也没法自己设置cpu虚拟化类型

咱有降级方案么？

**Comment by xkcore123** [comment]
> @Skyxim 测试J4125没问题了
> 
> 现在又遇到一个j1900 应该是没有avx2 并且装的爱快，在爱快里跑的kvm，也没法自己设置cpu虚拟化类型
> 
> 咱有降级方案么？

我10500也运行不起来，请问你是咋解决的？

**Comment by wwqgtxx** [comment]
fix at https://github.com/MetaCubeX/Clash.Meta/commit/6a89cc15c37dd6fef94efabdbfd23708beefc64e
