### ISSUE TITLE
openclash meta核心 nginx分流到x-ui内建立的vless+ws+tls 节点套用cdn无法连通的问题

### ISSUE THREAD

**Issue by zhourui89421** [MetaCubeX/Clash.Meta#169]
自建x-ui面板
nignx监听80和443
建了一个vless*ws＊tls节点监听的 127.0.0.1
用v2rayN在win10上正常连接
然后在v2rayN给这个节点设置好伪装地址，套上了cloudflare的cdn.也能正常使用用链接。
然后用v2rayN的分享功能将这个节点的套cdn和没套cdn的链接放入v2rayes.com网站里转换成了clashmeta的文件，导入到我openwrt的启用meta内核的openclash里。没套cdn的可以连通，套了cdn怎么也连通不了。还在Win10上用cIashN测试了。套了cdn怎么都联通不了。v2rayN里没问题，一切正常。请问哪里出了问题呢？。是openclash meta不支持节点套cdn么？
需要测试连接，请联系admin@thomaswade.eu.org
您也可以自建节点尝试，问题可复现

**Comment by zhourui89421** [comment]
问题已经解决。

**Comment by lslz627** [comment]
> 问题已经解决。

@zhourui89421 您好、想问一下、是如何解决的
