### ISSUE TITLE
ssr无法使用，测速失败

### ISSUE THREAD

**Issue by zvzl** [MetaCubeX/Clash.Meta#170]
使用proxy provider导入ssr节点，节点解析没有报错，节点名字解析正确，但是没有网络，测速没有结果。不知道是不是解析节点信息时出了问题。同样的节点clash正常。
这是ssr节点的一些信息
`cipher: aes-256-cfb, password: *****, protocol: auth_aes128_sha1, obfs: http_simple, protocol-param: ****, obfs-param: ****, udp: true`

**Comment by zvzl** [comment]
![image](https://user-images.githubusercontent.com/84430227/187069445-e71abaa4-e1d8-4edb-8659-e3520e64bdb6.png)
没有报错日志，但是没网。

**Comment by Skyxim** [comment]
provider 是以 clash 的 yaml 格式导入，还是 base64。如果是 base64，确认下参数是否解析正常

**Comment by zvzl** [comment]
![image](https://user-images.githubusercontent.com/84430227/187069904-fed019dd-43e3-4bde-9e91-fe058f7f339a.png)
链接的内容是base64，链接内容如果是clash的yaml格式，还会报错，是不兼容clash的provider格式吗？
我不知道如何看解析后的参数，好像看不到，api只能得到节点名字

**Comment by zvzl** [comment]
把节点信息直接写在配置文件中，正常连接。应该是解析的问题
