### ISSUE TITLE
控制面板的 Config 中的 Sniffer 选项未遵从配置且不可交互

### ISSUE THREAD

**Issue by aenerv7** [MetaCubeX/Clash.Meta#181]
按说这应该是 yacd-meta 这个项目的 issue，但 yacd-meta 的库没开 issue，只好发到这里来了。

如果在配置中关闭 sniffer，也就是将 sniffer 以如下方式配置：
```
sniffer:  
    enable: false
```

在 Clash.Mini 控制面板的 Config 中 Sniffer 设置依旧显示被打开且无法交互（关闭）
![image](https://user-images.githubusercontent.com/4949197/189571456-9cb297ac-d60f-4d34-8267-52ae1faac9be.png)

**Comment by aico267** [comment]
一切以配置为准😁

**Comment by kunish** [comment]
yacd-meta 最新的版本正常，更新以后再试
