### ISSUE TITLE
[Feature] 支持反向代理（隧道）功能

### ISSUE THREAD

**Issue by nick008a** [MetaCubeX/Clash.Meta#190]
### Description

Reverse Proxy (portal+bridge in v2ray) is a particularly useful for working from home. 

### Possible Solution

https://www.v2fly.org/config/reverse.html

**Comment by wwqgtxx** [comment]
显然这里说的tunnels和你理解的不是一个意思，而且上游的2440的PR还是我发的

**Comment by wwqgtxx** [comment]
@nick008a 反向代理建议使用frp

**Comment by wwqgtxx** [comment]
@nick008a 你说的反向代理必须要服务端额外支持的，所以就算clash支持也要配合frps之类的服务端程序，顶多就是在clash内部给你集成一个frpc，反正我觉得没啥意义
