### ISSUE TITLE
dns中的fallback引起所有节点超时的问题

### ISSUE THREAD

**Issue by DeasonHu** [MetaCubeX/Clash.Meta#192]
当配置文件这样写时
`dns:
  enable: true
...
  fallback:
    - https://dns.google/dns-query#PROXY
    - https://cloudflare-dns.com/dns-query#PROXY`
ClashMeta 在连接 `"server":"域名"` 的节点时，会把这个节点的域名送到 PROXY 里的节点来解析。但此时这个节点的域名正因为没有被解析而无法使用。

这个问题 2020 年就有人在 cfw 下面问了，好像提了好多个 issue，但是就是没有人在 ClashMeta 下面问
比如这个
https://github.com/Fndroid/clash_for_windows_pkg/issues/441

**Comment by Skyxim** [comment]
@DeasonHu 如果节点域名返回的 IP 是非 CN，将使用 fallback 的值，但是 fallback 需要节点，导致死循环，可以使用 https://github.com/MetaCubeX/Clash.Meta/blob/5987f8e3b5d489c577328c4cbc147432cb45a498/docs/config.yaml#L126
这样域名的解析将完全走这里的 DNS，从而破除死循环

**Comment by DeasonHu** [comment]
@Skyxim 谢谢谢谢，应该是我瞎了看 wiki 没看到这部分
