### ISSUE TITLE
更新alpha-1684756 无法启动openclash

### ISSUE THREAD

**Issue by eightsheep67** [MetaCubeX/Clash.Meta#193]
2022-09-25 13:20:09 第六步：删除 OpenClash 残留文件...
2022-09-25 13:20:09 第五步: 重启 Dnsmasq 程序...
2022-09-25 13:20:09 第四步: 关闭 Clash 主程序...
2022-09-25 13:20:09 第三步: 关闭 OpenClash 守护程序...
2022-09-25 13:20:08 第二步: 删除 OpenClash 防火墙规则...
2022-09-25 13:20:08 第一步: 备份当前策略组状态...
2022-09-25 13:20:08 OpenClash 开始关闭...
2022-09-25 13:20:05 错误: 无法获取 General 部分的转发端口设置, OpenClash 使用原始配置文件启动失败
2022-09-25 13:20:03 错误: 无法获取 DNS 部分的运行模式设置, OpenClash 使用原始配置文件启动失败
2022-09-25 13:20:01 错误: 无法获取 DNS 部分的监听端口设置, OpenClash 使用原始配置文件启动失败
2022-09-25 13:20:01 错误: OpenClash 启动失败，尝试使用原始配置文件启动...
2022-09-25 13:19:55 提示: 检测到配置了 Meta 内核专属功能，调用 Meta 内核启动...
2022-09-25 13:19:55 错误: OpenClash 启动失败，尝试还原第三方规则并重新启动 Clash 主程序...
2022-09-25 13:19:55 第六步: 等待主程序下载外部文件...
2022-09-25 13:19:52 第五步: 检查内核启动状态...
2022-09-25 13:19:51 提示: 检测到配置了 Meta 内核专属功能，调用 Meta 内核启动...
2022-09-25 13:19:51 第四步: 启动主程序...
2022-09-25 13:19:51 正在设置第二 DNS 服务器列表...
2022-09-25 13:19:49 提示：您为 SOCKS5/HTTP(S) 代理设置的账户密码为【XXXXXX】
2022-09-25 13:19:48 第三步: 修改配置文件...
2022-09-25 13:19:48 提示: 由于文件【 /etc/config/openclash 】被修改，暂停快速启动...
2022-09-25 13:19:48 第二步: 组件运行前检查...
2022-09-25 13:19:47 第一步: 获取配置...
2022-09-25 13:19:47 OpenClash 开始启动...

![屏幕截图 2022-09-25 132632](https://user-images.githubusercontent.com/70835718/192129680-c97e6067-fb53-42be-8515-f1a5b3894db9.png)

退回1.13.1恢复正常。

**Comment by eightsheep67** [comment]
下面是DNS相关配置文件

dns:
  default-nameserver:
  - 218.85.152.99
  - 218.85.157.99
  - 114.114.114.114
  - 119.29.29.29
  - 4.2.2.1
  - 223.5.5.5
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  nameserver:
  - 218.85.152.99
  - 218.85.157.99
  - 114.114.114.114
  - 119.29.29.29
  - 4.2.2.1
  - 223.5.5.5
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
  fallback:
  - https://dns.cloudflare.com/dns-query
  - tls://dns.google:853
  - https://1.1.1.1/dns-query
  - tls://1.1.1.1:853
  - tls://8.8.8.8:853
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
    - 0.0.0.0/8
    - 10.0.0.0/8
    - 100.64.0.0/10
    - 127.0.0.0/8
    - 169.254.0.0/16
    - 172.16.0.0/12
    - 192.0.0.0/24
    - 192.0.2.0/24
    - 192.88.99.0/24
    - 192.168.0.0/16
    - 198.18.0.0/15
    - 198.51.100.0/24
    - 203.0.113.0/24
    - 224.0.0.0/4
    - 240.0.0.0/4
    - 255.255.255.255/32
    domain:
    - "+.google.com"
    - "+.facebook.com"
    - "+.youtube.com"
    - "+.githubusercontent.com"
    - "+.googlevideo.com"
redir-port: 7892
tproxy-port: 7895
port: 7890
socks-port: 7891
mixed-port: 7893
mode: rule
log-level: debug
allow-lan: true
external-controller: 0.0.0.0:9090
secret: asdf1234
bind-address: "*"
external-ui: "/usr/share/openclash/ui"
ipv6: false
interface-name: pppoe-wan
geodata-mode: true
geodata-loader: standard
tcp-concurrent: true
sniffer:
  enable: true
  sniffing:
  - tls
  - http
  force-domain:
  - google.com
  - "+.netflix.com"
  - "+.nflxvideo.net"
  - "+.amazonaws.com"
  - "+.media.dssott.com"
  skip-domain:
  - Mijia Cloud
  - dlg.io.mi.com
  - "+.apple.com"
  - "+.jd.com"
  port-whitelist:
  - 443
  - 80
profile:
  store-selected: true
  store-fake-ip: true
authentication:
- XXXXXXXXXX

**Comment by eightsheep67** [comment]
下面是DNS相关配置文件

dns:
default-nameserver:

218.85.152.99
218.85.157.99
114.114.114.114
119.29.29.29
4.2.2.1
223.5.5.5
enable: true
ipv6: false
enhanced-mode: redir-host
listen: 0.0.0.0:7874
nameserver:
218.85.152.99
218.85.157.99
114.114.114.114
119.29.29.29
4.2.2.1
223.5.5.5
https://doh.pub/dns-query
https://dns.alidns.com/dns-query
fallback:
https://dns.cloudflare.com/dns-query
tls://dns.google:853
https://1.1.1.1/dns-query
tls://1.1.1.1:853
tls://8.8.8.8:853
fallback-filter:
geoip: true
geoip-code: CN
ipcidr:
0.0.0.0/8
10.0.0.0/8
100.64.0.0/10
127.0.0.0/8
169.254.0.0/16
172.16.0.0/12
192.0.0.0/24
192.0.2.0/24
192.88.99.0/24
192.168.0.0/16
198.18.0.0/15
198.51.100.0/24
203.0.113.0/24
224.0.0.0/4
240.0.0.0/4
255.255.255.255/32
domain:
"+.google.com"
"+.facebook.com"
"+.youtube.com"
"+.githubusercontent.com"
"+.googlevideo.com"
redir-port: 7892
tproxy-port: 7895
port: 7890
socks-port: 7891
mixed-port: 7893
mode: rule
log-level: debug
allow-lan: true
external-controller: 0.0.0.0:9090
secret: XXXXXXXXX
bind-address: "*"
external-ui: "/usr/share/openclash/ui"
ipv6: false
interface-name: pppoe-wan
geodata-mode: true
geodata-loader: standard
tcp-concurrent: true
sniffer:
enable: true
sniffing:
tls
http
force-domain:
google.com
"+.netflix.com"
"+.nflxvideo.net"
"+.amazonaws.com"
"+.media.dssott.com"
skip-domain:
Mijia Cloud
dlg.io.mi.com
"+.apple.com"
"+.jd.com"
port-whitelist:
443
80
profile:
store-selected: true
store-fake-ip: true
authentication:
XXXXXXXXXX

**Comment by liuwentao** [comment]
alpn变成数组了.

**Comment by eightsheep67** [comment]
> alpn变成数组了.

那这个我是需要修改哪个部分呀？

**Comment by MetaCubeX** [comment]
@eightsheep67 alpn : xxx.  改为
alpn :
   - xxx

**Comment by eightsheep67** [comment]
> 

大佬，还是有点不太明白，我搜了下openclash里的配置和alpn有关的，是hysteria的节点

- name: "\U0001F1FA\U0001F1F8美国圣何塞h02"
  type: hysteria
  server: sj2.XXXXXXX.tk
  port: XXXX
  protocol: udp
  up: '37'
  down: '250'
  skip-cert-verify: true
  sni: wechat.com
  alpn: h3
  auth_str: XXXXXXX
  recv_window_conn: '26214400'
  recv_window: '104857600'
  disable_mtu_discovery: false

不知道要怎么修改

**Comment by MetaCubeX** [comment]
@eightsheep67 alpn: h3 =>
alpn: 
  - h3

**Comment by eightsheep67** [comment]
![屏幕截图 2022-10-01 231453](https://user-images.githubusercontent.com/70835718/193416115-40b829c5-ee66-4eda-a7d2-dd1b4c394dd1.png)
这样的意思吗？

**Comment by eightsheep67** [comment]
刚好赶上新的核心c06b48a，改完后可以了。谢谢大佬
