### ISSUE TITLE
SRC-IP Rule

### ISSUE THREAD

**Issue by cornoctopus** [MetaCubeX/Clash.Meta#198]
Hi. this is cross-post from original Clash github. Clash has SRC-IP-CIDR rule but is it possible to implement rule like SRC-IP? In example - 3 clients connect to router with Clash, Clash has rules like:
SRC-IP,192.168.1.22,proxy1
SRC-IP,192.168.1.24,proxy2
SRC-IP,192.168.1.12,proxy3
Then Clash handle every connection from source ip to specific proxy.
Also think I can pay for this feature.

**Comment by LarkinZero** [comment]
`- SRC-IP-CIDR,192.168.1.201/32,DIRECT`

**Comment by cornoctopus** [comment]
> `- SRC-IP-CIDR,192.168.1.201/32,DIRECT`
Thanks bro:)
