### ISSUE TITLE
关于最近大量tls被封的情况，以及修改Clienthello指纹

### ISSUE THREAD

**Issue by moranno** [MetaCubeX/Clash.Meta#204]
在这个讨论中：
https://github.com/net4people/bbs/issues/129#issuecomment-1266617327

说到：
> 这些封锁可能与翻墙软件客户端发出的[Clienthello指纹](https://tlsfingerprint.io/)相关。开发者们或许可以考虑采用[uTLS](https://github.com/refraction-networking/utls)。这个[论文阅读小组](https://github.com/net4people/bbs/issues/54)，[这篇总结](https://gfw.report/blog/v2ray_weaknesses/zh/#%E7%8B%AC%E7%89%B9%E7%9A%84tls-clienthello%E6%8C%87%E7%BA%B9)，以及[这篇博文](https://zhufan.net/2022/06/18/tls%E6%8F%A1%E6%89%8B%E6%8C%87%E7%BA%B9%E6%A3%80%E6%B5%8B%E6%81%B6%E6%84%8F%E8%BD%AF%E4%BB%B6%E6%B5%81%E9%87%8F/)都是关于TLS指纹的，也许会有帮助。

请求在clash中加入uTLS或类似的解决方案。

**Comment by iKingEast** [comment]
同求

**Comment by Skyxim** [comment]
有效性未知
