### ISSUE TITLE
关于geoip 作为默认数据库的问题

### ISSUE THREAD

**Issue by mengxinz** [MetaCubeX/Clash.Meta#205]
受打包机制的限制，读取 v2ray 的 dat 文件时需要将其全部解包，再提取用户实际需要的部分
目前 v2ray 官方的 geoip.dat 大小已经快 11M 了，其内部包含几乎世界全部国家的近百万 IP 段，通常匹配国内规则应该用它那个精简的 cn 版足够了只包含 geoip:cn
https://raw.githubusercontent.com/Loyalsoldier/geoip/release/cn.dat
希望使用精简版的 v2ray 的数据文件以加快启动速度和减少内存占用

**Comment by Rashhz** [comment]
最好能在配置文件中自定义geosite和geoip文件就好了

**Comment by kkkgo** [comment]
你可以自己下载之后重命名geoip.dat放在clash的工作目录的，应该在~/.config/clash里面

**Comment by CHIZI-0618** [comment]
> 最好能在配置文件中自定义geosite和geoip文件的下载url就好了

https://github.com/MetaCubeX/Clash.Meta/issues/220#issuecomment-1336416965

**Comment by rianjskis** [comment]
> > 最好能在配置文件中自定义geosite和geoip文件的下载url就好了
> 
> [#220（评论） ](https://github.com/MetaCubeX/Clash.Meta/issues/220#issuecomment-1336416965)
请问是像这样添加规则集一样添加吗。
rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400
