### ISSUE TITLE
how can I use this on Clash X Pro on MacOS

### ISSUE THREAD

**Issue by hadifarnoud** [MetaCubeX/Clash.Meta#218]
I understand this fork now supports VLESS?

how can I replace clash in Clash X Pro app? the wiki on this repo does not have any tutorial

**Comment by MetaCubeX** [comment]
@hadifarnoud use clashxmeta

**Comment by MetaCubeX** [comment]
@hadifarnoud https://github.com/MetaCubeX/ClashX.Meta/releases

**Comment by skill7899** [comment]
> @hadifarnoud https://github.com/MetaCubeX/ClashX.Meta/releases

mac下面的tun模式，访问不了。设置为系统代理可以。

**Comment by hadifarnoud** [comment]
thanks, Clash X Meta is awesome! I set it up on OpenWRT (via OpenClash) and it works like a charm.

the Tun Mode did not work on MacOS reliably though, like you said.

**Comment by never-afk** [comment]
> @hadifarnoud https://github.com/MetaCubeX/ClashX.Meta/releases

macos tun模式 无限回环 ，又遇到过吗
