### ISSUE TITLE
[Feature] 自动更新Geoip.dat

### ISSUE THREAD

**Issue by kkkgo** [MetaCubeX/Clash.Meta#220]
希望实现可以在不结束进程的情况下能设置定期自动更新GeoIP.dat并重载。最好能配置更新使用的代理。

**Comment by LevineWoo** [comment]
同意，目前还不清楚怎么设置自动更新geoip或geosite文件，另外希望可以自定义下载geoip等文件的地址进行替换，包括mmdb文件。不过都不是紧急的，目前可以每周手动操作。

**Comment by Sakaizd** [comment]
```
%1 mshta vbscript:CreateObject("Shell.Application").ShellExecute("cmd.exe","/c %~s0 ::","","runas",1)(window.close)&&exit

@echo off
taskkill /F /IM "Clash Verge.exe" /T
taskkill /F /IM "clash-meta.exe" /T

//USERNAME  换成自己的
curl  https://gcore.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat -o C:\Users\USERNAME\.config\clash-verge\GeoIP.dat
curl  https://gcore.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat -o C:\Users\USERNAME\.config\clash-verge\GeoSite.dat 
curl  https://gcore.jsdelivr.net/gh/Loyalsoldier/geoip@release/Country.mmdb -o C:\Users\USERNAME\.config\clash-verge\Country.mmdb

//路径 换成自己的
start "" "C:\Program Files\Clash Verge\Clash Verge.exe"

```

**Comment by kkkgo** [comment]
我自己用shell脚本实现了dat更新，并且对比了md5sum。不过其实我想要的是不杀死进程的情况下能重载dat，类似mosdns的auto_reload功能。

**Comment by Sakaizd** [comment]
现在在windows下，使用最新的内核可以在[yacd](https://yacd.metacubex.one/) 的配置里面更新geodata了。

**Comment by rianjskis** [comment]
> 配置文件新增如下配置可指定更新 geo* 文件的地址
> 
> ```
> geox-url:
>       geoip: "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat"
>       mmdb: "https://github.com/Loyalsoldier/geoip/releases/latest/download/Country.mmdb"
>       geosite: "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat"
> ```
> 
> 通过 Clash.Meta 自己的 RESTful web API 可手动触发更新。目前不支持过代理更新它们。
> 
> 可用 RESTful web API 重载配置文件以达到重载 geo* 文件的目的。

请问是像添加规则集一样添加吗，
rule-providers:
  geoip:
    type: http
    behavior: domain
    url: "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat"
    path: ./ruleset/geoip.yaml
    interval: 86400
