### ISSUE TITLE
win11 tun模式可能会选中例如Zerotier的其他接口，导致无法上网

### ISSUE THREAD

**Issue by Rashhz** [MetaCubeX/Clash.Meta#222]
如题，tun模式在启动时可能会选中例如Zerotier的其他虚拟网卡，导致无法上网

**Comment by Rashhz** [comment]
> @Rashhz 先手动指定适配器凑活着用?

主要我经常切换网卡使用（校园网太卡了，晚上得开热点玩），比较希望meta能精准识别能上网的网卡

**Comment by Rashhz** [comment]
> 加个分组测试interface延迟自动选择？

这个要怎么写，interface也可以测延迟吗？有示例配置嘛

**Comment by hdchieh** [comment]
- name: en0DIRECT
    type: select
    interface-name: en0  # 网卡2名称
    proxies:
      - DIRECT

然后测这个分组延迟就行了。

**Comment by wwqgtxx** [comment]
fix in https://github.com/MetaCubeX/Clash.Meta/commit/94a765ee314044cff635629500991672a2a17f56
