### ISSUE TITLE
后台访问可疑链接？

### ISSUE THREAD

**Issue by geoleonsh** [MetaCubeX/Clash.Meta#228]
一直被杀毒软件拦截，具体信息如下，clash-verge项目里的clash.meta
﻿
时间;URL;状态;检测;应用程序;用户;IP 地址;哈希
2022/10/28 23:38:43;http://ocsp.trust-provider.cn/MFIwUDBOMEwwSjAJBgUrDgMCGgUABBQDhvjmfMdSVsHZ9u52p9jqu3rd8gQUXzp8ERB+DGdxYdyLo7UAA2f1VxwCEQDyOx61d9/LahUTCH3MpJWz;已阻止;内部黑名单;E:\ClashV\clash-meta.exe

**Comment by oluceps** [comment]
应该是用于获取证书撤销状态的连接 [ocsp](https://zh.m.wikipedia.org/zh-sg/%E5%9C%A8%E7%BA%BF%E8%AF%81%E4%B9%A6%E7%8A%B6%E6%80%81%E5%8D%8F%E8%AE%AE)
