### ISSUE TITLE
Failed to start TUN on android

### ISSUE THREAD

**Issue by samlux04** [MetaCubeX/Clash.Meta#229]
I couldn't start TUN on android since this commit https://github.com/MetaCubeX/Clash.Meta/commit/94246104b86e741770ec0ef83920d1ec97b61e09

```
tun ] default interface changed by monitor,  => wlan0"
 listening error: configure tun interface: permission denied"
```

Maybe also on openwrt x86_64 https://github.com/vernesong/OpenClash/issues/2762

**Comment by Mars160** [comment]
the same issue
v1.13.1 is ok

**Comment by samlux04** [comment]
> the same issue v1.13.1 is ok

It seems to be fixed with latest commit https://github.com/MetaCubeX/Clash.Meta/commit/94a765ee314044cff635629500991672a2a17f56
![Screenshot_20221107-151513_Clash for Magisk](https://user-images.githubusercontent.com/85811479/200247496-c5442939-d703-48a7-b1b9-19d11be36685.png)

**Comment by Mars160** [comment]
@samlux04 顺便请问一下，您的这个管理器是在哪里下载到的

**Comment by Mars160** [comment]
@wwqgtxx 我确认一下哦，现在1.13.2似乎有其他问题

**Comment by samlux04** [comment]
> @samlux04By the way, where did you download this manager?

It's from telegram. I think it's closed source.
https://t.me/nothing_taamarin
