### ISSUE TITLE
proxy-provider 有办法排出节点吗

### ISSUE THREAD

**Issue by Bitcion** [MetaCubeX/Clash.Meta#231]
部分节点不想用，用正规则要写太多关键词了

**Comment by wwqgtxx** [comment]
support in https://github.com/MetaCubeX/Clash.Meta/commit/0e5bf0c27e5c7fd2e9d3e9b3236ca0b8a4a77be7

**Comment by xishang0128** [comment]
@wwqgtxx (A).*(B)             节点名既有 A 也有 B 
(A)|(B)              节点名有 A 或者 B   
^(?!.*A)             节点名不含有 A 
^(?!.*A).*(B)        节点名不含有 A 但含有 B
^(?!.*(A|B))         节点名既不含有 A 也不含有 B
可以正则filter,自己对着写就行)

**Comment by wzdnzd** [comment]
> @wzdnzd 用filter啊

常见的应用场景就是同一个订阅的某些节点用于某一场景，**剩余**节点用于另外的场景。如果用 `filter` 的话，需要特别设计正则表达式，它们的**并集**便是 `proxy-providers` 提供的节点。

**Comment by Ma3tain** [comment]
@wzdnzd 对啊，用filter啊，clash这边没更好的方法了

**Comment by wwqgtxx** [comment]
@wzdnzd 未来某一天会加

**Comment by wzdnzd** [comment]
简单测试了一下，暂时没问题，感谢👍

**Comment by MelodyUSA** [comment]
>(A).*(B) 节点名既有 A 也有 B
(A)|(B) 节点名有 A 或者 B
^(?!.A) 节点名不含有 A
^(?!.A).(B) 节点名不含有 A 但含有 B
^(?!.(A|B)) 节点名既不含有 A 也不含有 B
可以正则filter,自己对着写就行)

@xishang0128 求指教，我想排除掉機場訂閲中帶'RU'字串的節點，在翻閲了[Go语言正则表达式：regexp](http://c.biancheng.net/view/5124.html) 之後，自己也試了好幾種寫法都不成功。
參考了你上面的總結，filter 項寫下`^(?!.(RU))`，仍舊沒有成功
内核用的是premium，日志顯示不支持語法：
>启动服务(2023/1/27 18:03:21)...
Core类型 clash_premium
17:49:20 FTL [Config] parse config failed error=parse proxy provider Airport error: invalid filter regex: error parsing regexp: invalid or unsupported Perl syntax: `(?!`

猜測是原版 clash 在後續版本中 Fix 了一部分他們認爲不需要的 regexp 包？吧？
雖然 meta-core 已經有 `exclude-filter`，但個別需求原因我需要繼續使用 Premium，另外也想探究學習一下能不能用正則表達式排除不需要的項目。
假設有機場訂閲節點若干，像這樣：
>FR-vmess1-Airport
FR-vmess2-Airport
FR-vmess3-Airport
DE-vmess1-Airport
...
US-vmess1-Airport
US-vmess2--Airport
...

它們有一部分相同字符，也有不同，如何能用正則表達式排除掉`DE` ？求指教🙋‍♂️
