### ISSUE TITLE
1.13.2载入hysteria协议的节点时报错

### ISSUE THREAD

**Issue by auqhjjqdo** [MetaCubeX/Clash.Meta#236]
![image](https://user-images.githubusercontent.com/56216884/199635381-12904ae6-b9ac-4180-be09-d79d65198e53.png)
1.13.2版本在hysteria协议的配置文件里包含alpn字段时，会出现如图所示的报错，测试更换回1.13.1版本正常加载

**Comment by fenger7** [comment]
hysteria传输协议你用的是upd还是wechat-video?

**Comment by auqhjjqdo** [comment]
> hysteria传输协议你用的是udd还是wechat-video?

faketcp和wechat-video都连接不上节点，只有udp能用，但这也是在能载入配置之后才能测试出来连通性，且相同配置使用1.13.1和1.12都能正常连接
根据hysteria的官方wiki，alpn字段是QUIC TLS用的，删除这个字段后连不上网

**Comment by srrshweee** [comment]
> > hysteria传输协议你用的是udd还是wechat-video?
> 
> faketcp和wechat-video都连接不上节点，只有udp能用，但这也是在能载入配置之后才能测试出来连通性，且相同配置使用1.13.1和1.12都能正常连接 根据hysteria的官方wiki，alpn字段是QUIC TLS用的，删除这个字段后连不上网

同样的问题，我是用的faketcp，我参照之前的节点写法就是有问题，包括alpha和1.13.2，但是1.13.1及之前版本的没问题。
建议出个标准的hysteria的config的写法或者模板

**Comment by Ma3tain** [comment]
@srrshweee 你来

**Comment by fenger7** [comment]
我用这个网站转的。
https://v2rayse.com/v2ray-clash/

**Comment by cubemaze** [comment]
@fenger7 因为 alpn 在最新版本是数组

**Comment by auqhjjqdo** [comment]
https://github.com/MetaCubeX/Clash.Meta/commit/88e4a9a755a2e8488cf98e82133221f20e0389f5#diff-2a83a88c7a4e17ea349f0b81faec044c0d84760a4b7761c7913dde8c913084e1R105
经过代码对比，1.13.2修改了config里alpn的数据类型为字符串数组
https://github.com/HyNetwork/hysteria/blob/1c7880e2f6f4ca2d2480c21805c1aaad1ec0a742/cmd/config.go#L57
但hysteria的官方config依旧为string，这样修改有何用意

**Comment by guaguaya66** [comment]
改成 `alpn: ['h3']`

**Comment by srrshweee** [comment]
> @srrshweee 你来

我要是知道，我就不会问问题了

**Comment by fenger7** [comment]
> 改成 `alpn: ['h3']`

感谢，最新版内核已正常可用。wechat-video协议也支持了。

**Comment by flyhigao** [comment]
在 openclash 中遇到相同问题，请问怎么解决?没法手动改啊

**Comment by moranno** [comment]
> @srrshweee 你来

应该按照hysteria官方的写法。

**Comment by Skimmle** [comment]
> > @srrshweee 你来
> 
> 应该按照hysteria官方的写法。

alpn 本来就是数组形式，改成 alpn 是为了和同是 yaml 的 stash 统一。

**Comment by moranno** [comment]
> > > @srrshweee 你来
> > 
> > 
> > 应该按照hysteria官方的写法。
> 
> ALPN 本来就是数组形式，改成 ALPN 是为了和同是 YAML 的 Stash 统一。

Stash的auth_str写法是auth，这个是不是也考虑统一下？

**Comment by Skimmle** [comment]
> 

暂时应该不会了，ALPN 主要是之前两个类型不一样，但是名字冲突了，对于名字不一样的可以同时写保证不冲突暂时不会修改。
也不是完全为了统一
