### ISSUE TITLE
[question] Meta 的 hysteria 是否支持本地 udp 流量(比如游戏)转发？

### ISSUE THREAD

**Issue by moranno** [MetaCubeX/Clash.Meta#237]
在hy的示例配置文档中：https://docs.metacubex.one/example/ex1
没看到有udp: true的配置选项。
请问是否支持udp转发？

**Comment by Adlyq** [comment]
@moranno hy是quic协议。。。。

**Comment by moranno** [comment]
> @moranno hy是quic协议。。。。

嗯嗯，这个我知道，我的意思是本地的udp流量（比如游戏）是否也会通过代理转发出去？
我看到小火箭的hy有这个配置，所以问一下。

**Comment by qist** [comment]
可以支持的。开启udp 转发就是了。

**Comment by 1014670860** [comment]
> 可以支持的。打开udp转发就可以了。

请问怎么打开
