### ISSUE TITLE
v1.13.2和最新的alpha 日志一直对不可用节点进行健康检查 v1.13.1则没有 这个正常吗

### ISSUE THREAD

**Issue by mlwrx1978** [MetaCubeX/Clash.Meta#241]
22-11-05 19:49:50[ debug ]Health Checking RW 15 {ce6b0a76-f141-4c8e-90b0-87645d689630}
22-11-05 19:49:50[ debug ]Health Checked RW 13 : false 65535 ms {ce6b0a76-f141-4c8e-90b0-87645d689630}
22-11-05 19:49:50[ debug ]Health Checking RW 4 {ce6b0a76-f141-4c8e-90b0-87645d689630}
22-11-05 19:49:50[ debug ]Health Checked RW 2 : false 65535 ms {ce6b0a76-f141-4c8e-90b0-87645d689630}
22-11-05 19:49:49[ debug ]Health Checking RW 20 {ce6b0a76-f141-4c8e-90b0-87645d689630}
22-11-05 19:49:49[ debug ]Health Checked RW 1 : false 65535 ms {ce6b0a76-f141-4c8e-90b0-87645d689630}
22-11-05 19:49:49[ debug ]Health Checking RW 10 {ce6b0a76-f141-4c8e-90b0-87645d689630}
22-11-05 19:49:49[ debug ]Health Checked RW 12 : false 65535 ms {ce6b0a76-f141-4c8e-90b0-87645d689630}
22-11-05 19:49:49[ debug ]Health Checking RW 7 {ce6b0a76-f141-4c8e-90b0-87645d689630}
22-11-05 19:49:49[ debug ]Health Checked RW 25 : false 65535 ms {ce6b0a76-f141-4c8e-90b0-87645d689630}
22-11-05 19:49:48[ debug ]Health Checking RW 14 {ce6b0a76-f141-4c8e-90b0-87645d689630}
22-11-05 19:49:48[ debug ]Health Checked RW 23 : false 65535 ms {ce6b0a76-f141-4c8e-90b0-87645d689630}
22-11-05 19:49:48[ info ][TCP] 192.168.50.16:56092 --> clients4.google.com:443 match RuleSet(ProxyLite) using 🚀 节点选择[🇺🇸 US 721]
22-11-05 19:49:48[ debug ]Health Checking RW 21 {ce6b0a76-f141-4c8e-90b0-87645d689630}
22-11-05 19:49:48[ debug ]Health Checked 🇺🇸 US 448 : false 65535 ms {ce6b0a76-f141-4c8e-90b0-87645d689630}
22-11-05 19:49:48[ debug ]Health Checking RW 9 {ce6b0a76-f141-4c8e-90b0-87645d689630}
22-11-05 19:49:48[ debug ]Health Checked RW 22 : false 65535 ms {ce6b0a76-f141-4c8e-90b0-87645d689630}

**Comment by wwqgtxx** [comment]
正常，只是之前版本没有输出日志罢了
