### ISSUE TITLE
tun模式下rule代理UDP始终直连

### ISSUE THREAD

**Issue by dsl888** [MetaCubeX/Clash.Meta#244]
tun模式下rule代理UDP始终直连，不会通过域名进行分流，而且有些网页会有UDP 443的流量，由于一直直连，导致无法正常访问网页

**Comment by qist** [comment]
你的代理开启或者支持udp转发么。

**Comment by dsl888** [comment]
用的是v2ray vmess节点，里面配置了udp，ture，感觉没什么区别，关闭或者开启都是一样的，还有使用openclash的meta核心，访问同样的网站并没有udp 443流量，为啥直接用linux的clash访问就会有，很奇怪

**Comment by dsl888** [comment]
重新建立了个trojan节点，没有这个问题，不知道是不是兼容问题

**Comment by dsl888** [comment]
vmess客户端配置文件加入udp ture就没问题了，此问题关闭
