### ISSUE TITLE
请问Meta支持DoH3吗？

### ISSUE THREAD

**Issue by michaelchen644** [MetaCubeX/Clash.Meta#246]
Google的doh因为运营商封禁8.8.8.8等的TCP连接不能用，但是改用quic后可以使用。
想尝试下DNS over HTTP3，Meta内核是否可以像AdGuardHome一样添加h3://xxx.xxx/dns-querry来强制使用h3进行查询呢？

**Comment by qist** [comment]
你自己看配置资料把

**Comment by none2393** [comment]
https://xxx/xxx#h3=true

**Comment by Rashhz** [comment]
> 

支持的，看下示例配置
