### ISSUE TITLE
x509: “USERTrust RSA Certification Authority”证书不符合标准

### ISSUE THREAD

**Issue by skill7899** [MetaCubeX/Clash.Meta#247]
用clash的不会有这样的问题，证书是acme生成的，已经是full的了
mac版本

**Comment by skill7899** [comment]
我自已配置问题

**Comment by shallbytwo** [comment]
> 我自已配置问题

请问具体怎么解决的 我也遇到这个问题了。之前用着好好的，突然出现这个问题

**Comment by skill7899** [comment]
> > 我自已配置问题
> 
> 请问具体怎么解决的 我也遇到这个问题了。之前用着好好的，突然出现这个问题

看一下是不是放的地方不对了，或者证书错了
