### ISSUE TITLE
mac clashX meta tun模式dns-hijack不生效，导致tun模式不行

### ISSUE THREAD

**Issue by skill7899** [MetaCubeX/Clash.Meta#248]
不知道是不是mac的原因，hijack是不生效的。我看clashxpro是直接修改了我的mac的wifi的dns为192.18.0.2。clashx meta没有做修改，nslookup 可以找到和dig还是看到走的wifi配置的dns。

**Comment by skill7899** [comment]
之前我是用脚本启动的这个命令可以修改wifi的dns
networksetup -setdnsservers Wi-Fi 198.18.0.2
恢复我就很粗暴，直接清空
networksetup -setdnsservers Wi-Fi "Empty"
就会恢复到dhcp给的

**Comment by mrFq1** [comment]
meta 换了sing-tun 所以会和sing-box 有[同样的问题](https://sing-box.sagernet.org/zh/faq/known-issues/)
需要设置一个公网dns

设置系统dns 的相关代码写了一半没写完

**Comment by skill7899** [comment]
> meta 换了sing-tun 所以会和sing-box 有[同样的问题](https://sing-box.sagernet.org/zh/faq/known-issues/) 需要设置一个公网dns
> 
> 设置系统dns 的相关代码写了一半没写完

坐等更新，哈哈不是macos的开发，帮不上什么忙。

**Comment by githublovered** [comment]
只有mac有这个问题吗？我看我windows链接的wifi，然后启动meta，访问不了外网了

**Comment by Skimmle** [comment]
> 不知道是不是mac的原因，hijack是不生效的。我看clashxpro是直接修改了我的mac的wifi的dns为192.18.0.2。clashx meta没有做修改，nslookup 可以找到和dig还是看到走的wifi配置的dns。

这是 GUI 做的，原本 P 核也是，内核没有处理这个，需要软件处理。不过的确需要设置一个到网络中 要么是公网 DNS，要么是 Tun 的特别 DNS

**Comment by Ssiswent** [comment]
你好，请问你在macOS上是如何使用服务的呢，我看wiki似乎只有Linux的运行教程
https://wiki.metacubex.one/startup/service/
