### ISSUE TITLE
游戏游戏：NAT检测失败

### ISSUE THREAD

**Issue by clift190** [MetaCubeX/Clash.Meta#25]
GTA5检测NAT类型失败，原版核心为NAT2，其实VPS为NAT1

**Comment by MetaCubeX** [comment]
@clift190 协议方式告知一下

**Comment by clift190** [comment]
UDP

**Comment by MetaCubeX** [comment]
@clift190 是问你用啥协议，不是tcp或udp……

**Comment by clift190** [comment]
vmess ，原版也是用同一协议同一节点，使用TUN方式。用netch这个节点就是NAT1，进入GTA5显示NAT开放

**Comment by Rakau** [comment]
CFM和Openclash表示正常

**Comment by MetaCubeX** [comment]
> GTA5检测NAT类型失败，原版核心为NAT2，其实VPS为NAT1

下载最新的alpha测试

**Comment by clift190** [comment]
最新CFW0.19.15，最新alpha内核，多个节点测试，问题未能解决：
vmess ，TUN方式，进入GTA5显示NAT检测失败。
原内核，显示为NAT中等
NETCH，显示为NAT开放

**Comment by clift190** [comment]
> 最新CFW0.19.15，最新alpha内核，多个节点测试，问题未能解决：
 vmess ，TUN方式，进入GTA5显示NAT检测失败
 原内核，显示为NAT中等
 NETCH，显示为NAT开放

**Comment by clift190** [comment]
> > GTA5检测NAT类型失败，原版核心为NAT2，其实VPS为NAT1
> 
> 下载最新的alpha测试

最新CFW0.19.15，最新alpha内核，多个节点测试，问题未能解决：
vmess ，TUN方式，进入GTA5显示NAT检测失败
原内核，显示为NAT中等
NETCH，显示为NAT开放

**Comment by MetaCubeX** [comment]
> 

今天编译的alpha替换试过了吗

**Comment by Mirr0ch1** [comment]
最新版本的确是GTA5里不能用 UDP，但是却能 p2p 上别的玩家。。。（原版内核就不行）
这玩意简直神了，老板有兴趣贴个捐赠链接不。。。你这省了我一笔加速器的钱。

**Comment by vj23456** [comment]
@Mirr0ch1 路由 tproxy  
ss/vemss
测试都可以 fullcone

**Comment by Rakau** [comment]
> 最新版本的确是GTA5里不能用 UDP，但是却能 p2p 上别的玩家。。。（原版内核就不行） 这玩意简直神了，老板有兴趣贴个捐赠链接不。。。你这省了我一笔加速器的钱。

这内核支持Xray的VMESS，当然可以Fullcone

**Comment by bash99** [comment]
打扰了，请问最新稳定版v1.10.0 支持 fullcone吗，协议是vless/grpc, 服务端xray？

直接用xray客户端用NatTypeTester测是支持的。但是clash.meta测速不支持，试着下载了alpha版（6天前的），死循环了，似乎把所有Ip当 lancidr处理了。最新的beta也不行

配置如下：
  - name: "2019"
    type: vless
    server: xxx.yyy.com
    port: 443
    uuid: "myuuid"
    tls: true
    udp: true
    network: grpc
    grpc-opts:
      multiMode: true
      idle_timeout: 67
      grpc-service-name: myservicename

**Comment by MetaCubeX** [comment]
@bash99 vless未跟进xudp，所以不支持fullcone。另外你说的死循环，请使用最新alpha[有commit会自动build了替换]，再麻烦贴一下log看看。

**Comment by bash99** [comment]
> @bash99 vless未跟进xudp，所以不支持fullcone。另外你说的死循环，请使用最新alpha[有commit会自动build了替换]，再麻烦贴一下log看看。

看release里面, alpha的还是6 days ago啊？是这个吗？

我以为clash的vless支持是和xray基本一致的。
其实不只是fullcone，感觉这个配置下(vless + grpc），udp就不太支持。

我看youtube就碰到了问题，切广告之后回来就卡顿，看Log发现是同时有udp 443端口请求发送出去，但是没下载速率，直到反复几次就切回纯tcp。估计是在尝试quic协议。后来我单独block youtube的udp请求，问题就解决了。

**Comment by Skyxim** [comment]
@bash99 alpha 时间不作为参考，唯一参考只有commit id ，包后面携带的那串数字

**Comment by Skyxim** [comment]
@bash99 还有你说的环流，具体 配置是什么

**Comment by bash99** [comment]
> @bash99 还有你说的环流，具体 配置是什么

可能我表达错误，看见不停的刷新log，cpu使用到了85%，我下意识就以为是死循环，关掉了进程。
这次重定向log，截取了前面几秒上传了。 alpha的文件名是 Clash.Meta-windows-amd64v3-alpha-663bf4f.zip

具体配置应该就是正常配置，urltest 几个proxy，然后按规则分流，beta版和正式版都运行正常。如果需要我再上传一个脱敏版本的config.yaml上来。

[clash_log.zip](https://github.com/MetaCubeX/Clash.Meta/files/8644815/clash_log.zip)
log文件如上，看了看，都是访问一些广播地址，每秒钟重复数百行

time="2022-05-07T17:24:15+08:00" level=info msg="Mixed(http+socks) proxy listening at: 127.0.0.1:7890"
time="2022-05-07T17:24:15+08:00" level=info msg="TUN stack listening at: Meta(198.18.0.1), mtu: 9000, auto route: true, ip stack: gVisor"
time="2022-05-07T17:24:15+08:00" level=info msg="[UDP] 198.18.0.1:137(:System) --> 198.18.255.255:137 match RuleSet(lancidr) using DIRECT"
time="2022-05-07T17:24:15+08:00" level=info msg="[UDP] 198.18.0.1:53259(Clash.Meta-windows-amd64v3.exe) --> 198.18.255.255:137 match RuleSet(lancidr) using DIRECT"
time="2022-05-07T17:24:15+08:00" level=info msg="[UDP] 198.18.0.1:53260(Clash.Meta-windows-amd64v3.exe) --> 198.18.255.255:137 match RuleSet(lancidr) using DIRECT"
time="2022-05-07T17:24:15+08:00" level=info msg="[UDP] 198.18.0.1:53261(Clash.Meta-windows-amd64v3.exe) --> 198.18.255.255:137 match RuleSet(lancidr) using DIRECT"
...
time="2022-05-07T17:24:16+08:00" level=info msg="[UDP] 198.18.0.1:60384(Clash.Meta-windows-amd64v3.exe) --> 224.0.0.252:5355 match RuleSet(lancidr) using DIRECT"
time="2022-05-07T17:24:16+08:00" level=info msg="[UDP] 198.18.0.1:60385(Clash.Meta-windows-amd64v3.exe) --> 224.0.0.251:5353 match RuleSet(lancidr) using DIRECT"
time="2022-05-07T17:24:16+08:00" level=info msg="[UDP] 198.18.0.1:60386(Clash.Meta-windows-amd64v3.exe) --> 198.18.255.255:137 match RuleSet(lancidr) using DIRECT"
time="2022-05-07T17:24:16+08:00" level=info msg="[UDP] 198.18.0.1:60387(Clash.Meta-windows-amd64v3.exe) --> 224.0.0.252:5355 match RuleSet(lancidr) using DIRECT"
time="2022-05-07T17:24:16+08:00" level=info msg="[UDP] 198.18.0.1:60388(Clash.Meta-windows-amd64v3.exe) --> 224.0.0.251:5353 match RuleSet(lancidr) using DIRECT"
time="2022-05-07T17:24:16+08:00" level=info msg="[UDP] 198.18.0.1:60390(Clash.Meta-windows-amd64v3.exe) --> 224.0.0.252:5355 match RuleSet(lancidr) using DIRECT"
time="2022-05-07T17:24:16+08:00" level=info msg="[UDP] 198.18.0.1:60389(Clash.Meta-windows-amd64v3.exe) --> 198.18.255.255:137 match 
...

**Comment by Skyxim** [comment]
@bash99 哦对了 最新版本auto-detect-interface变成默认false了，没看到配置，不知道你加没，可以尝试添加

**Comment by bash99** [comment]
> @bash99 哦对了 最新版本auto-detect-interface变成默认false了，没看到配置，不知道你加没，看日志是没有的，可以尝试添加

大量访问广播地址确实和这个有关，加了之后解决了。但是udp还是不通，youtube那边能看见udp链接，下载速率几百B或者1.x KB 每秒，最后还是转到tcp正常。
