### ISSUE TITLE
[更新]Xray-core v1.6.3 重要功能更新 XTLS Vision

### ISSUE THREAD

**Issue by adslcool** [MetaCubeX/Clash.Meta#254]
[Xray-core v1.6.3](https://github.com/XTLS/Xray-core/releases/tag/v1.6.3) Pre-release
xtls-rprx-vision
详情：[Xray-core v1.6.2 release note](https://github.com/XTLS/Xray-core/releases/tag/v1.6.2)
模板：[VLESS-TCP-XTLS-Vision](https://github.com/XTLS/Xray-examples/tree/main/VLESS-TCP-XTLS-Vision)
原理：https://github.com/XTLS/Xray-core/discussions/1295 [[ENG](https://github.com/seakfind/examples/blob/main/xtls-vision/README.md)]
Feature
XTLS Vision 现已支持通过 uTLS 库 模拟 Chrome / Firefox / Safari 或随机生成的指纹（[tls fingerprint 参数](https://xtls.github.io/config/transport.html#tlsobject)）

**Comment by xishang0128** [comment]
@adslcool 让一个软件追另一个软件还在dev的东西,是不是有点什么毛病?

**Comment by adslcool** [comment]
@xishang0128 好吧，Dev

**Comment by iKira** [comment]
> 
话不能这么说，如果你是开发者，这么说的话无可厚非，人家自己的选择。
你认为不合理可以说出你的观点和想法，上来就“有毛病”，就这样的行为不知道“有毛病”的是谁呢？

**Comment by htfcuddles** [comment]
现在TLS封锁太厉害，Meta支持的协议不套CDN基本都封了，去追一个暂时能用的协议有什么问题？

**Comment by bash99** [comment]
> 现在TLS封锁太厉害，Meta支持的协议不套CDN基本都封了，去追一个暂时能用的协议有什么问题？

感觉不同地区差异很大啊，我所在地方 接入用caddy/nginx，协议走grpc的暂时还好。外围如果是xray之类，感觉服务器指纹风险比较高（jarm指纹）

**Comment by iKira** [comment]
> > 现在TLS封锁太厉害，Meta支持的协议不套CDN基本都封了，去追一个暂时能用的协议有什么问题？
> 
> 感觉不同地区差异很大啊，我所在地方 接入用caddy/nginx，协议走grpc的暂时还好。外围如果是xray之类，感觉服务器指纹风险比较高（jarm指纹）

很多小白都不会仔细研究配置文件的，清一色的“一键脚本”一条龙服务。用这些脚本不见得会前置Caddy或Nginx。

**Comment by adslcool** [comment]
1.6.3 （1.6.4也发布）版本改进了XTLS 里面改进了自身的一个明显特征，XTLS（TLS1.3才能运行）里面如果访问TLS1.2或者其它版本的服务，就会出现TLS1.3里面包含TLS其它版本的特征，新版本加了判断，如果访问目标是TLS1.3（国外网络服务大部分都是TLS1.3） 就直接无缝拼接（减少加密解密环节）否则全部加密，可以说挺重要的一个改进，而且uTLS指纹伪装功能模拟浏览器(NaiveProxy就是)，问题其实Xray早有预判（他预判了你的预判），之前版本早就加入这个功能，现在只是提一下，大家可以用。

**Comment by adslcool** [comment]
至于封锁原因（还有各种自己技术不到位的一键脚本），各自不同，前段时间开会，反正我部署的Caddy+NaieProxy也照样封，这Jarm总是Caddy的 了吧，如果特殊时刻执行白名单，浏览一大就封一端时间端口，那什么协议也没办法。

**Comment by iKira** [comment]
> 至于封锁原因（还有各种自己技术不到位的一键脚本），各自不同，前段时间开会，反正我部署的Caddy+NaiveProxy也照样封，这Jarm总是Caddy的 了吧，如果特殊时刻执行白名单，流量一大就封一端时间端口，那和协议有什么关系。

也可能是老早之前因所谓的开源协议问题双方大规模辩论一番后，导致部分人一直对xray有不可磨灭的偏见。（仅仅是猜测，不要来对号入座，来入座了你就是对的）

**Comment by bash99** [comment]
> 至于封锁原因（还有各种自己技术不到位的一键脚本），各自不同，前段时间开会，反正我部署的Caddy+NaiveProxy也照样封，这Jarm总是Caddy的 了吧，如果特殊时刻执行白名单，流量一大就封一端时间端口，那和协议有什么关系。

这个是不是重点ip + 全局代理被抓了特征？我的caddy + naive没封过。

**Comment by yoohooyoo** [comment]
+1 
vision协议已经发布正式版1.7.0
https://github.com/XTLS/Xray-core/releases/tag/v1.7.0
希望meta能够支持，解决tls in tls问题

**Comment by fredericky123** [comment]
+1 求支持

**Comment by cubemaze** [comment]
@fredericky123 建议pr

**Comment by LiuTangLei** [comment]
有大佬提pr吗

**Comment by ZhuangJiayu** [comment]
https://github.com/XTLS/Xray-core/releases/tag/v1.7.3

Xray-core v1.8.0 会加入对 [REALITY](https://github.com/XTLS/REALITY) 的支持，并且可能会移除对旧版 XTLS 的支持，请尽快迁移到 XTLS Vision

**Comment by lialosiu** [comment]
临时用的话，起一个xray跑vision出站当作前置，出一个socks5的入站给clash不就好了，吃不了多少资源的啦（ 
<del>虽然有点蠢</del>

**Comment by iciness** [comment]
> 临时用的话，起一个xray跑vision出站当作前置，出一个socks5的入站给clash不就好了，吃不了多少资源的啦（ ~虽然有点蠢~

我一直这么在用😂

**Comment by H1JK** [comment]
Added in #406.
