### ISSUE TITLE
最新的Release用Tun会崩溃

### ISSUE THREAD

**Issue by csy19960309** [MetaCubeX/Clash.Meta#26]
> panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x88831b]
goroutine 124115 [running]:
github.com/Dreamacro/clash/adapter/inbound.NewSocket({0xc00140a2e8?, 0xc00018e780?, 0x4?}, {0x1d9cd7b10c0?, 0xc003649140}, 0xc)
	github.com/Dreamacro/clash/adapter/inbound/socket.go:16 +0x5b
github.com/Dreamacro/clash/listener/tun/ipstack/gvisor.(*GVHandler).HandleTCP(0xc003997ef0, {0xe1a038, 0xc003649140})
	github.com/Dreamacro/clash/listener/tun/ipstack/gvisor/handler.go:77 +0x21d
github.com/Dreamacro/clash/listener/tun/ipstack/gvisor.withTCPHandler.func1.1(0xc0006a8040)
	github.com/Dreamacro/clash/listener/tun/ipstack/gvisor/tcp.go:61 +0x22c
created by gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*Forwarder).HandlePacket
	gvisor.dev/gvisor@v0.0.0-20220326024801-5d1f3d24cb84/pkg/tcpip/transport/tcp/forwarder.go:94 +0x3b0

**Comment by MetaCubeX** [comment]
@csy19960309 请查看-v 获取一下版本好号

**Comment by csy19960309** [comment]
> @csy19960309 请查看-v 获取一下版本好号

Clash Meta alpha-88e4b35 windows amd64 with go1.18 Wed Mar 30 16:26:51 UTC 2022

**Comment by MetaCubeX** [comment]
@csy19960309 看看system堆栈是否会复现问题？
另外Log部分是停在哪里裂开的？

**Comment by csy19960309** [comment]
> @csy19960309 看看system堆栈是否会复现问题？ 另外Log部分是停在哪里裂开的？

system stack我回头测试下吧，我以为meta核只支持gvisor来着。

崩溃前的log是这样的。
> time="2022-04-01T16:49:37+08:00" level=debug msg="[Process] pic2.zhimg.com from process \\Device\\HarddiskVolume2\\Program Files\\Waterfox\\waterfox.exe"
time="2022-04-01T16:49:37+08:00" level=debug msg="[DNS] pic1.zhimg.com --> 221.231.81.243"
time="2022-04-01T16:49:37+08:00" level=debug msg="[DNS] static.zhihu.com --> 58.215.89.123"
time="2022-04-01T16:49:37+08:00" level=debug msg="[Process] static.zhihu.com from process \\Device\\HarddiskVolume2\\Program Files\\Waterfox\\waterfox.exe"
time="2022-04-01T16:49:37+08:00" level=debug msg="[DNS] static.zhihu.com --> 218.92.220.158"
time="2022-04-01T16:49:37+08:00" level=debug msg="[TUN] hijack dns udp: 198.18.0.2:53"
time="2022-04-01T16:49:37+08:00" level=debug msg="[Process] www.zhihu.com from process \\Device\\HarddiskVolume2\\Program Files\\Waterfox\\waterfox.exe"
time="2022-04-01T16:49:37+08:00" level=debug msg="[TUN] hijack dns udp: 198.18.0.2:53"
time="2022-04-01T16:49:37+08:00" level=debug msg="[DNS] pic2.zhimg.com --> 114.80.30.41"
time="2022-04-01T16:49:37+08:00" level=debug msg="[TUN] hijack dns udp: 198.18.0.2:53"
time="2022-04-01T16:49:37+08:00" level=debug msg="[TUN] hijack dns udp: 198.18.0.2:53"
time="2022-04-01T16:49:37+08:00" level=debug msg="[Process] hm.baidu.com from process \\Device\\HarddiskVolume2\\Program Files\\Waterfox\\waterfox.exe"
time="2022-04-01T16:49:37+08:00" level=debug msg="[Process] (公网ip) from process \\Device\\HarddiskVolume2\\Program Files (x86)\\Oray\\SunLogin\\SunloginClient\\SunloginClient.exe"
time="2022-04-01T16:49:37+08:00" level=info msg="[TCP] 198.18.0.1:57211(waterfox.exe) --> pic2.zhimg.com:443 match DomainSuffix(zhimg.com) using China-Websites[DIRECT]"
time="2022-04-01T16:49:37+08:00" level=info msg="[TCP] 198.18.0.1:57207(waterfox.exe) --> pic1.zhimg.com:443 match DomainSuffix(zhimg.com) using China-Websites[DIRECT]"
time="2022-04-01T16:49:37+08:00" level=debug msg="[DNS] www.zhihu.com --> 180.153.93.94"
time="2022-04-01T16:49:37+08:00" level=debug msg="[DNS] hm.baidu.com --> 220.181.33.11"
time="2022-04-01T16:49:37+08:00" level=info msg="[TCP] 198.18.0.1:57217(waterfox.exe) --> www.zhihu.com:443 match DomainSuffix(zhihu.com) using China-Websites[DIRECT]"

就正常使用。

**Comment by MetaCubeX** [comment]
> > @csy19960309 看看system堆栈是否会复现问题？ 另外Log部分是停在哪里裂开的？
> 
> system stack我回头测试下吧，我以为meta核只支持gvisor来着。
> 
> 崩溃前的log是这样的。
> 
> > time="2022-04-01T16:49:37+08:00" level=debug msg="[Process] pic2.zhimg.com from process \Device\HarddiskVolume2\Program Files\Waterfox\waterfox.exe"
> > time="2022-04-01T16:49:37+08:00" level=debug msg="[DNS] pic1.zhimg.com --> 221.231.81.243"
> > time="2022-04-01T16:49:37+08:00" level=debug msg="[DNS] static.zhihu.com --> 58.215.89.123"
> > time="2022-04-01T16:49:37+08:00" level=debug msg="[Process] static.zhihu.com from process \Device\HarddiskVolume2\Program Files\Waterfox\waterfox.exe"
> > time="2022-04-01T16:49:37+08:00" level=debug msg="[DNS] static.zhihu.com --> 218.92.220.158"
> > time="2022-04-01T16:49:37+08:00" level=debug msg="[TUN] hijack dns udp: 198.18.0.2:53"
> > time="2022-04-01T16:49:37+08:00" level=debug msg="[Process] [www.zhihu.com](http://www.zhihu.com) from process \Device\HarddiskVolume2\Program Files\Waterfox\waterfox.exe"
> > time="2022-04-01T16:49:37+08:00" level=debug msg="[TUN] hijack dns udp: 198.18.0.2:53"
> > time="2022-04-01T16:49:37+08:00" level=debug msg="[DNS] pic2.zhimg.com --> 114.80.30.41"
> > time="2022-04-01T16:49:37+08:00" level=debug msg="[TUN] hijack dns udp: 198.18.0.2:53"
> > time="2022-04-01T16:49:37+08:00" level=debug msg="[TUN] hijack dns udp: 198.18.0.2:53"
> > time="2022-04-01T16:49:37+08:00" level=debug msg="[Process] hm.baidu.com from process \Device\HarddiskVolume2\Program Files\Waterfox\waterfox.exe"
> > time="2022-04-01T16:49:37+08:00" level=debug msg="[Process] (公网ip) from process \Device\HarddiskVolume2\Program Files (x86)\Oray\SunLogin\SunloginClient\SunloginClient.exe"
> > time="2022-04-01T16:49:37+08:00" level=info msg="[TCP] 198.18.0.1:57211(waterfox.exe) --> pic2.zhimg.com:443 match DomainSuffix(zhimg.com) using China-Websites[DIRECT]"
> > time="2022-04-01T16:49:37+08:00" level=info msg="[TCP] 198.18.0.1:57207(waterfox.exe) --> pic1.zhimg.com:443 match DomainSuffix(zhimg.com) using China-Websites[DIRECT]"
> > time="2022-04-01T16:49:37+08:00" level=debug msg="[DNS] [www.zhihu.com](http://www.zhihu.com) --> 180.153.93.94"
> > time="2022-04-01T16:49:37+08:00" level=debug msg="[DNS] hm.baidu.com --> 220.181.33.11"
> > time="2022-04-01T16:49:37+08:00" level=info msg="[TCP] 198.18.0.1:57217(waterfox.exe) --> [www.zhihu.com:443](http://www.zhihu.com:443) match DomainSuffix(zhihu.com) using China-Websites[DIRECT]"
> 
> 就正常使用。

最近还有复现崩溃吗？

**Comment by csy19960309** [comment]
> > > @csy19960309 看看system堆栈是否会复现问题？ 另外Log部分是停在哪里裂开的？
> > 
> > 
> > system stack我回头测试下吧，我以为meta核只支持gvisor来着。
> > 崩溃前的log是这样的。
> > > time="2022-04-01T16:49:37+08:00" level=debug msg="[Process] pic2.zhimg.com from process \Device\HarddiskVolume2\Program Files\Waterfox\waterfox.exe"
> > > time="2022-04-01T16:49:37+08:00" level=debug msg="[DNS] pic1.zhimg.com --> 221.231.81.243"
> > > time="2022-04-01T16:49:37+08:00" level=debug msg="[DNS] static.zhihu.com --> 58.215.89.123"
> > > time="2022-04-01T16:49:37+08:00" level=debug msg="[Process] static.zhihu.com from process \Device\HarddiskVolume2\Program Files\Waterfox\waterfox.exe"
> > > time="2022-04-01T16:49:37+08:00" level=debug msg="[DNS] static.zhihu.com --> 218.92.220.158"
> > > time="2022-04-01T16:49:37+08:00" level=debug msg="[TUN] hijack dns udp: 198.18.0.2:53"
> > > time="2022-04-01T16:49:37+08:00" level=debug msg="[Process] [www.zhihu.com](http://www.zhihu.com) from process \Device\HarddiskVolume2\Program Files\Waterfox\waterfox.exe"
> > > time="2022-04-01T16:49:37+08:00" level=debug msg="[TUN] hijack dns udp: 198.18.0.2:53"
> > > time="2022-04-01T16:49:37+08:00" level=debug msg="[DNS] pic2.zhimg.com --> 114.80.30.41"
> > > time="2022-04-01T16:49:37+08:00" level=debug msg="[TUN] hijack dns udp: 198.18.0.2:53"
> > > time="2022-04-01T16:49:37+08:00" level=debug msg="[TUN] hijack dns udp: 198.18.0.2:53"
> > > time="2022-04-01T16:49:37+08:00" level=debug msg="[Process] hm.baidu.com from process \Device\HarddiskVolume2\Program Files\Waterfox\waterfox.exe"
> > > time="2022-04-01T16:49:37+08:00" level=debug msg="[Process] (公网ip) from process \Device\HarddiskVolume2\Program Files (x86)\Oray\SunLogin\SunloginClient\SunloginClient.exe"
> > > time="2022-04-01T16:49:37+08:00" level=info msg="[TCP] 198.18.0.1:57211(waterfox.exe) --> pic2.zhimg.com:443 match DomainSuffix(zhimg.com) using China-Websites[DIRECT]"
> > > time="2022-04-01T16:49:37+08:00" level=info msg="[TCP] 198.18.0.1:57207(waterfox.exe) --> pic1.zhimg.com:443 match DomainSuffix(zhimg.com) using China-Websites[DIRECT]"
> > > time="2022-04-01T16:49:37+08:00" level=debug msg="[DNS] [www.zhihu.com](http://www.zhihu.com) --> 180.153.93.94"
> > > time="2022-04-01T16:49:37+08:00" level=debug msg="[DNS] hm.baidu.com --> 220.181.33.11"
> > > time="2022-04-01T16:49:37+08:00" level=info msg="[TCP] 198.18.0.1:57217(waterfox.exe) --> [www.zhihu.com:443](http://www.zhihu.com:443) match DomainSuffix(zhihu.com) using China-Websites[DIRECT]"
> > 
> > 
> > 就正常使用。
> 
> 最近还有复现崩溃吗？

没有了，system stack 平稳运行。

**Comment by MetaCubeX** [comment]
@csy19960309 在alpha 的pre release已经修复该问题，可直接下载

**Comment by csy19960309** [comment]
> @csy19960309 在alpha 的pre release已经修复该问题，可直接下载

好的，辛苦了。
