### ISSUE TITLE
您好请问我在clash.net中替换mate不显示代理的界面，但是开启代理有网络能用是啥原因呀。

### ISSUE THREAD

**Issue by rianjskis** [MetaCubeX/Clash.Meta#261]
![mate核心](https://user-images.githubusercontent.com/86937445/201949616-568e2bc4-a628-4704-a666-8f76fdfe17e2.jpg)
![原核心显示](https://user-images.githubusercontent.com/86937445/201949641-707c549e-51c2-435d-a197-0312af6396d2.jpg)
第一张是mate核心的，第二张是原核心。

**Comment by kunish** [comment]
估计是接口不通用导致的
