### ISSUE TITLE
releases中Assets的文件名能否去除最后commit

### ISSUE THREAD

**Issue by 2dust** [MetaCubeX/Clash.Meta#27]
您好
最近想做检查更新Clash.Meta core的功能，发现releases中Assets的文件名不是很方便处理，所以提出此issue。

[Clash.Meta-windows-amd64-v1.9.0-8-g89609cc.zip](https://github.com/MetaCubeX/Clash.Meta/releases/download/v1.9.0/Clash.Meta-windows-amd64-v1.9.0-8-g89609cc.zip)

**Comment by MetaCubeX** [comment]
有推荐的格式嘛

**Comment by 2dust** [comment]
v2ray的发布文件名是最方便的，
大概这样[Clash.Meta-{平台}-{位数}.zip]

```
Clash.Meta-windows-64.zip
Clash.Meta-windows-32.zip
Clash.Meta-windows-arm64.zip
Clash.Meta-windows-arm32.zip

```

**Comment by Skyxim** [comment]
@2dust commitid只是方便测试版的大包 release 不会有

**Comment by MetaCubeX** [comment]
@2dust 这应该是release的格式推荐是吧，alpha还是带的commit区分。我今天看看把1.9.0的release给更到最新

**Comment by 2dust** [comment]
> @2dust 这应该是release的格式推荐是吧，alpha还是带的commit区分。我今天看看把1.9.0的release给更到最新

release的，测试的可以保持不动。自动更新只会使用正式版

**Comment by MetaCubeX** [comment]
@2dust 好的，另外感谢大佬关注到这个小项目~

**Comment by 2dust** [comment]
请问这三个有什么区别？
Clash.Meta-windows-amd64v1.zip
Clash.Meta-windows-amd64v2.zip
Clash.Meta-windows-amd64v3.zip

**Comment by MetaCubeX** [comment]
@2dust 指令集不同，嫌麻烦的直接v1

**Comment by 2dust** [comment]
> 
感谢回复，暂时使用v1.

**Comment by 2dust** [comment]
@MetaCubeX 
windows-amd64 在v1.11.1时有V1,V2,V3
到了https://github.com/MetaCubeX/Clash.Meta/releases/tag/v1.11.2
V1,V2,V3没有了?

**Comment by Skyxim** [comment]
> @MetaCubeX
> windows-amd64 在v1.11.1时有V1,V2,V3
> 到了https://github.com/MetaCubeX/Clash.Meta/releases/tag/v1.11.2
> V1,V2,V3没有了?

为了减少剔除了v1版本 compatible是v2 有什么影响吗

**Comment by 2dust** [comment]
> > @MetaCubeX
> > windows-amd64 在v1.11.1时有V1,V2,V3
> > 到了https://github.com/MetaCubeX/Clash.Meta/releases/tag/v1.11.2
> > V1,V2,V3没有了?
> 
> 为了减少数量 剔除了v1版本 compatible是v2 有什么影响吗

没有问题，只要保证名称一致就好，方便GUI更新core。
那么现在windows-amd64使用这个版本是吗？ [Clash.Meta-windows-amd64-v1.11.2.zip](https://github.com/MetaCubeX/Clash.Meta/releases/download/v1.11.2/Clash.Meta-windows-amd64-v1.11.2.zip)

**Comment by Skyxim** [comment]
@2dust 如果想尽量兼容还是compatible吧 虽然从4代intel都是v3的cpu了

**Comment by 2dust** [comment]
> 

多谢，那就默认使用compatible
