### ISSUE TITLE
关于跟进hysteria的客户端更新，以支持port hopping以及0RTT

### ISSUE THREAD

**Issue by moranno** [MetaCubeX/Clash.Meta#270]
hy1.3.0版本加入了一个很好的功能port hopping: https://hysteria.network/zh/docs/port-hopping/
能极大的缓解运营商qos。
edit:
另外今天刚刚更新的1.3.1又增加了0RTT的选项，能极大的降低延迟。

希望meta的hy客户端能跟进更新！

感谢开发者的辛劳付出，我之前说的资金支持一直有效，希望能联系我tg：@missmoranno

**Comment by geoleonsh** [comment]
#269

**Comment by Job28703** [comment]
支持port hopping!!跟进hysteria的客户端更新

**Comment by Zxis233** [comment]
感谢开发者的辛勤付出！

**Comment by moranno** [comment]
今天刚刚更新的1.3.1又增加了0RTT的选项，能极大的降低延迟。
