### ISSUE TITLE
路由器 开启 tun  ，启动报 “level=error msg="Start TUN listening error: configure tun interface: permission denied”

### ISSUE THREAD

**Issue by dogtapdsd** [MetaCubeX/Clash.Meta#285]
系统:asuswrt-merlin 386.7_2
clash meta 版本1.13.2
TUN 配置：
tun:
  enable: true
  device: tun0
  stack: gVisor 
  dns-hijack:
     - 0.0.0.0:53
  auto-route: true 
  inet4_route_address:
    - 0.0.0.0/1
    - 128.0.0.0/1

启动Tun失败，日志报错
time="2022-12-04T12:01:32+08:00" level=error msg="Start TUN listening error: configure tun interface: permission denied"
使用了 modprobe tun 加载
修改了 /dev/net/tun 权限
chmod 777 /dev/net/tun
 ls -lrth /dev/net/tun
crwxrwxrwx    1 admin    root       10, 200 Dec  4 11:44 /dev/net/tun

**Comment by CHIZI-0618** [comment]
@dogtapdsd tun:
  enable: true
  inet6-address:
  stack: system # or gvisor
  dns-hijack:
    - 'any:53'
  auto-route: true
  auto-detect-interface: true

临时 inet6-address: 置空

或者更新最新 Alpha 内核

**Comment by dogtapdsd** [comment]
inet6-address:
thanks，置空后没问题了
