### ISSUE TITLE
相比Clash原版，内存占用有点高？

### ISSUE THREAD

**Issue by bash99** [MetaCubeX/Clash.Meta#286]
刚刚试了，同配置下clash原版启动占26M内存，Clash.Meta启动占116M内存。
这个配置没开tun，协议仅trojan和socks5，开启dns。

家里的特殊配置，有vless协议等，开tun，长期占用256M内存。

总体内存够用，就是感觉这样不利于在小路由器上部署。

**Comment by wwqgtxx** [comment]
@bash99 试一下最新alpha版内存情况是否有所降低

**Comment by bash99** [comment]
> @bash99 试一下最新alpha版内存情况是否有所降低

从 116M 降到了 76M，有改善

**Comment by fireinrain** [comment]
所以问题解决了 把issue关了吧
