### ISSUE TITLE
可能是DNS相关问题

### ISSUE THREAD

**Issue by La-Hire** [MetaCubeX/Clash.Meta#29]
1.10.0版本，开启服务大概率出现下面这种，然后连不上

> "[TCP] dial Proxy (match GeoIP/TELEGRAM) to 149.154.167.51:443 error: 节点域名:端口 connect error: all DNS requests failed, first error: Post \"https://dns.adguard.com/dns-query\": couldn't find ip"

之前使用的alpha-611ce5f版本正常，没有这个问题

个人的config.yaml头部如下，win平台。

mixed-port: 1083
geodata-mode: true
tun:
  enable: true
  stack: gvisor #  only gvisor
  dns-hijack:
    - 198.18.0.2:53
  auto-route: true # auto set global route
interfacename: "WLAN"
allow-lan: true
ipv6: true
dns: 
  enable: true
  listen: 127.0.0.1:1053
  ipv6: true
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  nameserver: 
    - https://rubyfish.cn/dns-query
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  fallback:
    - https://doh.opendns.com/dns-query#Proxy
    - https://dns.adguard.com/dns-query#Proxy
    - https://doh.dns.sb/dns-query#Proxy
    - https://dns64.dns.google/dns-query#Proxy
    - https://dns.google/dns-query#Proxy

  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
      - GFW

**Comment by MetaCubeX** [comment]
@La-Hire 试试alpha,每次commit都会自动编译到pre release

**Comment by La-Hire** [comment]
排查了一下，在
611ce5f5f1a978be168a6abe2f08aca45f3f1874
到
4502776513bf45c5daf0d2158c84384626da29f1
之间产生的问题，就是我能用的alpha版本后就不行了。
此外为啥4502776那几个不认rule-set
time="2022-04-04T11:12:49+08:00" level=fatal msg="Parse config error: rules[1] [RULE-SET,kc,KC] error: unsupported rule type RULE-SET"

此外，不在fallback里使用#Proxy就无问题，因为611ce5f版本没问题这组写的肯定没问题，是不是之后这段运行逻辑又改动导致没解析出节点就用Proxy组去查了？

**Comment by La-Hire** [comment]
问题越来越奇怪了，我安卓上用611ce5f也出一样问题了，先close观察一阵子了
