### ISSUE TITLE
armv7-v1.13.1和v1.13.2内核会导致Apple TV上无法播放Youtube视频，但armv7-v1.10可以

### ISSUE THREAD

**Issue by dinnermanac** [MetaCubeX/Clash.Meta#297]
大神你好。

我是N1盒子作为旁路由使用。

我发现当N1上的OpenClash使用Clash.Meta-armv7-**v1.10**内核，手机/电脑/Apple TV通过旁路由访问所有外国网站一切正常。

当OpenClash的内核改为armv7-**v1.13.1**或者**v13.2**时，手机/电脑一切正常，但Apple TV上的Youtube会无法播放视频。Apple TV上Youtube可以正常加载视频Thumbnail，动态Thumbnai也能播放，但点击播放视频会进入无限loading的黑屏状态。

我又在MacOS上CFW**v0.20.10**尝试了Clash.Meta-darwin-arm64-**v1.13.2**，一切正常。结论似乎是Clash.Meta-armv7的**v1.13**版本有问题。不确定其他设备版本的**v1.13**是否存在同样问题。

望改进，谢谢！

**Comment by keep1earning** [comment]
如果可以的话，我们希望您提供一下日志和配置文件
