### ISSUE TITLE
update verson number when updating

### ISSUE THREAD

**Issue by lankylonky22** [MetaCubeX/Clash.Meta#299]
https://github.com/MetaCubeX/Clash.Meta/blob/667f42dcdcaacfef0c6cd84d38267d5971315f0d/constant/version.go#L5

**Comment by wwqgtxx** [comment]
https://github.com/MetaCubeX/Clash.Meta/blob/667f42dcdcaacfef0c6cd84d38267d5971315f0d/Makefile#L15-L17
