### ISSUE TITLE
疑问：我想咨询一下 Loyalsoldier/v2ray-rules-dat的geosite:category-games@cn对应的是clash里的格式是什么？

### ISSUE THREAD

**Issue by 330377782** [MetaCubeX/Clash.Meta#30]
我想咨询一下 Loyalsoldier/v2ray-rules-dat的geosite:category-games@cn对应的是clash里的格式是什么？
PS：本人小白，不喜勿碰

**Comment by eastmalon** [comment]
rules:
***
    - GEOSITE,category-games@cn,DIRECT
***

**Comment by 330377782** [comment]
谢谢

**Comment by 330377782** [comment]
你好，请问可以在自定义规则中加入GEOSITE的选择吗？
