### ISSUE TITLE
[Sniffer] Skip sniffing[149.154.167.92:80] due to multiple failures"

### ISSUE THREAD

**Issue by hadifarnoud** [MetaCubeX/Clash.Meta#306]
I have a strange issue. my internet connection dies for a few seconds every few minutes.

I looked at clash log and the only strange thing I found was this error `[Sniffer] Skip sniffing[149.154.167.92:80] due to multiple failures`

does anyone know what this means? what failure and how can I fix it?

**Comment by Skyxim** [comment]
It's just a hint. For traffic that cannot be sniffed, a whitelist will be added after many failures, and there will be no further sniffing.
