### ISSUE TITLE
规则匹配有问题，同样的规则有的走了规则，有的走了兜底规则

### ISSUE THREAD

**Issue by ycg31** [MetaCubeX/Clash.Meta#309]
Alpha最新版  开启tun

连接日志中有部分googlevideo.com走了最后的兜底规则，连接信息如下：
rr2---sn-i3belnl7.googlevideo.com:443  Google / HK / 🇭🇰 香港IEPL-10 HK-1x  RuleSet (Google)   74.125.101.167   Tun(tcp)
rr5---sn-i3belnll.googlevideo.com:443    Match / DIRECT    Match   74.125.164.234    Tun(udp)

**Comment by Skyxim** [comment]
@ycg31 正常情况，查看节点/策略组是否支持 UDP 具体可看 clash wiki
