### ISSUE TITLE
Clash meta for windows

### ISSUE THREAD

**Issue by hiddify** [MetaCubeX/Clash.Meta#316]
Is there any clash Meta for windows that have similar ui to clash for windows?

**Comment by Kingsmanvn-Official** [comment]
@hiddify clash verge

**Comment by hiddify** [comment]
Thanks
It would be nice if you mention it in the readme file

**Comment by hiddify** [comment]
https://github.com/MetaCubeX/Clash.Meta/pull/318

**Comment by Kingsmanvn-Official** [comment]
> Thanks It would be nice if you mention it in the readme file

https://docs.metacubex.one/used
