### ISSUE TITLE
PROCESS-NAME规则导致路由上的clash代理缓慢

### ISSUE THREAD

**Issue by chain710** [MetaCubeX/Clash.Meta#322]
1. 代理缓慢是指浏览器打开网页体感非常慢，大约~3s
2. 我理解PROCESS-NAME规则似乎不应该出现在路由上的clash规则中，但是规则是从某些网站自动聚合而来，暂未过滤PROCESS-NAME规则
3. 我从原版clash迁移到clash-meta，原版clash使用相同规则，并未出现代理缓慢的问题

debug后发现区别如下

```
if !processFound && (alwaysFindProcess || rule.ShouldFindProcess()) {
	srcPort, err := strconv.ParseUint(metadata.SrcPort, 10, 16)
	uid, path, err := P.FindProcessName(metadata.NetWork.String(), metadata.SrcIP, int(srcPort))
	if err != nil {
		log.Debugln("[Process] find process %s: %v", metadata.String(), err)
	} else {
		metadata.Process = filepath.Base(path)
		metadata.ProcessPath = path
		metadata.Uid = uid
		processFound = true
	}
}
```

原版中无论FindProcessName成功失败，都直接设置为processFound = true，而meta版要求FindProcessName必须成功
因此meta中调用多次FindProcessName，而路由上应该是无法正确查到processName的，导致`代理缓慢`

我猜原版和meta版的处理各有理由，也明白删除PROCESS-NAME规则似乎也可以解决此问题
但是我建议能否将处理权交给用户：
引入process-name-mode选项，value为strict | relax | disable
默认strict，保持当前行为
relax可仿照clash，只尝试一次
disable则彻底不查询processName

**Comment by a904055262** [comment]
我也有process规则，没发现网页缓慢啊。。

**Comment by Skyxim** [comment]
alwaysFindProcess 这个配置仅仅是为了保留一直强制获取进程名而存在，的确无法禁止。如果多次找不到的确可能比较耗时，具体多少我不清楚。不过路由器上的确别有进程规则最好

**Comment by chain710** [comment]
> alwaysFindProcess 这个配置仅仅是为了保留一直强制获取进程名而存在，的确无法禁止。如果多次找不到的确可能比较耗时，具体多少我不清楚。不过路由器上的确别有进程规则最好 至于查询的性能（内存/CPU）消耗，不确定进程搜索代码是否有问题和存在优化空间，我也不用进程规则没有深究

1. 我这里配置中enable-process: false, alwaysFindProcess变量亦为false
2. 根据我在自己的x86路由上观察，多次findProcess失败，会导致1) 大量的clash线程处于D状态 2) pprof看到部分堆栈停留在findProcess中，注释掉findProcess调用后一切正常

**Comment by skill7899** [comment]
我也发现这个问题了。。只要有ROCESS-NAME的规则，就好慢。。删除掉就没有问题
