### ISSUE TITLE
http outbound代理HTTP链接不应使用CONNECT方法

### ISSUE THREAD

**Issue by zvzl** [MetaCubeX/Clash.Meta#328]
一般在代理HTTPS时使用connect方法，若代理HTTP时使用connect方法会造成兼容性问题，比如tinyproxy按照一般设置会出现报错
![image](https://user-images.githubusercontent.com/84430227/211319945-1b59c431-2f46-4da8-8ddc-b3a3521f6424.png)

当http代理上游为elecv2p时，也会出现兼容性问题https://github.com/elecV2/elecV2P/issues/180

希望可以为代理HTTP时是否使用CONNECT方法增添一个选项

**Comment by Skyxim** [comment]
@zvzl 作为代理服务器 需要代理TCP，并且你并不知道 被代理的流量属于 HTTP 的 GET POST HEAD 你就算能自定义也是无意义的

**Comment by Skyxim** [comment]
@Skyxim clash 不是一个纯粹的 HTTP 代理转发服务器

**Comment by Skyxim** [comment]
如果 PR 一个 HTTP 处理引擎，提取 HTTP 流量中信息，进行对 HTTP 代理还原，倒是可解决

**Comment by zvzl** [comment]
可以，我边学边做，可能需要比较久

**Comment by Skyxim** [comment]
> 可以，我边学边做，可能需要比较久

不过就算能还原部分，但是原始 TCP 流量仍然会以 connect 方式连接，从而断开，导致无法连接，需要解决的东西不少
