### ISSUE TITLE
How To Convert Script Clash To Meta

### ISSUE THREAD

**Issue by rizkisquadpants** [MetaCubeX/Clash.Meta#335]
Example :
script:
  shortcuts:
    UDP-Game: network == 'udp' and dst_port not in [21,22,23,53,80,123,143,194,443,465,587,853,993,995,998,2052,2053,2082,2083,2086,2095,2096,5222,5228,5229,5230,8080,8443,8880,8883,8888,8889]

**Comment by cubemaze** [comment]
@rizkisquadpants - AND,(NOT,((DST-PORT,21/22/23/53/80/123/143/194/443/465/587/853/993/995/998/2052/2053/2082/2083/2086/2095/2096/5222/5228/5229/5230/8080/8443/8880/8883/8888/8889)),(NETWORK,UDP)),PROXY

**Comment by rizkisquadpants** [comment]
@cubemaze Thanks You
