### ISSUE TITLE
initial proxy provider xxx error: proxy 6 error: cannot parse 'port' as int: strconv.ParseInt: parsing \"\": invalid syntax

### ISSUE THREAD

**Issue by ag2s20150909** [MetaCubeX/Clash.Meta#345]
initial proxy provider xxx error: proxy 6 error: cannot parse 'port' as int: strconv.ParseInt: parsing \"\": invalid syntax

**Comment by Skyxim** [comment]
字面意思，不能是字符串，只能是数字
