### ISSUE TITLE
hysteria 协议的配置问题

### ISSUE THREAD

**Issue by wang20150419** [MetaCubeX/Clash.Meta#348]
在 hysteria 的原生配置里：
     "server_name": "www.${domain}.com",
     "ca": "${path}/hysteria.ca.crt"
其中，server_name 在 clash.meta 里没有对应的选项。猜测是 sni ?
ca 选项的 hysteria.ca.crt 文件放SD卡上，位置为：/storage/emulated/0/hysteria.ca.crt
已给clash.meta设置存储访问权限，但读取配置文件时，依然报错： Permission denied

**Comment by H1JK** [comment]
> server_name 在 clash.meta 里没有对应的选项。猜测是 sni ?

Yes.

> 已给clash.meta设置存储访问权限，但读取配置文件时，依然报错： Permission denied
Need further information. Looks like you are using Clash.Meta on Android. Are you using Clash.Meta binary on Termux (with or without root permission?)? Or just using ClashMetaForAndroid application.

**Comment by Skyxim** [comment]
安卓问题不太清楚，不过你可以使用指纹来进行校验证书
https://github.com/MetaCubeX/Clash.Meta/blob/3bace079488070a1fa5454d2f3b9aadd310101f4/docs/config.yaml#L258
针对 TLS 相关的协议皆可使用

**Comment by wang20150419** [comment]
> > server_name 在 clash.meta 里没有对应的选项。猜测是 sni ?
> 
> Yes.
> 
> > 已给clash.meta设置存储访问权限，但读取配置文件时，依然报错： Permission denied
> 
> Need further information. Looks like you are using Clash.Meta on Android. Are you using Clash.Meta binary on Termux (with or without root permission?)? Or just using ClashMetaForAndroid application. Which Android version are you using?

Termux 下可以查看SDCARD里的证书文件。android version = 12
能用 custom-certificates:  解决也行。
