### ISSUE TITLE
alpha内核不开ipv6代理的开关的话，即使允许IPV6DNS解析，也一并干掉AAAA记录了？？

### ISSUE THREAD

**Issue by a904055262** [MetaCubeX/Clash.Meta#351]
那我这种只是FALLBACK组挂了个上游不要IPV6的怎么办？？我国内IPV6不走核心，直接直连不行么？

**Comment by a904055262** [comment]
幸好备份了旧版本。。

**Comment by OiCkilL** [comment]
貌似从 https://github.com/MetaCubeX/Clash.Meta/commit/3bace079488070a1fa5454d2f3b9aadd310101f4 这个 commit 开始就这样了，对于需要 IPv6 DNS 解析并且不需要 IPv6代理的情况下AAAA记录全被干掉了，这个改动的逻辑很有问题

**Comment by Skyxim** [comment]
@OiCkilL 那你就 开着

**Comment by OiCkilL** [comment]
> 

开着没用，节点不支持IPv6，最终还是只有IPv4地址

**Comment by handsomexdd1024** [comment]
我这里观察到的现象是：向clash-meta的dns服务器请求ipv6单栈站点的AAAA记录时，返回的记录正确无误；请求双栈站点时只有A记录能正常解析，AAAA记录会返回SOA。
