### ISSUE TITLE
请问下fallback-filter设置geosite后，geosite的网站会向nameserve服务器发送dns请求吗？

### ISSUE THREAD

**Issue by EsuRt** [MetaCubeX/Clash.Meta#353]
请问下fallback-filter设置geosite后，geosite的网站会向nameserve服务器发送dns请求吗？

**Comment by a904055262** [comment]
应该不会吧，不然逻辑何在

**Comment by EsuRt** [comment]
> 应该不会吧，不然逻辑何在

原版clash在设置fallback-filter的geoip时，会同时向nameserve和fallback的dns发送请求，geosite是meta专属的，所以不清楚是否也会同时发送。

**Comment by Rashhz** [comment]
redir host会 fakeip 不会，感觉应该是个bug

**Comment by EsuRt** [comment]
> redir host会 fakeip 不会，感觉应该是个bug
那这样应该会有dns泄露的风险，如果设置了geosite的网站走代理，直接用fallback的dns即可，无须再向nameserver的服务器请求，geoip发送二次请求倒能理解。

**Comment by Skyxim** [comment]
使用 nameserver-policy 分流 DNS

**Comment by EsuRt** [comment]
> 使用 nameserver-policy 分流 DNS

看了下Wiki，nameserver-policy在域名不多的情况下可解决问题，不知能否加入geosite规则？一般情况下，国外域名我都走国外的DNS。

**Comment by EsuRt** [comment]
> > > 使用 nameserver-policy 分流 DNS
> > 
> > 
> > 看了下Wiki，nameserver-policy在域名不多的情况下可解决问题，不知能否加入geosite规则？一般情况下，国外域名我都走国外的DNS。
> 
> 最新的alpha支持ns-policy写法。
> 
> nameserver-policy: 'geosite:cn': '223.5.5.5'

多谢大佬，等正式版试试。
