### ISSUE TITLE
[BUG]clashx.meta客户端内存占用异常

### ISSUE THREAD

**Issue by skill7899** [MetaCubeX/Clash.Meta#357]
<img width="938" alt="image" src="https://user-images.githubusercontent.com/13962272/215314899-95bca50e-bba7-4925-b03a-37b9ed481597.png">
已经在使用alpha最新版本，之前的版本一样会，一度占用达到1.5G。MAC M1

**Comment by Skyxim** [comment]
@Larvan2 访问下 http://127.0.0.1:xxxx/debug/pprof/heap 这个地址，将下载文件传上来下

**Comment by Skyxim** [comment]
@Skyxim xxx 为 controller 的端口

**Comment by skill7899** [comment]
> @Skyxim xxx 为 controller 的端口

<img width="600" alt="image" src="https://user-images.githubusercontent.com/13962272/215372675-2765de6c-b819-4608-928c-27980bc1e329.png">

404

**Comment by skill7899** [comment]
<img width="271" alt="image" src="https://user-images.githubusercontent.com/13962272/215372830-f3e64545-5df4-47de-b8fc-6b8d9be02934.png">
现在开机一晚，也是占用到500M了
<img width="162" alt="image" src="https://user-images.githubusercontent.com/13962272/215372877-3e258531-97ff-4640-8f5b-51a0c29b2a5b.png">

**Comment by skill7899** [comment]
基本已经确认是stack的问题，用gvisor就会内存泄漏，用system没有问题。
@Larvan2 @Skyxim 
tun:
  enable: true
  # device: meta
  stack: system #gvisor

**Comment by skill7899** [comment]
猜错了，换成system依然达到了400多MB，一晚过去了。
<img width="269" alt="image" src="https://user-images.githubusercontent.com/13962272/215633935-75024de0-d53a-43d4-9060-91f162216e71.png">

**Comment by skill7899** [comment]
把hysteria的多端口改回单端口，内存占用就没有问题了。另外alpha版本，的确没有debug的服务，我自已编译也不会放到clashxMeta客户端里面。
@Larvan2 @Skyxim

**Comment by skill7899** [comment]
https://github.com/apernet/hysteria/issues/556 
hysteria的多端口，我测试了原版也有这个问题，不过提交给作者已经修复了，希望这边也同步一下代码，修复一下
