### ISSUE TITLE
[Bug]无法运行vless-ws模式，核心会崩溃

### ISSUE THREAD

**Issue by ximiTech** [MetaCubeX/Clash.Meta#358]
按照此模板填入配置：
  - name: "vless-ws"
    type: vless
    server: server
    port: 443
    uuid: uuid
    udp: false
    tls: true
    network: ws
    servername: example.com # priority over wss host
    skip-cert-verify: false
    fingerprint: xxxx
    ws-opts:
      path: "/"
      headers:
        Host: example.com

Meta Core启动后会崩溃，日志如下：
	github.com/Dreamacro/clash/tunnel/tunnel.go:178 +0x71
created by github.com/Dreamacro/clash/tunnel.process
	github.com/Dreamacro/clash/tunnel/tunnel.go:390 +0x4f1
github.com/Dreamacro/clash/tunnel.handleTCPConn({0x1321440, 0xc0006072f0})
	github.com/Dreamacro/clash/tunnel/tunnel.go:533 +0xd1
github.com/Dreamacro/clash/tunnel.retry[...]({0x1324ac8?, 0xc000281980}, 0xc000293ed8, 0xc000293f28)
	github.com/Dreamacro/clash/tunnel/tunnel.go:391 +0x42
github.com/Dreamacro/clash/tunnel.handleTCPConn.func2({0x1324ac8?, 0xc000281980?})
	github.com/Dreamacro/clash/adapter/adapter.go:41 +0x30
github.com/Dreamacro/clash/adapter.(*Proxy).DialContext(0x0?, {0x1324ac8?, 0xc000281980?}, 0x40d907?, {0x0?, 0x1094c20?, 0x1324a01?})
	github.com/Dreamacro/clash/adapter/outboundgroup/selector.go:22 +0xb7
github.com/Dreamacro/clash/adapter/outboundgroup.(*Selector).DialContext(0xc0005326e0, {0x1324ac8, 0xc000281980}, 0x7f819762e7b8?, {0x0, 0x0, 0x0})
	github.com/Dreamacro/clash/adapter/adapter.go:41 +0x30
github.com/Dreamacro/clash/adapter.(*Proxy).DialContext(0xc000266600?, {0x1324ac8?, 0xc000281980?}, 0x7f81bed355b8?, {0x0?, 0xc000068800?, 0xc0009aa780?})
	github.com/Dreamacro/clash/adapter/outbound/vless.go:221 +0x351
github.com/Dreamacro/clash/adapter/outbound.(*Vless).DialContext(0xc00084d5f0, {0x1324ac8, 0xc000281980}, 0x2?, {0x0?, 0xc0001197c0?, 0xc0001197e0?})
	github.com/Dreamacro/clash/adapter/outbound/vless.go:235 +0x228
github.com/Dreamacro/clash/adapter/outbound.(*Vless).DialContextWithDialer(0xc00084d5f0, {0x1324ac8?, 0xc000281980?}, {0x131f3c8?, 0xc0001fe300?}, 0xc00004cc00?)
	github.com/Dreamacro/clash/adapter/outbound/vless.go:107 +0x729
github.com/Dreamacro/clash/adapter/outbound.(*Vless).StreamConn(0xc00084d5f0, {0x13310d0, 0xc0017a0300}, 0x113e0fb?)
goroutine 234 [running]:
[signal SIGSEGV: segmentation violation code=0x1 addr=0x88 pc=0xc84f29]
panic: runtime error: invalid memory address or nil pointer dereference

**Comment by tgNotHouse** [comment]
应该是第103行的err没有处理，这里tlsconfig获取为nil了。
![image](https://user-images.githubusercontent.com/19563977/215690934-86275f21-4d0c-4ae8-8974-86423f956efe.png)

@Skyxim

**Comment by tgNotHouse** [comment]
fingerprint: xxxx 

你看你下是不是你这行填错了，这应该是个sha256的指纹。 你方便把fingerprint发一下吗。

**Comment by Skyxim** [comment]
> 应该是第103行的err没有处理，这里tlsconfig获取为nil了。 ![image](https://user-images.githubusercontent.com/19563977/215690934-86275f21-4d0c-4ae8-8974-86423f956efe.png)
> 
> 另外这里应该是sha256吧 ![image](https://user-images.githubusercontent.com/19563977/215691592-bb0b1038-496d-4485-bbfd-d5436d0bcf45.png)
> 
> @Skyxim

对，写掉了

**Comment by ximiTech** [comment]
大佬再看看？vless-ws好像还是不行？

**Comment by tgNotHouse** [comment]
你编译了最新版的alpha吗？

**Comment by tgNotHouse** [comment]
这个问题目前判断是你的证书指纹问题，现在解决的是不让clash崩溃，而是返回错了。所以需要你发一下指纹

**Comment by ximiTech** [comment]
证书问题？不改证书换成trojan-ws就能通啊。。。

**Comment by Skyxim** [comment]
@ximiTech 删除服务器域名，发出你 vless-ws 的配置文件

**Comment by ximiTech** [comment]
- {name: xxx, server: x.x.x.x, port: 8443, type: vless, uuid: xxxxx, udp: true, tls: true, network: ws, servername: xxx, skip-cert-verify: false, fingerprint: chrome, ws-opts: {path: "/", headers: {Host: xxx}}}

**Comment by Skyxim** [comment]
@ximiTech 删除 指纹配置

**Comment by ximiTech** [comment]
https://github.com/MetaCubeX/Clash.Meta/blob/Alpha/docs/config.yaml#L497
