### ISSUE TITLE
开启sniffer会连不上ssh

### ISSUE THREAD

**Issue by nameless3721** [MetaCubeX/Clash.Meta#36]
最新内核arm64 alpha 815a060 开启sniff后会连不上xshell和MobaXterm enable: false 后则正常 ssh服务器直接用ip(试了下用域名也是连接失败和提示嗅探失败) 开启sniff的时候会有个警告提示嗅探失败其他纯ip例如tg也有这样的提示(题外enable: false ssh正常连接)force 参数开关也是连不上  1.10不用clash dns服务很多ip和一些域名   alpha 815a060  基本都是域名可以抛弃clash内置dns的水平 就是连ssh失败目前感受

**Comment by Skyxim** [comment]
应该不是sniffer导致的，sniffer嗅探失败不会影响流量正常发出
我也尝试通过域名和IP两种方法ssh 可以正常链接
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/70276018/162595304-13786ffd-8863-45e6-ab23-b93c1c03fe9e.png">
有根据信息么

**Comment by nameless3721** [comment]
那可能要换成xshell和MobaXterm才能复现了 连接的时候不会打印到日志 要关闭才有日志 试了下putty倒是正常... 可能看软件的
![image](https://user-images.githubusercontent.com/50364156/162603042-5372c6a7-1727-48cb-8a19-933c0c8cfd11.png)

**Comment by nameless3721** [comment]
新发现 虽然应该不是嗅探失败导致 但应该是嗅探了某些ssh软件发出的某些参数卡住导致吧,使用xshell 或者MobaXterm  给ssh设置了clash的socks5代理如果用ip也会复现日志卡住不打印的问题关闭连接ssh后才打印 但是用域名的话会直接打印连接域名的日志也正常使用  putty是正常

**Comment by Skyxim** [comment]
> 那可能要换成xshell和MobaXterm才能复现了 连接的时候clash控制台不会打印到日志 要关闭才有ssh的ip日志 试了下putty倒是正常... 可能看软件的
> ![image](https://user-images.githubusercontent.com/50364156/162603042-5372c6a7-1727-48cb-8a19-933c0c8cfd11.png)
> 就一直卡在这里

100%复现么  我搞个试试  我大概猜了个问题 验证下

**Comment by nameless3721** [comment]
> 

我这里是100%吧 又试了下 83e0aba 一样卡住 主动断开才打印连接ssh ip的日志

**Comment by nameless3721** [comment]
sniffer:
  enable: false
  force: true
  sniffing:
    - tls

https://user-images.githubusercontent.com/50364156/162901569-e8fa7c3f-0429-4a5a-ad02-49f62caf3feb.mp4

就正常了

**Comment by woaihsw** [comment]
我也遇到了同样的问题...

openclash v0.45.06-beta, 内核alpha-g58cd8f9

用putty的话可以正常连接, 而且log和连接是同步的, 尝试连接的时候就有log打出来, 具体如下

```
22-04-19 22:50:33
info
[TCP] 10.0.0.111:10375 --> 82.156.xxx.xxx:xxxxx match RuleSet(ChinaIP) using DIRECT
22-04-19 22:50:33
debug
[Sniffer] All sniffing sniff failed with from [10.0.0.111:10375] to [82.156.xxx.xxx:xxxxx]
22-04-19 22:50:33
debug
[Sniffer] [tls] Sniff data failed 82.156.xxx.xxx
```

用xshell的话, 连接的时候是没有log的, 但是连接也不会成功, 只有手动断开后才会有log出现, 如下

```
22-04-19 22:51:30
info
[TCP] 10.0.0.111:10400 --> 82.156.xxx.xxx:xxxxx match RuleSet(ChinaIP) using DIRECT
22-04-19 22:51:30
debug
[Sniffer] All sniffing sniff failed with from [10.0.0.111:10400] to [82.156.xxx.xxx:xxxxx]
```

**Comment by nameless3721** [comment]
> 我也遇到了同样的问题...
> 
> openclash v0.45.06-beta, 内核alpha-g58cd8f9
> 
> 用putty的话可以正常连接, 而且log和连接是同步的, 尝试连接的时候就有log打出来, 具体如下
> 
> ```
> 22-04-19 22:50:33
> info
> [TCP] 10.0.0.111:10375 --> 82.156.xxx.xxx:xxxxx match RuleSet(ChinaIP) using DIRECT
> 22-04-19 22:50:33
> debug
> [Sniffer] All sniffing sniff failed with from [10.0.0.111:10375] to [82.156.xxx.xxx:xxxxx]
> 22-04-19 22:50:33
> debug
> [Sniffer] [tls] Sniff data failed 82.156.xxx.xxx
> ```
> 
> 用xshell的话, 连接的时候是没有log的, 但是连接也不会成功, 只有手动断开后才会有log出现, 如下
> 
> ```
> 22-04-19 22:51:30
> info
> [TCP] 10.0.0.111:10400 --> 82.156.xxx.xxx:xxxxx match RuleSet(ChinaIP) using DIRECT
> 22-04-19 22:51:30
> debug
> [Sniffer] All sniffing sniff failed with from [10.0.0.111:10400] to [82.156.xxx.xxx:xxxxx]
> ```

目前只能说加个域名吧 域名出来不触发嗅探就能连 ip会触发嗅探然后卡log

**Comment by Skyxim** [comment]
实在没法复现 搞了个xshell7 也可以正常连接 通过socks5代理
![image](https://user-images.githubusercontent.com/70276018/164126112-8432679c-505c-4c7c-b06a-53e020e8a167.png)

**Comment by Skyxim** [comment]
> > 我也遇到了同样的问题...
> > openclash v0.45.06-beta, 内核alpha-g58cd8f9
> > 用putty的话可以正常连接, 而且log和连接是同步的, 尝试连接的时候就有log打出来, 具体如下
> > ```
> > 22-04-19 22:50:33
> > info
> > [TCP] 10.0.0.111:10375 --> 82.156.xxx.xxx:xxxxx match RuleSet(ChinaIP) using DIRECT
> > 22-04-19 22:50:33
> > debug
> > [Sniffer] All sniffing sniff failed with from [10.0.0.111:10375] to [82.156.xxx.xxx:xxxxx]
> > 22-04-19 22:50:33
> > debug
> > [Sniffer] [tls] Sniff data failed 82.156.xxx.xxx
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 用xshell的话, 连接的时候是没有log的, 但是连接也不会成功, 只有手动断开后才会有log出现, 如下
> > ```
> > 22-04-19 22:51:30
> > info
> > [TCP] 10.0.0.111:10400 --> 82.156.xxx.xxx:xxxxx match RuleSet(ChinaIP) using DIRECT
> > 22-04-19 22:51:30
> > debug
> > [Sniffer] All sniffing sniff failed with from [10.0.0.111:10400] to [82.156.xxx.xxx:xxxxx]
> > ```
> 
> 目前只能说加个域名吧 域名出来不触发嗅探就能连 ip会触发嗅探然后卡log

嗅探失败不会影响正常请求

**Comment by xianren78** [comment]
开始sniffer还会造成ikev2 VPN服务器无法连接。N1 openwrt，openclash混合模式，同时启动ikev2 VPN 服务端。在不启用sniffer模式的时候，客户端可以顺利拨号，开启则无法拨号。

**Comment by nameless3721** [comment]
> 实在没法复现 搞了个xshell7 也可以正常连接 通过socks5代理 ![image](https://user-images.githubusercontent.com/70276018/164126233-a9ab5b57-1757-40b9-8729-08f994b51783.png)
> 
> 由于无法复现暂时关闭

发现控制台才看到debug信息 cfw里面看不了.. sniff应该是不影响正常连接的 目前应该是卡log不发起连接的问题吧? 复现不了可能系统关系?
![image](https://user-images.githubusercontent.com/50364156/164157526-20a5835b-7269-4c1e-9366-41eb4fdec379.png)
可能也和Process有冲突吗 开嗅探后先出Process然后卡Sniffer 和info信息了 
关闭sniff后几乎能同时出 
![image](https://user-images.githubusercontent.com/50364156/164158030-15e69ebd-6a9b-4f44-88a5-b0801e34d341.png)

**Comment by xianren78** [comment]
可能和这个相关 https://github.com/XTLS/Xray-core/issues/127

**Comment by Skyxim** [comment]
@xianren78 不同一个原因，原因已经确定了 解决有点麻烦

**Comment by Skyxim** [comment]
添加了个port-whitelist 参数 用于添加白名单端口，为空时匹配全端口
~~~
sniffer:
  port-whitelist:
    - 443
    - 8080-9090
 ~~~
