### ISSUE TITLE
LB的round-robin策略异常

### ISSUE THREAD

**Issue by ovear** [MetaCubeX/Clash.Meta#362]
如果LB中存活的Proxies为偶数，那么有部分节点会被跳过，可能永远不会被选中。

出现这种情况的原因是因为`lb`的`adapter.Unwarp()`在一次链接中被调用了两次，从而导致`lb`的`strategyRoundRobin()`被调用多次。

而`strategyRoundRobin()`的逻辑非常简单，调用一次就往后找一个节点，那么第一次调用的节点会一直无法使用。

`strategyRoundRobin()`的代码

https://github.com/MetaCubeX/Clash.Meta/blob/53b41ca166717d81398b97224777d1045935374a/adapter/outboundgroup/loadbalance.go#L117-L131

第一次调用是在`resolve metadata`时：
https://github.com/MetaCubeX/Clash.Meta/blob/53b41ca166717d81398b97224777d1045935374a/tunnel/tunnel.go#L492-L497

第二次调用是在`DialContext`实际发出链接时：
https://github.com/MetaCubeX/Clash.Meta/blob/53b41ca166717d81398b97224777d1045935374a/adapter/outboundgroup/loadbalance.go#L84-L98

可能的解决方案：

- 在`strategyRoundRobin`处通过传入的`metadata`检查是否重复调用；
- 修改`adapter.Unwarp()`接口，增加一个`dry run`的`bool`；
- 修改`resolve metadata`时调用的逻辑，比如跳过`lb`；

**Comment by ovear** [comment]
或者对于LB来说，找个地方记录一下本次链接的`proxy`也行，比如说往`context`里面放；刚好又实现了幂等。

**Comment by ovear** [comment]
想了一下，按照`PASS`设计的初衷，应该没有什么场景在`LB`中使用`PASS`；可以考虑在检查`PASS`时，直接跳过`LB`

这样应该能在不增加复杂度的情况下修复，也比较符合直觉。

**Comment by Skyxim** [comment]
我觉得直接简单粗暴的禁止非可选加入 pass

**Comment by Skyxim** [comment]
@Skyxim 哦 不大行 因为有嵌套 还是会被其他策略组引入

**Comment by ovear** [comment]
洗澡的时候突发奇想，感觉可以作为临时解决方案。

**Comment by ovear** [comment]
Close since #390 Merged
