### ISSUE TITLE
EBPF 无法使用

### ISSUE THREAD

**Issue by xmapst** [MetaCubeX/Clash.Meta#364]
failed to create bpf fs subpath: mkdir /sys/fs/bpf/clash: no such file or directory

**Comment by oluceps** [comment]
确认一下 `/sys/fs/bpf` 目录存在？
看看这个输出
```console
bpftool feature probe | grep program_type
```

**Comment by xmapst** [comment]
> 
```txt
root@test ~ 14:47:49 # ls -l /sys/fs/bpf/
total 0
root@test ~ 14:47:57 # bpftool feature probe | grep program_type
Usage: bpftool [OPTIONS] OBJECT { COMMAND | help }
       bpftool batch file FILE
       bpftool version

       OBJECT := { prog | map | cgroup }
       OPTIONS := { {-j|--json} [{-p|--pretty}] | {-f|--bpffs} }
```

**Comment by oluceps** [comment]
> 

这输出不太对啊
```console
$ cat /proc/version
$ bpftool version
```
看看输出

**Comment by xmapst** [comment]
> > 
> 
> 这输出不太对啊
> 
> ```
> $ cat /proc/version
> $ bpftool version
> ```
> 
> 看看输出

```
root@test ~ 15:26:09 #  cat /proc/version
Linux version 5.17.6-1.el7.elrepo.x86_64 (mockbuild@Build64R7) (gcc (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2), GNU ld version 2.32-16.el7) #1 SMP PREEMPT Fri May 6 09:08:57 EDT 2022
root@test ~ 15:26:13 # bpftool version
bpftool v3.10.0-1160.83.1.el7.x86_64.debug
```

**Comment by oluceps** [comment]
> > > 
> > 
> > 
> > 这输出不太对啊
> > ```
> > $ cat /proc/version
> > $ bpftool version
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 看看输出
> 
> ```
> root@test ~ 15:26:09 #  cat /proc/version
> Linux version 5.17.6-1.el7.elrepo.x86_64 (mockbuild@Build64R7) (gcc (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2), GNU ld version 2.32-16.el7) #1 SMP PREEMPT Fri May 6 09:08:57 EDT 2022
> root@test ~ 15:26:13 # bpftool version
> bpftool v3.10.0-1160.83.1.el7.x86_64.debug
> ```

大概率是内核不支持eBPF
另外你这bpftool太老了

**Comment by xmapst** [comment]
> > > > 
> > > 
> > > 
> > > 这输出不太对啊
> > > ```
> > > $ cat /proc/version
> > > $ bpftool version
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 看看输出
> > 
> > 
> > ```
> > root@test ~ 15:26:09 #  cat /proc/version
> > Linux version 5.17.6-1.el7.elrepo.x86_64 (mockbuild@Build64R7) (gcc (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2), GNU ld version 2.32-16.el7) #1 SMP PREEMPT Fri May 6 09:08:57 EDT 2022
> > root@test ~ 15:26:13 # bpftool version
> > bpftool v3.10.0-1160.83.1.el7.x86_64.debug
> > ```
> 
> 大概率是内核不支持eBPF 另外你这bpftool太老了

但是用 `Dreamacro` 的 `Clash` `Premium` 没问题

**Comment by yswtrue** [comment]
一样，配置了ebpf之后会报这个错误
```
Attached tc ebpf program error: failed to create bpf fs subpath: mkdir /sys/fs/bpf/clash: permission denied
```
`clash-premium`是可以的
都是加了这些权限的
```
/usr/bin/setcap 'CAP_PERFMON,cap_bpf,cap_sys_admin,cap_net_admin,cap_net_bind_service=ep' /usr/bin/clash-meta
```

**Comment by yswtrue** [comment]
> 确认一下 `/sys/fs/bpf` 目录存在？ 看看这个输出
> 
> ```
> bpftool feature probe | grep program_type
> ```

```
╰─ sudo bpftool feature probe | grep program_type                                                                                                                                         ─╯
请把您的右手中指放在指纹读取器上eBPF program_type socket_filter is available
eBPF program_type kprobe is available
eBPF program_type sched_cls is available
eBPF program_type sched_act is available
eBPF program_type tracepoint is available
eBPF program_type xdp is available
eBPF program_type perf_event is available
eBPF program_type cgroup_skb is available
eBPF program_type cgroup_sock is available
eBPF program_type lwt_in is available
eBPF program_type lwt_out is available
eBPF program_type lwt_xmit is available
eBPF program_type sock_ops is available
eBPF program_type sk_skb is available
eBPF program_type cgroup_device is available
eBPF program_type sk_msg is available
eBPF program_type raw_tracepoint is available
eBPF program_type cgroup_sock_addr is available
eBPF program_type lwt_seg6local is available
eBPF program_type lirc_mode2 is available
eBPF program_type sk_reuseport is available
eBPF program_type flow_dissector is available
eBPF program_type cgroup_sysctl is available
eBPF program_type raw_tracepoint_writable is available
eBPF program_type cgroup_sockopt is available
eBPF program_type tracing is available
eBPF program_type struct_ops is available
eBPF program_type ext is available
eBPF program_type lsm is available
eBPF program_type sk_lookup is available
eBPF program_type syscall is available

```

**Comment by xmapst** [comment]
> 一样，配置了ebpf之后会报这个错误
> 
> ```
> Attached tc ebpf program error: failed to create bpf fs subpath: mkdir /sys/fs/bpf/clash: permission denied
> ```
> 
> `clash-premium`是可以的 都是加了这些权限的
> 
> ```
> /usr/bin/setcap 'CAP_PERFMON,cap_bpf,cap_sys_admin,cap_net_admin,cap_net_bind_service=ep' /usr/bin/clash-meta
> ```

需要自行mount一下bpf才行, 编辑`/etc/fstab`文件, 加入以下内容
```text
bpffs                  /sys/fs/bpf             bpf     defaults 0 0
```
