### ISSUE TITLE
非Lan IP无法链接

### ISSUE THREAD

**Issue by ycmmonkey** [MetaCubeX/Clash.Meta#365]
![ddd](https://user-images.githubusercontent.com/452558/216752165-0e00b5e5-3429-41fb-a9f6-658c4e8027fe.png)
tun模式透明代理，除了本地lan ip，其他ip段（我目前是wireguard回家的ip段）无法连通，没有数据流量，且destination ip 显示为节点域名，P核是可以正常连接的

**Comment by ycmmonkey** [comment]
通过加路由解决了

**Comment by jaesony** [comment]
请问路由怎么设置的，我也遇到同样的问题

**Comment by ycmmonkey** [comment]
ip route add {wg网段} via {网关}
