### ISSUE TITLE
fake-ip-filter 能否像fallback-filter一样支持 GEOSITE databases

### ISSUE THREAD

**Issue by nick008a** [MetaCubeX/Clash.Meta#366]
``fake-ip-filter`` 能否像fallback-filter一样支持 GEOSITE databases？

希望实现 对大陆的域名不使用fake-ip，直接返回真实ip。目前的做法是需要把GEOSITE 手工一行行抄写到``fake-ip-filter`` 里，很麻烦。

使用场景（与本issue无直接关联）：
openclash等软件已经自动配置linux防火墙可以根据 chnroute 绕过大陆ip地址。如果dns能直接返回真实ip，则这些流量可以完全不经过clash.meta内核，有助于提升速度和解决部分服务器在大陆的UDP协议问题。

**Comment by Skyxim** [comment]
直接使用 redir-host

**Comment by xianren78** [comment]
dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: true
  enhanced-mode: redir-host
  default-nameserver:
    - 114.114.114.114
    - 223.5.5.5
  nameserver:
    - tls://dns.google
    - tls://1.0.0.1
  proxy-server-nameserver:
    - https://doh.pub/dns-query
  nameserver-policy:
    "geosite:cn": https://doh.pub/dns-query

**Comment by Skyxim** [comment]
@nick008a 删除所有国外 dns

**Comment by xianren78** [comment]
> @xianren78 这种配置下，浏览器发出dns请求，会先走- tls://dns.google 和 - tls://1.0.0.1，通过代理链路，解析出真实ip。但如果延迟很大，浏览器直接就报错了。要再刷新一次才能显示页面。

国内已经分流了，至于nameserver如果不稳定可以走PROXY:
- tls://dns.google#PROXY
- tls://1.0.0.1#PROXY

**Comment by xishang0128** [comment]
@nick008a fakeip需要担心污染?

**Comment by Skyxim** [comment]
@nick008a 这根本不是你所考虑的，代理软件 自己都处理了

**Comment by trawor** [comment]
翻了一下源码尝试想改改, 发现现在的处理逻辑是把filter里的域名列表插入到了`hosts`的配置里, 相当于是借助hosts的预设逻辑绕过了fake ip
到实际判断是否需要fake ip的时候这块封装的比较死, 没找到好的入手点... 比如dns上下文里没有办法读取geosite或者rule-set

也间接理解了作者不想把这个做重的原因 @cjwddtc in https://github.com/Dreamacro/clash/issues/2536#issuecomment-1460310392_

**Comment by Skyxim** [comment]
> 翻了一下源码尝试想改改, 发现现在的处理逻辑是把filter里的域名列表插入到了`hosts`的配置里, 相当于是借助hosts的预设逻辑绕过了fake ip
> 
> 到实际判断是否需要fake ip的时候这块封装的比较死, 没找到好的入手点... 比如dns上下文里没有办法读取geosite或者rule-set
> 
> 
> 
> 也间接理解了作者不想把这个做重的原因 @cjwddtc in https://github.com/Dreamacro/clash/issues/2536#issuecomment-1460310392_
> 
>             

主要是 fake-ip 设计就是为了让域名得到唯一标记方便处理分流，这么一搞，准确度没了，还不如 redir-host 灵活

**Comment by PingZi-Wing** [comment]
nameserver-policy:  可以使用 geosite 分流 DNS 解析了。
https://docs.metacubex.one/function/dns/nameserver-policy
