### ISSUE TITLE
最新的alpha 内核无法启动

### ISSUE THREAD

**Issue by eightsheep67** [MetaCubeX/Clash.Meta#372]
最新87的openclash
最新的alpha 内核

2023-02-06 10:37:33 错误：无法获取 General 部分的转发端口设置, OpenClash 使用原始配置文件启动失败 
2023-02-06 10:37:31 错误：无法获取 DNS 部分的运行模式设置, OpenClash 使用原始配置文件启动失败 
2023-02-06 10:37:29 错误：无法获取 DNS 部分的监听端口设置, OpenClash 使用原始配置文件启动失败

nohup: failed to run command ‘/etc/openclash/clash’: Exec format error

更换1.14.1恢复正常。

**Comment by Skyxim** [comment]
@eightsheep67 这是openclash 日志

**Comment by Skyxim** [comment]
@Skyxim 这个应该是内核没下完整或者压缩有问题

**Comment by eightsheep67** [comment]
要如何查看内核日志，启动失败后，我在openclash的内核日志页面也没有看到错误的信息。

**Comment by eightsheep67** [comment]
我下了下面两种

[clash.meta-linux-amd64-cgo-alpha-4c25f5e.gz](https://github.com/MetaCubeX/Clash.Meta/releases/download/Prerelease-Alpha/clash.meta-linux-amd64-cgo-alpha-4c25f5e.gz)
9.15 MB

[clash.meta-linux-amd64-compatible-alpha-4c25f5e.gz](https://github.com/MetaCubeX/Clash.Meta/releases/download/Prerelease-Alpha/clash.meta-linux-amd64-compatible-alpha-4c25f5e.gz)
9.01 MB

都同样的错误

**Comment by tgNotHouse** [comment]
nohup: failed to run command ‘/etc/openclash/clash’: Exec format error

你的cpu是amd64吗，openclash一般不是路由器上的吗？你估计下载错了，看看你cpu是什么类型的。

**Comment by eightsheep67** [comment]
> nohup: failed to run command ‘/etc/openclash/clash’: Exec format error
> 
> 你的cpu是amd64吗，openclash一般不是路由器上的吗？你估计下载错了，看看你cpu是什么类型的。

是amd64，1.14.1我也是下这个版本。

**Comment by tgNotHouse** [comment]
那你把代码拉下来自己编译吧

**Comment by eightsheep67** [comment]
新的alpha已经修复
