### ISSUE TITLE
[BUG] Sniffer 开启 override-destination 后导致 GEOSITE 规则匹配失败

### ISSUE THREAD

**Issue by Hill-98** [MetaCubeX/Clash.Meta#374]
~~现在 Meta Clash 开启 Sniffer 之后，它探测到域名后会使用内置 DNS 重新解析，但是如果在路由器上运行可能就不需要重新解析，比如我路由器的 DNS 已经完美解决了 DNS 污染以及 DNS 分流这些操作，二次解析反而会破坏一些东西。~~

~~虽然可以把 Meta Clash 的上游 DNS 设置为路由器 DNS，但这总归不是完美的解决方案，希望可以通过选项控制这个功能，方便只想使用 Sniffer 做到域名分流的用户。~~

**Comment by Skyxim** [comment]
@Hill-98 override-destination: false

**Comment by Hill-98** [comment]
原来如此，谢谢，我昨天在主分支找了半天没找到，原来还在 Alpha 分支里。

**Comment by Hill-98** [comment]
@Skyxim 我发现 `override-destination: false` 之后会导致域名嗅探失效，这是 BUG 吗？

**Comment by Hill-98** [comment]
```
23-02-07 14:31:00[ info ][TCP] 10.10.10.3:56796 --> 184.30.30.209:80 match DstPort(20/21/25/53/80/110/143/443/465/587/853/873/989/990/993/995/8080/8443) using 常用端口
23-02-07 14:31:00[ info ][Sniffer] Sniff TCP [10.10.10.3:56796]-->[184.30.30.209:80] success, replace domain []-->[www.msftconnecttest.com]
```

日志显示的是探测到了域名，但是匹配规则时没有用域名匹配，以及查看连接时也不显示域名。

**Comment by Skyxim** [comment]
@Hill-98 既然 不覆盖当然连接时不是域名了，规则匹配会使用，日志没打而已

**Comment by Hill-98** [comment]
但是当我开启 `override-destination` 后，规则匹配是正常的。

```
23-02-07 14:45:54[ info ][TCP] 10.10.10.3:52156 --> www.msftconnecttest.com:80 match GeoSite(win-extra) using Windows[DIRECT]
23-02-07 14:45:53[ info ][Sniffer] Sniff TCP [10.10.10.3:52156]-->[184.30.30.209:80] success, replace domain []-->[www.msftconnecttest.com]
```

**Comment by Hill-98** [comment]
@Skyxim 我发现开启 `override-destination` 之后会导致 GEOSITE 规则匹配异常。

测试命令：`curl -vI4 --resolve "store.steampowered.com:80:1.1.1.1" store.steampowered.com`

`GEOSITE,steam,Steam`: 开启 override-destination 时会匹配成功，关闭 override-destination 时会匹配失败，
`DOMAIN,store.steampowered.com,Steam`: 无论 override-destination 开启或关闭都会匹配成功。

规则链:
```
- GEOSITE,steam,Steam
- DOMAIN,store.steampowered.com,Steam
```

开启 override-destination:
```
02-07 15:30:42 INFO [Sniffer] Sniff TCP [198.18.0.1:61100]-->[1.1.1.1:80] success, replace domain []-->[store.steampowered.com]
02-07 15:30:42 INFO [TCP] 198.18.0.1:61100 --> store.steampowered.com:80 match GeoSite(steam) using Steam
```

关闭 override-destination:
```
02-07 15:28:37 INFO [Sniffer] Sniff TCP [198.18.0.1:61116]-->[1.1.1.1:80] success, replace domain []-->[store.steampowered.com]
02-07 15:28:37 INFO [TCP] 198.18.0.1:61116 --> 1.1.1.1:80 match Domain(store.steampowered.com) using Steam
```
