### ISSUE TITLE
支持 Clash.Meta内核的客户端有哪些

### ISSUE THREAD

**Issue by gcphym** [MetaCubeX/Clash.Meta#38]
windows有 https://github.com/2dust/clashN
安卓和mac目前没找到

**Comment by CHIZI-0618** [comment]
@gcphym 自己换核心就好

**Comment by Skyxim** [comment]
可以直接用CFW mac上

**Comment by CyEilo** [comment]
openclash支持
上个星期还在弄clash的script功能弄的一头雾水 
刚发现openwrt上openclash已经能使用meta内核了,开心

**Comment by zzz6839** [comment]
Clash for windows 文件名clash-win64.exe，把这个文件替换成Meta内核的就行

**Comment by MetaCubeX** [comment]
@zzz6839 话说，有个不起眼的，叫做clash.mini

**Comment by zzz6839** [comment]
> @zzz6839 话说，有个不起眼的，叫做clash.mini

界面可以再美化一点就好啦，yacd面板欣赏不能

**Comment by MetaCubeX** [comment]
@zzz6839 主打轻量，yacd界面都有点多余……

**Comment by fredericky123** [comment]
> @gcphym 自己换核心就好

请问如何替换clash x pro的内核为这个呢

**Comment by vj23456** [comment]
@fredericky123 clash X pro 不支持~可以用cfw

**Comment by fredericky123** [comment]
Electront下的cfw太臃肿了，很耗cpu
希望用个轻量版的

**Comment by fredericky123** [comment]
> @zzz6839 话说，有个不起眼的，叫做clash.mini

这个mini似乎只支持win?
尚未更新到最新core?

**Comment by vj23456** [comment]
@fredericky123 clashx把内核写在程序里了~无法替换二进制

**Comment by fredericky123** [comment]
> @fredericky123 clashx把内核写在程序里了~无法替换二进制

原来如此

**Comment by matthuo333** [comment]
Meta内核作用是什么？解决什么问题？

**Comment by MetaCubeX** [comment]
@matthuo333 https://clashmeta.gitbook.io/meta/

**Comment by matthuo333** [comment]
除健康检查外，看features 大部分和其它内核差不多。 还是有些自己没有Get到？

**Comment by MetaCubeX** [comment]
@matthuo333 和哪些其他内核差不多？ 你这么说反而是我没get到

**Comment by matthuo333** [comment]
因为最近Openclash 刚支持了Meta。因为一直使用oc, 然后看到Meta wiki中的那些介绍，对比在支持Meta前，大部分feature也能实现。所以就在想为什么支持Meta

**Comment by MetaCubeX** [comment]
@matthuo333 你可以看看openclash的meta介绍或设置页。

**Comment by ag2s20150909** [comment]
```bat
@echo off
cd /d %~dp0
clash -m -d ./data -f ./data/config.yaml
```
