### ISSUE TITLE
TUIC增加sni配置项

### ISSUE THREAD

**Issue by pk000** [MetaCubeX/Clash.Meta#380]
现有的代码不支持sni设置，只能跳过。建议增加sni配置，可以校验服务器。

**Comment by qist** [comment]
代理可以使用ip 代理服务器IP  就不需要跳过了,

**Comment by pk000** [comment]
如果方便实现校验的话，希望还是可以增加SNI配置。

**Comment by Skyxim** [comment]
@pk000 已经支持

**Comment by pk000** [comment]
@Skyxim 在Wiki（https://github.com/MetaCubeX/Clash.Meta/wiki/Configuring-example#tuic）中没看到SNI相关配置项，只看到disable-sni这一项。
我需要链接的服务器的域名与使用的SNI名字不一样，希望可以多个SNI项可以配置。
像surge/shadowrocket一样。host和sni单独配置。

**Comment by qist** [comment]
https://github.com/MetaCubeX/Clash.Meta/blob/Alpha/adapter/outbound/tuic.go 这里面 SNI                 string `proxy:"sni,omitempty"`

**Comment by pk000** [comment]
看到了。
Wiki页面也同步更新一下吧~
一般人不会看源代码。
另外alpha版本什么时候可以发布到最新release？
