### ISSUE TITLE
开启sniffer手游加速器玩外服游戏被还原成域名走节点流量

### ISSUE THREAD

**Issue by Misaka09982** [MetaCubeX/Clash.Meta#39]
家里路由器用了最新alpha内核开启sniffer，手机连wifi开手游加速器玩外服游戏，结果一卡一卡的，通过yacd看日志发现，手游加速器加速的节点被还原成域名走节点流量导致游戏不稳定。希望大佬解决一下。

**Comment by MetaCubeX** [comment]
@Misaka09982 你可以省一个加速器的钱

**Comment by vj23456** [comment]
@Misaka09982 后期会加 filter，解决类似问题

**Comment by Misaka09982** [comment]
> @Misaka09982 后期会加 filter，解决类似问题



> @Misaka09982 后期会加 filter，解决类似问题

好的
