### ISSUE TITLE
microarchitecture not support

### ISSUE THREAD

**Issue by liansishen** [MetaCubeX/Clash.Meta#393]
系统是n5105上的pve里面跑的debian11

用linux-amd64版本提示以下错误
This program can only be run on AMD64 processors with v3 microarchitecture support
改成compatible之后变成以下错误
This program can only be run on AMD64 processors with v2 microarchitecture support

所以在我这个环境里面不能用meta了吗？

**Comment by Skyxim** [comment]
@liansishen 把 pve 虚拟机设置中的 CPU 虚化 改成 host，或者尝试 cgo 那个，那个是 v1 的指令集下编译的

**Comment by liansishen** [comment]
> 
谢谢解答
改成host后用compatible可以了
