### ISSUE TITLE
the newest Alpha pre-release's performance is suck

### ISSUE THREAD

**Issue by johntaiko** [MetaCubeX/Clash.Meta#396]
in my router, the benchmark with my Trajon server in between cur: cd7d9fc with the version prev: 59cd89a of yesterday, that is 5 times the loss of speed

**Comment by H1JK** [comment]
Which arch are you using? Is that `amd64-compatible`?

**Comment by johntaiko** [comment]
> Which arch are you using? Is that `amd64-compatible`?

yes

**Comment by H1JK** [comment]
`amd64-compatible` has changed to GOAMD64 v1 since 6a89cc1 (previous v2).

So that should be the reason.

**Comment by Skyxim** [comment]
@johntaiko this change does not affect the code of throughput.

**Comment by johntaiko** [comment]
cpu is n4500
os is ubuntu22.10

everything is ok when i switch to prev-version

**Comment by johntaiko** [comment]
I'll also check by exclusion, maybe something else is wrong.

**Comment by H1JK** [comment]
IDK. You can build it yourself with environment variable `GOAMD64=v2` and then have a test.

Trojan-related code has not been modified within these commits and I think it is more likely to be caused by the GOAMD64 level changes.

**Comment by Skyxim** [comment]
As @H1JK said.
You can also consider the error of rule matching, which is caused by. This may be possible
This requires a look at the matching of rules in the log.

**Comment by johntaiko** [comment]
```
rules:
  #- SRC-IP-CIDR,192.168.3.15/32,TV
  # GEOSITE
  #- GEOSITE,category-ads-all,REJECT
  - GEOSITE,icloud@cn,DIRECT
  - GEOSITE,apple@cn,DIRECT
  - GEOSITE,apple-cn,DIRECT
  - GEOSITE,microsoft@cn,DIRECT
  - GEOSITE,facebook,PROXY
  - AND,((GEOSITE,youtube),(DST-PORT,443),(NETWORK,UDP)),REJECT
  - GEOSITE,youtube,PROXY
  - GEOSITE,gfw,PROXY
  - GEOSITE,geolocation-cn,DIRECT
  - GEOSITE,geolocation-!cn,PROXY
  # GEOIP
  - GEOIP,telegram,PROXY,no-resolve
  - GEOIP,private,DIRECT,no-resolve
  - GEOIP,lan,DIRECT
  - GEOIP,cn,DIRECT
  - MATCH,PROXY
```

I only used the GEO rules, I can be sure the prev-version works well
