### ISSUE TITLE
Xray Reality Support

### ISSUE THREAD

**Issue by BuWH** [MetaCubeX/Clash.Meta#398]
会支持最近发布的 Reality 协议吗 https://github.com/XTLS/REALITY

**Comment by Qlmuby** [comment]
希望能支持吧，新流控不支持，这也不支持，Xray在Meta上也就没啥存在感了，还不如直接抛弃支持Xray，现在还用xray的都是冲着新流控去的，毕竟稳一手，而其它协议人少，进而用Meta的也就更少了，也就Xray能多分点用户。

**Comment by xianren78** [comment]
vision最新alpha已经支持了，而且也会支持REALITY

**Comment by H1JK** [comment]
Supported in Alpha.
