### ISSUE TITLE
ss协议开启udp-over-tcp，udp流量不通

### ISSUE THREAD

**Issue by escapezn** [MetaCubeX/Clash.Meta#407]
服务端xray 1.7.5，客户端clash.meta 1.14.2版本，以及最新alpha版本 5bfad04 的ss协议，打开udp-over-tcp时，udp流量不通，回退1.14.1版本正常。

```
    udp: true
    udp-over-tcp: false
```
udp正常
```
    udp: true
    udp-over-tcp: true
```
udp不通

日志中udp连接经过代理
**time="2023-02-25T10:24:52.7893258+08:00" level=info msg="[UDP] [fdfe:dcba:9876::1]:52046(chrome.exe) --> [2404:6800:400a:1002::7f]:19302 match  using proxy[ssgr]"
time="2023-02-25T10:24:52.7948863+08:00" level=info msg="[UDP] 198.18.0.1:52045(chrome.exe) --> 142.250.23.127:19302 match  using proxy[ssgr]"**
time="2023-02-25T10:24:52.8185009+08:00" level=info msg="[TCP] 198.18.0.1:59942(chrome.exe) --> ipapi.atto.town:443 match Match using proxy[ssgr]"
time="2023-02-25T10:24:52.8194814+08:00" level=info msg="[TCP] 198.18.0.1:59943(chrome.exe) --> ipapi.atto.town:443 match Match using proxy[ssgr]"
time="2023-02-25T10:24:52.915534+08:00" level=debug msg="[DNS Server] Exchange ;stun.l.google.com.\tIN\t AAAA failed: all DNS requests failed, first error: websocket: close 1000 (normal)"
time="2023-02-25T10:24:52.9394899+08:00" level=debug msg="[DNS Server] Exchange ;ipapi.atto.town.\tIN\t AAAA failed: all DNS requests failed, first error: websocket: close 1000 (normal)"
time="2023-02-25T10:24:52.9394899+08:00" level=debug msg="[DNS Server] Exchange ;stun.l.google.com.\tIN\t A failed: all DNS requests failed, first error: websocket: close 1000 (normal)"
time="2023-02-25T10:24:52.9455178+08:00" level=debug msg="[DNS Server] Exchange ;ipapi.atto.town.\tIN\t A failed: all DNS requests failed, first error: websocket: close 1000 (normal)"
time="2023-02-25T10:24:52.9514915+08:00" level=debug msg="[DNS Server] Exchange ;stun.qq.com.\tIN\t AAAA failed: all DNS requests failed, first error: websocket: close 1000 (normal)"

相关问题https://github.com/MetaCubeX/Clash.Meta/issues/383

**Comment by wwqgtxx** [comment]
fixed in https://github.com/MetaCubeX/Clash.Meta/commit/3cd1c92162f83417cd1342268076ab7c6c90de01

**Comment by escapezn** [comment]
一直在用修复后的这个版本，最近更新到1.14.4后又发现存在同样的问题，1.14.3及最新alpha版本都有问题。
