### ISSUE TITLE
使用SS 2022加密时，Meta无法启动

### ISSUE THREAD

**Issue by Rakau** [MetaCubeX/Clash.Meta#409]
time="2023-02-25T05:41:27.865410347Z" level=info msg="Start initial configuration in progress"
time="2023-02-25T05:41:27.865802222Z" level=error msg="proxy 15: ss xx:114514 initialize error: decode key: illegal base64 data at input byte 8"
configuration file /data/adb/box/clash/config.yaml test failed

[v1.14.2](https://github.com/MetaCubeX/Clash.Meta/releases/tag/v1.14.2)

**Comment by ArchGuyWu** [comment]
@Rakau 你应该参考[[此处](https://xtls.github.io/config/inbounds/shadowsocks.html#clientobject)]的方法生成密码
