### ISSUE TITLE
使用vless-xtls-vision协议无法正常游玩碧蓝档案国际服

### ISSUE THREAD

**Issue by ShoukakuChuuCC** [MetaCubeX/Clash.Meta#411]
![image](https://user-images.githubusercontent.com/38343280/221360423-0e1fa660-9f4c-496d-8917-ea133080d745.png)
debug日志：https://paste.ubuntu.com/p/zp67SJXrSy

使用xray v1.7.5正常
使用clash.meta alpha-a3b8c9c提示无法通过CDN取得数据

**Comment by ShoukakuChuuCC** [comment]
战地2042也无法正常游玩，连不上服务器

**Comment by H1JK** [comment]
Please close the Telegram process when recording logs because it creates a lot of connections and cause confusion.

It looks like a chained proxy. What's your Clash proxy config, tho? And could you also post Xray server-side log?

**Comment by ShoukakuChuuCC** [comment]
xray-core版本，最新commit a5b297f
xray日志: https://paste.ubuntu.com/p/HxbyDK3zVW
一起记录的clash日志: https://paste.ubuntu.com/p/G3StTDH3D3

xray配置:
{
  "log": {
    "loglevel": "warning",
    "error": "/var/log/xray/error.log",
    "access": "/var/log/xray/access.log"
  },
  "inbounds": [
    {
      "listen": "0.0.0.0",
      "port": "57916",
      "protocol": "vless",
      "settings": {
        "decryption": "none",
        "clients": [
          {
            "id":"Shoukaku",
            "flow": "xtls-rprx-vision"
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "tls",
        "sockopt": {"tcpFastOpen": true},
        "tlsSettings": {
          "certificates": [
            {
              "certificateFile": "",
              "keyFile": ""
            }
          ]
        }
      }
    }
  ],
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "ip": ["geoip:cn"],
        "outboundTag": "block"
      }
    ]
  },
  "outbounds": [
    {
      "tag": "direct",
      "protocol": "freedom"
    },
    {
      "tag": "block",
      "protocol": "blackhole"
    }
  ]
}

clash配置
- name: AWS-SGP-Vision
  type: vless
  server: 
  port: 57916
  uuid: Shoukaku
  network: tcp
  tls: true
  tfo: true
  udp: true
  xudp: true
  flow: xtls-rprx-vision
  client-fingerprint: firefox

**Comment by ShoukakuChuuCC** [comment]
直连没有链式代理，而且发现浏览网页偶尔会ERR_SSL_PROTOCOL_ERROR

**Comment by ShoukakuChuuCC** [comment]
@H1JK 忘记点reply了 手动艾特一下 嘿嘿

**Comment by ShoukakuChuuCC** [comment]
![image](https://user-images.githubusercontent.com/38343280/221393737-cf523f57-1e13-4d2b-b93c-e7831e72fcc6.png)
用vision下载github release文件时也会出错

**Comment by H1JK** [comment]
Tested on Windows 10 and IDM but I can't repro. Please make sure that you are using the latest Alpha build.

**Comment by ShoukakuChuuCC** [comment]
> 

基于alpha-0321fe9测试

**Comment by ShoukakuChuuCC** [comment]
> Tested on Windows 10 and IDM but I can't repro. Please make sure that you are using the latest Alpha build.

基于alpha-0321fe9测试

**Comment by xianren78** [comment]
> > Tested on Windows 10 and IDM but I can't repro. Please make sure that you are using the latest Alpha build.
> 
> 基于alpha-0321fe9测试

再debug一下

**Comment by ShoukakuChuuCC** [comment]
> > > Tested on Windows 10 and IDM but I can't repro. Please make sure that you are using the latest Alpha build.
> > 
> > 
> > 基于alpha-0321fe9测试
> 
> 再debug一下

xray log: https://paste.ubuntu.com/p/zK3FHZb5C6/
clash log: https://paste.ubuntu.com/p/QwySyNyGVC/

**Comment by Larvan2** [comment]
改了一下，~~再探再报~~

**Comment by ShoukakuChuuCC** [comment]
fix

**Comment by qist** [comment]
[ERROR] XTLS Vision server responded unknown UUID: 48545450-2f31-2e31-2032-3034204e6f20 接收错误的uuid了

**Comment by H1JK** [comment]
> [ERROR] XTLS Vision server responded unknown UUID: 48545450-2f31-2e31-2032-3034204e6f20 接收错误的uuid了

@qist Since 8771fa5, Alpha has been updated to the latest Vision protocol spec, which made it partially incompatible with Xray v1.7.5. If you want to use Alpha XTLS Vision, please update your server-side Xray to CI build version (or wait for the next Xray release).

**Comment by Abdipour** [comment]
Upgrade xray-core on server to 1.8.0 fixed this.

**Comment by LedPeach** [comment]
> > [ERROR] XTLS Vision server responded unknown UUID: 48545450-2f31-2e31-2032-3034204e6f20 接收错误的uuid了
> 
> @qist Since [8771fa5](https://github.com/MetaCubeX/mihomo/commit/8771fa5c17e8eb430739eb125bc283f3dc0b32df), Alpha has been updated to the latest Vision protocol spec, which made it partially incompatible with Xray v1.7.5. If you want to use Alpha XTLS Vision, please update your server-side Xray to CI build version (or wait for the next Xray release).

Sry, I know this is a closed issue. 
But does this issue still exist on Xray v.24.11.21 with vless + reality protocol using vision flow? 

I'm having [this](https://github.com/MetaCubeX/mihomo/issues/411#issuecomment-1455288665) exact error on the clash meta client side and the following error on the xray server side: 
`2024/11/24 02:17:13 [Info] transport/internet/tcp: REALITY: processed invalid connection
2024/11/24 02:17:13 [Info] transport/internet/tcp: REALITY: processed invalid connection
2024/11/24 02:17:13 [Info] transport/internet/tcp: REALITY: processed invalid connection`

And I'm following the [wiki's example config](https://wiki.metacubex.one/config/proxies/vless/) to the teeth. 
With the same config, it works on the V2rayN client but not with Clash Meta. 
Though the only difference is I have this `SpiderX` parameter on the server side. 
It is one of the `RealityConfig` for the Xray-core: https://github.com/XTLS/Xray-core/blob/513f18bf531ef5f92464c2affefed0db4f28280b/infra/conf/transport_internet.go#L525-L543 
But the clash meta doesn't have it in the example config: https://github.com/MetaCubeX/mihomo/blob/eb985b002e5aa61c4c2208646f33180c4fc938f9/docs/config.yaml#L594-L608

Is it not supported in clash meta yet? Or can I just add it manually?
