### ISSUE TITLE
未来是否会支持Naiveproxy协议？

### ISSUE THREAD

**Issue by katayaburi** [MetaCubeX/Clash.Meta#415]
并不是用Go实现Naiveproxy，而是作为分流(GEOIP)，将正确的代理流量以及国外网站DNS查询功能转至Naiveproxy。希望可以指定Naiveproxy核心文件（如果是OpenWRT的话安装了Naiveproxy的包就可以使用）。

目前Clash是支持HTTPS协议的，不过Naiveproxy主要解决了以下问题（也是该作者在文档中提到的）：

1. 使用Chrome的网络协议栈，解决客户端特殊的TLS指纹问题。并且指纹版本跟随Chrome版本更进，避免使用过旧版本。
2. 包长度填充，缓解TLS in TLS包长度的特征问题。

在最新的[Clash.Meta](https://github.com/MetaCubeX/Clash.Meta)中已经支持了全局的TLS指纹，但目前局限于VLESS/Vmess以及Trojan。

如果不支持的话，未来全局的TLS指纹功能覆盖到其他协议吗？或者说，使用别的方式也可以实现差不多的功能？

**Comment by Skyxim** [comment]
@katayaburi 其它？还有 tcp 的协议，是 tls 的么

**Comment by katayaburi** [comment]
上游Clash支持的SS（开启TLS）、HTTPS，以及Socks5 over TLS。
