### ISSUE TITLE
new url-test method

### ISSUE THREAD

**Issue by mozilla-firefox** [MetaCubeX/Clash.Meta#418]
Hello
Current clash url-test method is not best. please add a second method.
There is a method by NekoRay: https://github.com/MatsuriDayo/nekoray/issues/387#issuecomment-1436616481
And also a idea from me. Clash can send a HEAD request to a URL and wait for any or specified response-code.
check them please
thank you

**Comment by wwqgtxx** [comment]
I don't think it is necessary to send a lot of garbage requests to the server for a little bit of accuracy improvement. NekoRay's approach is nothing more than sending three requests to take the average.
In addition, the gen_204 currently used by url-test itself does not have any body, and there is no difference between using GET or HEAD to send requests.
In summary, this issue will not be fixed.

**Comment by Skyxim** [comment]
@mozilla-firefox What is the best?

**Comment by VZiChoushaDui** [comment]
I'm not sure if this is ever going to implemented, but if it is, perhaps an average or weighted average of previous health checks (based on the user defined interval) would be a better solution than multiple "garbage" requests?
