### ISSUE TITLE
希望支持ss2022的tcp封装udp功能

### ISSUE THREAD

**Issue by Kryo123456** [MetaCubeX/Clash.Meta#419]
如题，不知道这个在meta内核上实现困不困难。

**Comment by xishang0128** [comment]
@Kryo123456 ss2022的uot早就支持了啊

**Comment by Kryo123456** [comment]
> 

我在完整示例的文档里没有看到诶，配置应该怎么写呢

**Comment by Kryo123456** [comment]
> 我在完整示例的文档里没有看到诶，配置应该怎么写呢



> @Kryo123456 ss2022的uot早就支持了啊

我在完整示例的文档里没有看到诶，配置应该怎么写呢

**Comment by xishang0128** [comment]
@Kryo123456 udp-over-tcp: true
