### ISSUE TITLE
web 面板哪里可以下载对应的web程序？

### ISSUE THREAD

**Issue by chuntsky** [MetaCubeX/Clash.Meta#423]
目前 使用的是 wiki上记录的 
支持Meta特性的在线面板
http://clash.metacubex.one
http://yacd.metacubex.one

我想自己部署在本地，请问哪里可以下载：支持meta特性的WEB面板 ？

**Comment by Larvan2** [comment]
@chuntsky https://github.com/MetaCubeX/Yacd-meta/archive/refs/heads/gh-pages.zip

**Comment by chuntsky** [comment]
> @chuntsky https://github.com/MetaCubeX/Yacd-meta/archive/refs/heads/gh-pages.zip

有用，谢谢！
