### ISSUE TITLE
PVE虚拟openwrt使用版本1.4.2负载异常

### ISSUE THREAD

**Issue by dycwuxing** [MetaCubeX/Clash.Meta#428]
请问我该如何排查呢?
CPU:J4125
PVE通过虚拟机安装OpenWRT,内核版本5.4.188,安装openclash使用
完全相同的在V1.14.1和之前版本均无异常.1.14.2及alpha版本均100%复现
<img width="687" alt="image" src="https://user-images.githubusercontent.com/44988562/222958217-f7a417ed-d4f4-4286-81c9-54542ca8cb38.png">
<img width="598" alt="image" src="https://user-images.githubusercontent.com/44988562/222958312-07deabb5-8244-4501-b9e7-a2e34fef63b2.png">
<img width="1394" alt="image" src="https://user-images.githubusercontent.com/44988562/222958161-503be49f-882e-4301-b9d2-d8ea50338c80.png">
<img width="801" alt="image" src="https://user-images.githubusercontent.com/44988562/222958177-017f5211-adcd-45d4-aa12-a03e83e40d77.png">
<img width="727" alt="image" src="https://user-images.githubusercontent.com/44988562/222958197-b8943401-4a89-4968-9876-62608eef99e5.png">

**Comment by Skyxim** [comment]
配置文件，设置 log-level 为 debug，遇到问题访问`http://${controller-api}/debug/pprof/profile\?seconds\=30`下载 CPU 统计文件，30 代表 30s 内的数据

**Comment by dycwuxing** [comment]
> 
大佬,提示这个,请问应该怎么用.....
<img width="481" alt="image" src="https://user-images.githubusercontent.com/44988562/222959672-6d7a2c22-8afa-4684-a610-f920bb9d4f2a.png">
<img width="711" alt="image" src="https://user-images.githubusercontent.com/44988562/222959685-68fe6c35-d226-4bb7-87a5-45e2530ded94.png">

**Comment by Skyxim** [comment]
@dycwuxing 饿，忘了，你得换到最新的测试版本内核才能有这个 API

**Comment by dycwuxing** [comment]
> 

呃...我改用了1.14.2,然后配置打开了debug,网址输入的是:http://[192.168.10.1:9090/debug/pprof/profile/?seconds\=30](http://192.168.10.1:9090/debug/pprof/profile/?seconds\=30)

但是是这样提示的
<img width="522" alt="image" src="https://user-images.githubusercontent.com/44988562/222960189-11aa0357-0d63-4e07-98bc-1ec22e5008b6.png">
<img width="575" alt="image" src="https://user-images.githubusercontent.com/44988562/222960216-7eac0aaf-2eaf-44b0-86ef-c1f41523cc0f.png">
<img width="272" alt="image" src="https://user-images.githubusercontent.com/44988562/222960272-b8b043a4-dd2e-42db-8609-551080d59910.png">

**Comment by Skyxim** [comment]
最新的测试版本

**Comment by dycwuxing** [comment]
> 最新的测试版本
还是不行,提示“Unknown profile“
<img width="632" alt="image" src="https://user-images.githubusercontent.com/44988562/222960674-c80fb89a-60d4-48cd-a1c2-036a356cf825.png">
<img width="763" alt="image" src="https://user-images.githubusercontent.com/44988562/222960565-eeaf3a1c-d431-428a-a22d-073da71b4677.png">
<img width="765" alt="image" src="https://user-images.githubusercontent.com/44988562/222960642-960850d3-6e03-480d-8767-6884d2c2de93.png">

**Comment by Skyxim** [comment]
我的，`http://${controller-api}/debug/pprof/profile?seconds=30` 不应该有反斜杠

**Comment by dycwuxing** [comment]
> 我的，`http://${controller-api}/debug/pprof/profile?seconds=30` 不应该有反斜杠

大佬,这次跑出来了,能给我个邮箱发给您不?

**Comment by Skyxim** [comment]
@dycwuxing 直接能上传 GitHub ，这里面没有敏感信息

**Comment by dycwuxing** [comment]
> @dycwuxing 直接能上传 GitHub ，这里面没有敏感信息
好的,谢谢啦~~
[profile.zip](https://github.com/MetaCubeX/Clash.Meta/files/10891855/profile.zip)

**Comment by dycwuxing** [comment]
> @dycwuxing 你这个文件的时候，有负载异常的问题么，需要在负载异常的时候使用
有的，只要启动就开始快速变高，我目前又换回14.1了，刚才没及时截图，现在还能看到那个10点多的负载
![57D8EAAC-A2F0-4D65-8083-2B08DEAC4F90](https://user-images.githubusercontent.com/44988562/222961671-d59ac4b8-bfbc-4406-81ee-e297195f1063.jpeg)

**Comment by Skyxim** [comment]
启动时高一瞬间，还能理解。只要不是一直不恢复

**Comment by dycwuxing** [comment]
> 启动时高一瞬间，还能理解。只要不是一直不恢复


呃.....不是的,是一直在增高,直到断网无法使用
目前只能是继续使用14.1
14.2处于无法使用的状态....
这个负载数值太夸张了....,CPU上来看的话,只要启动就开始维持在30~40%的占用不下降
<img width="429" alt="image" src="https://user-images.githubusercontent.com/44988562/222962165-a4f02c42-f4b1-484d-958c-bd02e7a065f5.png">

**Comment by Skyxim** [comment]
那等他高了在用个下载下，低了的时候不太明显

**Comment by dycwuxing** [comment]
> http://${controller-api}/debug/pprof/profile?seconds=30

这次记录了差不多5-10分钟左右

<img width="631" alt="image" src="https://user-images.githubusercontent.com/44988562/222964621-c7450b61-d774-41ea-963c-e9f7cce6951d.png">
[profile.zip](https://github.com/MetaCubeX/Clash.Meta/files/10891950/profile.zip)

**Comment by Skyxim** [comment]
你试试这个配置
![image](https://user-images.githubusercontent.com/70276018/222965114-48faaa83-3737-4797-aa3f-b03505f78247.png)
或者配置文件中写入
```
find-process-mode: 'off'
```

**Comment by dycwuxing** [comment]
> 你试试这个配置 ![image](https://user-images.githubusercontent.com/70276018/222965114-48faaa83-3737-4797-aa3f-b03505f78247.png) 或者配置文件中写入
> 
> ```
> find-process-mode: 'off'
> ```
目前在luci界面使用“off”,而非“停用”后,暂无异常了,我继续观察下,非常非常感谢!

**Comment by dycwuxing** [comment]
感觉已经没有问题了,再次感谢!
