### ISSUE TITLE
may not have any sent data, Consider adding skip"

### ISSUE THREAD

**Issue by Bitcion** [MetaCubeX/Clash.Meta#429]
【clash】:  time="2023-03-06T02:56:18.875736745Z" level=error msg="[Sniffer] [17.57.145.167] may not have any sent data, Consider adding skip"

大约找到一些原因了：
PADAVAN固件，开启了chinadns-ng跟smartdns，防止污染。chinadns-ng监听是8053，然后clash也是监听8053。可能是这个冲突原因导致这个现象

当然，具体原因不清楚。我只是在想，既然clash收到了这些 无效的data，能否直接做到自动忽略或者按ip处理，自动不进行sni还原了

**Comment by Bitcion** [comment]
发现一点原因：大部分出现这个错误是telegram纯ip代理出现的问题。
个人分析是telegram在进行代理是，sniffer会试图还原其ip

建议sniffer添加自动忽略IP-CIDR 域名还原

**Comment by Skyxim** [comment]
多于多次嗅探失败将对此目的地址进行自动跳过

**Comment by Konbai-code** [comment]
2025-04-15 22:07:43 level=error msg="[Sniffer] [101.32.143.247] [http1] may not have any sent data, Consider adding skip"

我也有很多这类error。如何解决呢

**Comment by zgc** [comment]
> 2025-04-15 22:07:43 level=error msg="[Sniffer] [101.32.143.247] [http1] may not have any sent data, Consider adding skip"
> 
> 我也有很多这类error。如何解决呢

我也是有同样的问题

**Comment by Konbai-code** [comment]
更换机场解决了。不知道是dns的问题还是其他啥

**Comment by zgc** [comment]
> 更换机场解决了。不知道是dns的问题还是其他啥

我是自建的，没得换

**Comment by Dubian-che720** [comment]
我也是遇到类似的问题，具体表现是网络不稳，会时而断网

**Comment by Skyxim** [comment]
@Dubian-che720 有没有可能这个就是因为网络不稳定而提示的？

**Comment by Dubian-che720** [comment]
我不知道具体原因，但是如果只是ping目标IP延迟和丢包看起来都一切正常，在移动网络和WIFI场景下也是如此> @Dubian-che720 有没有可能这个就是因为网络不稳定而提示的？
