### ISSUE TITLE
关于通过 TProxy 代理 IPv6 流量并匹配到直连规则时，IP 被修改为了网关 IP，请教一下原因以及有没有办法改变

### ISSUE THREAD

**Issue by EkkoG** [MetaCubeX/Clash.Meta#430]
clash 跑在 OpenWrt 上，通过 TProxy 代理 IPv6 流量时，在匹配到直连规则的情况下，网站检测到的 IP  不是发起请求的那台机的 IP 而是路由器的 IP，比如发起请求的 IP 是 xxx::cd3，路由器 IP xxx::1，访问 6.com，在 6.com 上显示的当前 IP 是 xxx::1 而不是 xxx::cd3

  这个行为有办法通过配置改变吗？

是因为什么呢，是因为流量被代理后，是在路由器上重新建立的 TCP 连接导致的吗

这个行为一般用户来说没什么差别，就是对 PT/BT 用户来说，这个行为看起来就像是网关在和 tracker 通讯，导致 tracker 会认为客户端 IP 是网关，而实际上并不是，就出错了

**Comment by Skyxim** [comment]
@EkkoG 没办法，代理软件就是这样，你只有让他不进入代理

**Comment by EkkoG** [comment]
> @EkkoG 没办法，代理软件就是这样，你只有让他不进入代理

OK，那我知道了

还是想请教一下原因，是因为和 6.com 的通讯实际是由 clash 重新建立的连接，而 clash 跑在网关上，所以当前 IP 变成了网关 IP，这样吗

**Comment by Skyxim** [comment]
@EkkoG 对

**Comment by EkkoG** [comment]
> @EkkoG 对

了解了，感谢回答！
