### ISSUE TITLE
alpha内核xtls-rprx-vision测速失灵

### ISSUE THREAD

**Issue by vicdorke** [MetaCubeX/Clash.Meta#431]
一直显示超时，实际可以连接

**Comment by Skyxim** [comment]
@vicdorke vision 协议处于不稳定状态，保证软件最新，或等待适配

**Comment by Larvan2** [comment]
https://github.com/XTLS/Xray-core/actions/runs/4331697589 从此处下载最新版服务端

**Comment by vicdorke** [comment]
啊@什么超前部署

**Comment by wwqgtxx** [comment]
add a notice to upgrade server version by https://github.com/MetaCubeX/Clash.Meta/commit/e7f907291193d05d1218cdb1307980c6890a8565

**Comment by twlz0ne** [comment]
@Larvan2 
> [XTLS/Xray-core/actions/runs/4331697589](https://github.com/XTLS/Xray-core/actions/runs/4331697589) 从此处下载最新版服务端

下载了 xray-core 放哪里，怎么用？
