### ISSUE TITLE
xtls-rprx-vision 配置不对吗

### ISSUE THREAD

**Issue by lbbboy** [MetaCubeX/Clash.Meta#434]
```
 - name: "vless-tcp"
    type: vless
    server: server
    port: 443
    uuid: uuid
    network: tcp
    servername: example.com
      flow: xtls-rprx-vision
    # skip-cert-verify: true
    # fingerprint: xxxx
```
内核：v1.14.2
Clash Verge 1.2.3

加入后，节点都不在了。

**Comment by Abdipour** [comment]
To connect xtls-rprx-vision you should use alpha version of Clash.Meta. unfortunately Clash Verge not use Alpha version.
I had same problem. Now fixed by using ClashMetaForAndroid and upgrade xray-core on server to 1.8.0.

**Comment by H1JK** [comment]
1. Where is your `tls: true`?
2. Indents matter.
3. You can replace Clash-Verge Meta core by yourself. CC @Abdipour.
