### ISSUE TITLE
代理链的相关问题

### ISSUE THREAD

**Issue by feng-king** [MetaCubeX/Clash.Meta#436]
代理链不支持tuic over socks吗，我尝试了tuic over vmess是可以的，tuic over socks会报错：
`time="2023-03-10T19:04:16.8000111+08:00" level=warning msg="[TCP] dial 🚀 节点选择 (match Match/) 127.0.0.1:57343 --> 91.108.56.111:80 error: no support"
time="2023-03-10T19:04:16.8621555+08:00" level=warning msg="[TCP] dial 🚀 节点选择 (match Match/) 127.0.0.1:57348 --> 149.154.175.53:443 error: no support"
time="2023-03-10T19:04:16.9392171+08:00" level=warning msg="[TCP] dial 🚀 节点选择 (match Match/) 127.0.0.1:57344 --> 149.154.175.53:80 error: no support"
time="2023-03-10T19:04:16.9544977+08:00" level=warning msg="[TCP] dial 🚀 节点选择 (match Match/) 127.0.0.1:57341 --> 91.108.56.111:443 error: no support"`

配置文件：
`proxies:
  - {name: vmess0, server: ****, port: 443, type: vmess, uuid: **, alterId: 0, cipher: auto, tls: true, skip-cert-verify: true, servername: ****, network: ws, ws-opts: {path: **, headers: {Host: ****}}, udp: true}

  - name: tuic.🇺🇸
    server: cdn.procnik.cf
    port: 41011
    type: tuic
    token: fuck
    ip: 1.1.1.1
    heartbeat-interval: 10000
    alpn: [H4]
    # disable-sni: true
    reduce-rtt: true
    # request-timeout: 8000
    udp-relay-mode: native # Available: "native", "quic". Default: "native"
    congestion-controller: bbr # Available: "cubic", "new-reno", "bbr". Default: "cubic"
    skip-cert-verify: true

  - name: socks_10898
    type: socks5
    server: 127.0.0.1
    port: 32613
    # username: username
    # password: password
    # tls: true
    # skip-cert-verify: true
    udp: true

proxy-groups:
  - name: 🚀 节点选择
    type: select
    proxies:
      # - tuic.🇺🇸
      - chains

  - name: chains
    type: relay
    proxies:
      - socks_10898    #换成vmess0就可以用
      - tuic.🇺🇸`

**Comment by Skyxim** [comment]
@feng-king tuic 走代理链是怎么想的

**Comment by Skyxim** [comment]
@feng-king clash 代理链不支持 udp

**Comment by wwqgtxx** [comment]
代理链目前不支持socks的udp部分
目前relay可以支持udp的只有vmess/vless/trojan/ss/ssr/tuic

**Comment by feng-king** [comment]
好吧
