### ISSUE TITLE
[Process] process not found

### ISSUE THREAD

**Issue by hadifarnoud** [MetaCubeX/Clash.Meta#437]
I get a lot of errors like these:
`[Process] find process connectivitycheck.gstatic.com: process not found`

I use latest core `alpha-g3b037ac`

edit: I use gvisor as TUN and youtube does not work on my TV. Instagram does not work on some devices, etc.

I thought the issue could be related to errors above. I see no other errors in logs

**Comment by hadifarnoud** [comment]
I managed to fix youtube issue on my TV but now Apple's app store and imessage don't work

here is what I changed:
change TUN to system
changed DNS redirect to Firewall redirect (using openclash)
changed Enable Process Rule to OFF

any idea what fixed it? and what is causing SSL issue for apple services?
```
curl -vvv "https://bag.itunes.apple.com/bag.xml?deviceClass=Macintosh&format=json&os=OS%20X&osVersion=13.1&product=MacAppStore&productVersion=3.0&profile=MacAppStore"
*   Trying 198.18.0.5:443...
* Connected to bag.itunes.apple.com (198.18.0.5) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (OUT), TLS handshake, Client hello (1):
* LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to bag.itunes.apple.com:443
* Closing connection 0
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to bag.itunes.apple.com:443
```

**Comment by Skyxim** [comment]
@hadifarnoud You can look at the log, bag.itunes.apple.com is it through a proxy or direct connection.

**Comment by hadifarnoud** [comment]
it's through proxy `23-03-15 10:33:26[ warn ][TCP] dial Apple (match RuleSet/Apple) 192.168.1.176:57063 --> bag.itunes.apple.com:443 error: dns resolve failed: context deadline exceeded`

in fact I have many `dns resolve failed: context deadline exceeded` errors

**Comment by Skyxim** [comment]
@hadifarnoud DNS resolve timeout

**Comment by hadifarnoud** [comment]
it's weird everything else works though. just apple services don't work

**Comment by hadifarnoud** [comment]
it was a DNS server issue. thanks
