### ISSUE TITLE
希望能为nameserver-policy添加兜底规则的设置

### ISSUE THREAD

**Issue by EsuRt** [MetaCubeX/Clash.Meta#447]
使用nameserver-policy进行dns分流后，不在规则中的网站就无法打开，测试直接给该网站指定dns后，能正常打开，希望能添加一个兜底规则的设置。

**Comment by xishang0128** [comment]
@EsuRt nameserver policy如果没有匹配到就会到nameserver,请检查你的nameserver/fallback配置

**Comment by EsuRt** [comment]
> @EsuRt nameserver policy如果没有匹配到就会到nameserver,请检查你的nameserver/fallback配置

如果设置了nameserver，nameserver-policy规则中的域名是否会同时使用nameserver的dns进行解析？
