### ISSUE TITLE
Support mKCP, hysteria and uuid with custom string

### ISSUE THREAD

**Issue by ghost** [MetaCubeX/Clash.Meta#45]
1. [mkcp](https://github.com/Dreamacro/clash/issues/150)

1. [hysteria](https://github.com/hynetwork/hysteria)

1. [uuid with custom string](https://github.com/XTLS/Xray-core/issues/158)

**Comment by MarksonHon** [comment]
@LGTMXD So could you please show your code?

**Comment by tayson1106** [comment]
I think he doesn't have any code. He just want to add these functions into clash meta core.

**Comment by MetaCubeX** [comment]
We will consider suggestions.

**Comment by MetaCubeX** [comment]
> 1. [mkcp](https://github.com/Dreamacro/clash/issues/150)
> 2. [hysteria](https://github.com/hynetwork/hysteria)
> 3. [uuid with custom string](https://github.com/XTLS/Xray-core/issues/158)  ==> e11f6f8
