### ISSUE TITLE
配置openai 走warp代理关闭udp时走直连了。

### ISSUE THREAD

**Issue by qist** [MetaCubeX/Clash.Meta#457]
个人vps被openai拉黑走warp时，warp不能转发udp 就vps 连接openai ，代理关闭udp 就出现主机直连国内ip也是被拉黑得。能不能配置指定某些站点只走tcp 不走quic

**Comment by xishang0128** [comment]
https://clash-meta.wiki/config/rules/logic/ 使用逻辑规则
