### ISSUE TITLE
开启tun模式后无法访问git

### ISSUE THREAD

**Issue by fecet** [MetaCubeX/Clash.Meta#460]
开启tun后`ssh git`或者`git pull`都提示失败, 看日志是clash用了198.18.0.8这个地址尝试连接, 这是预期内的吗, 如何解决呢

**Comment by fecet** [comment]
> @fecet 请确保你的代理没用禁用22端口来源

代理是指clash的前端?

**Comment by ArchGuyWu** [comment]
> 代理是指clash的前端?
你的节点
