### ISSUE TITLE
go build 成功后，只有一个clash文件，双击是命令窗口，没有gui窗口吗？怎么修改代理配置

### ISSUE THREAD

**Issue by froggengoing** [MetaCubeX/Clash.Meta#469]

**Comment by ha-ku** [comment]
这是clash core的仓库，core只是一个可执行文件，从命令行启动的时候通过在参数里指定配置文件来运行。GUI客户端请参考readme中wiki链接里的客户端列表。

**Comment by froggengoing** [comment]
找到了
start clash-meta:
put your config.yaml in this directory and run:

./clash-meta -d ./

**Comment by Cyberbolt** [comment]
请问

> 找到了 start clash-meta: put your config.yaml in this directory and run:
> 
> ./clash-meta -d ./

请问是在哪里找到的？我找了很久都没找到 clash-meta 命令行（客户端）怎么运行
