### ISSUE TITLE
配置文件书写乱序有影响吗

### ISSUE THREAD

**Issue by kkksa528** [MetaCubeX/Clash.Meta#479]
把代理放最前面，客户端配置，dns设置放中间，规则放最后，举例：
proxies:
 xxxxx
 xxxxx
  xxxx

mixed-port: 10801
allow-lan: true
bind-address: '*'
find-process-mode: strict
mode: rule
log-level: info
ipv6: true
external-controller: '127.0.0.1:9090'
global-client-fingerprint: chrome

profile:
    store-selected: false
    store-fake-ip: true
dns:
    xxxxx

rules:
xxxx
xxxx
rule-providers:
xxxx
xxxx

这样写 配置内核不报错，会完全生效吗

**Comment by handsomexdd1024** [comment]
entry的顺序不影响，只要保证entry之间的等级（父子）关系正确就行
要是还不明白，最简单的方法是自己尝试一下（

**Comment by kkksa528** [comment]
> entry的顺序不影响，只要保证entry之间的等级（父子）关系正确就行 要是还不明白，最简单的方法是自己尝试一下（

多次尝试，没影响
