### ISSUE TITLE
一个错误，偶尔会导致重启

### ISSUE THREAD

**Issue by Bitcion** [MetaCubeX/Clash.Meta#480]
Apr  3 11:24:12 【clash】:  panic: runtime error: index out of range [-1]
Apr  3 11:24:12 【clash】:  
Apr  3 11:24:12 【clash】:  goroutine 781552 [running]:
Apr  3 11:24:12 【clash】:  github.com/Dreamacro/clash/adapter/outboundgroup.strategyRoundRobin.func1({0x2d89260, 0x5, 0x6}, 0x35549a0)
Apr  3 11:24:12 【clash】:   github.com/Dreamacro/clash/adapter/outboundgroup/loadbalance.go:132 +0x190
Apr  3 11:24:12 【clash】:  github.com/Dreamacro/clash/adapter/outboundgroup.(*LoadBalance).Unwrap(0x3455ab0, 0x35549a0, 0x0)
Apr  3 11:24:12 【clash】:   github.com/Dreamacro/clash/adapter/outboundgroup/loadbalance.go:204 +0x80
Apr  3 11:24:12 【clash】:  github.com/Dreamacro/clash/tunnel.match(0x35549a0)
Apr  3 11:24:12 【clash】:   github.com/Dreamacro/clash/tunnel/tunnel.go:494 +0x90c
Apr  3 11:24:12 【clash】:  github.com/Dreamacro/clash/tunnel.resolveMetadata({0x737ee500, 0x595e160}, 0x35549a0)
Apr  3 11:24:12 【clash】:   github.com/Dreamacro/clash/tunnel/tunnel.go:232 +0xc4
Apr  3 11:24:12 wsdd2[2274]: wsdd-http-v6: open_ep: bind: Address already in use
Apr  3 11:24:12 【clash】:  github.com/Dreamacro/clash/tunnel.handleTCPConn({0x11c2050, 0x595e160})
Apr  3 11:24:12 【clash】:   github.com/Dreamacro/clash/tunnel/tunnel.go:373 +0x250
Apr  3 11:24:12 【clash】:  created by github.com/Dreamacro/clash/tunnel.process
Apr  3 11:24:12 【clash】:   github.com/Dreamacro/clash/tunnel/tunnel.go:179 +0xbc

chatgpt给的建议是：
github.com/Dreamacro/clash/adapter/outboundgroup.strategyRoundRobin.func1({0x2d89260, 0x5, 0x6}, 0x35549a0)
github.com/Dreamacro/clash/adapter/outboundgroup/loadbalance.go:132 +0x190

Clash Meta alpha-1a1e334 linux mipsle with go1.20.1 Sun Feb 19 02:11:32 UTC 2023

**Comment by Skyxim** [comment]
@Bitcion clash -v，版本是多少，是最新版本么。有尝试过 alpha 没

**Comment by Skyxim** [comment]
> Sun Feb 19 02:11:32 UTC 2023

使用最新版本，确定问题再进行反馈
