### ISSUE TITLE
通过scoop安装，无法使用，应用闪退，是否兼容了

### ISSUE THREAD

**Issue by Niefee** [MetaCubeX/Clash.Meta#481]
```
版本	Windows 10 企业版 LTSC
版本号	21H2
安装日期	‎2022/‎9/‎23 ‎星期五
操作系统内部版本	19044.2486
体验	Windows Feature Experience Pack 120.2212.4190.0
```
系统信息

**Comment by ArchGuyWu** [comment]
你是通过命令：scoop install clash.meta安装的吗？这样安装的是裸核，是个命令行程序

**Comment by Niefee** [comment]
@ArchGuyWu 这样安装怎么使用啊，没有gui客户端吗

**Comment by xishang0128** [comment]
https://clash-meta.wiki/client/  请使用官方支持meta的gui客户端

**Comment by Niefee** [comment]
@xishang0128 公司系统限制，只能通过scoop ，有没办法安装clash.meta

**Comment by nkta3m** [comment]
我也使用scoop install clash.meta, 无法执行啊，只能手动下载了clash.meta-windows-cgo这个程序
