### ISSUE TITLE
[Feature] vless/vmess已经支持多端口，port可以是string/int，但clash.meta貌似不支持

### ISSUE THREAD

**Issue by jantacy** [MetaCubeX/Clash.Meta#486]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://clash-meta.wiki/) 并无法自行解决问题 I have read the [documentation](https://clash-meta.wiki/) and was unable to solve the issue. 

### Description

vless/vmess支持同一个bound有多个端口，其port可以是int也可以是string，但目前clash.meta仅支持int，且当前hysteria中的ports也不能用于vless/vmess中。

希望大佬们考虑支持一下~

**Comment by white586** [comment]
我也遇到了相同的问题
