### ISSUE TITLE
[Bug] vless reality grpc  error: REALITY authentication failed

### ISSUE THREAD

**Issue by qist** [MetaCubeX/Clash.Meta#487]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://clash-meta.wiki/) 并无法自行解决问题 I have read the [documentation](https://clash-meta.wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

alpha-ae722bb

### Clash config

```yaml
- name: "vless-reality-grpc"
    type: vless
    server: www.lovelive-anime.jp
    port: 51878
    uuid: aaa3c18c-335b-4a41-f6bc-bf0c26225aab
    network: grpc
    tls: true
    udp: true
    flow:
    # skip-cert-verify: true
    servername: www.lovelive-anime.jp
    grpc-opts:
      grpc-service-name: "c58e8d"
    reality-opts:
      public-key: "ch1nsFSsjvQfIV3adxCqVv6OXdbePn0tzUbl3kPsgHY"
      short-id: c7f2a9c0ebbd7d47
```
```


### Clash log

```shell
[2023-04-05 14:39:01][WARNING] [TCP] dial ✈️ 墙外网站 (match RuleSet/proxy) 198.19.0.1:54506(msedge.exe) --> client.wns.windows.com:443 error: REALITY authentication failed
[2023-04-05 14:39:01][WARNING] [TCP] dial ✈️ 墙外网站 (match RuleSet/proxy) 198.19.0.1:54506(msedge.exe) --> client.wns.windows.com:443 error: REALITY authentication failed
[2023-04-05 14:39:01][WARNING] [TCP] dial ✈️ 墙外网站 (match RuleSet/proxy) 198.19.0.1:54506(msedge.exe) --> client.wns.windows.com:443 error: REALITY authentication failed
[2023-04-05 14:39:01][WARNING] [TCP] dial ✈️ 墙外网站 (match RuleSet/proxy) 198.19.0.1:54506(msedge.exe) --> client.wns.windows.com:443 error: REALITY authentication failed
```
```


### Description

授权不过，昨天的版本正常。安卓手机端也正常。

**Comment by qist** [comment]
这个是我笔记本BUG 台式机没问题。

**Comment by Andy963** [comment]
台式机也出这问题，就正常用了几天，突然就各种：REALITY authentication failed，重启服务端，客户端，刷新dns还一直这样，请楼主怎么解决的

**Comment by qist** [comment]
@Andy963  你更换一个端口试试

**Comment by chika0801** [comment]
建议这样排查

换其它目标域名，如果出现类似第1次点击链接等待时间慢（5-10秒）。感觉vps速度比换REALITY前慢，感觉vps出现类似回程线路不稳定时快时慢，突然连不上（不是连不上约3分钟自行恢复再反复）反正让你觉得就像vps线路是很差的感觉。

换非用REALITY的协议组合如VLESS Vision TLS。

或用网上交流称的自己偷自己的方式。如果故障现象消息 期待你的反馈。

**Comment by Andy963** [comment]
@qist  换过端口，换过域名，没效果，用x-ui重装了可以了

**Comment by YCarlB** [comment]
这个是什么原因导致的 ，偶尔就会这样。
