### ISSUE TITLE
[Feature] 是否能在设置中加入 "Parsers" 方便编辑负载均衡规则

### ISSUE THREAD

**Issue by althougha** [MetaCubeX/Clash.Meta#502]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://clash-meta.wiki/) 并无法自行解决问题 I have read the [documentation](https://clash-meta.wiki/) and was unable to solve the issue. 

### Description

希望更方便的添加负载均衡规则。

### Possible Solution

请加入类似CFW的Parsers以方便增加相关规则。

**Comment by Skyxim** [comment]
负载均衡规则是指什么

**Comment by althougha** [comment]
实现多线程下载宽带叠加。

**Comment by xishang0128** [comment]
@althougha clash.meta是内核,这是客户端功能,并不能提供,请直接书写配置文件

**Comment by althougha** [comment]
sorry，对不起我发错了，我应该发到Clash Verge。

**Comment by althougha** [comment]
结果发到内核中了。
