### ISSUE TITLE
[Feature] 希望加入对Script Shortcut的支持

### ISSUE THREAD

**Issue by fxchby** [MetaCubeX/Clash.Meta#510]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

我希望实现IDM下载国内文件和YOUTUBE视频的分流，我找到的方案是结合SCRIPT和PROCESS-NAME的两种类型的规则，但是Meta并不支持Script Shortcut，所有，希望后续版本可以加入这一项支持

**Comment by Skyxim** [comment]
@fxchby 暂时不会考虑支持，可使用逻辑规则实现 https://wiki.metacubex.one/config/rules/logic/

**Comment by xaotag** [comment]
希望加入对`Script Shortcut`的支持,`Script Shortcut`的可读性更好一些,当然也看大佬意愿。
```。
rules:
   - SCRIPT,UDP-Game,DIRECT

script:
shortcuts:
UDP-Game: network == 'udp' and dst_port not in [21,22,23,53,80,123,143,194,443,465,587,853,993,995,998,2052,2053,2082,2083,2086,2095,2096,5222,5228,5229,5230,8080,8443,8880,8883,8888,8889]
```
```
rules:
   - AND,((NOT,((DST-PORT,21/22/23/53/80/123/143/194/443/465/587/853/993/995/998/2052/2053/2082/2083/2086/2095/2096/5222/5228/5229/5230/8080/8443/8880/8883/8888/8889))),(NETWORK,UDP)),PROXY
```

**Comment by Se7enMuting** [comment]
> @fxchby 暂时不会考虑支持，可使用逻辑规则实现 https://wiki.metacubex.one/config/rules/logic/

这个链接目前404了，这个 逻辑规则 具体是指？

个人也比较希望可以支持 Script Shortcut

**Comment by pongfcnkl** [comment]
> > [@fxchby](https://github.com/fxchby) 暂时不会考虑支持，可使用逻辑规则实现 https://wiki.metacubex.one/config/rules/logic/
> 
> 这个链接目前404了，这个 逻辑规则 具体是指？
> 
> 个人也比较希望可以支持 Script Shortcut


https://wiki.metacubex.one/config/rules/#and-or-not

[AND & OR & NOT](https://wiki.metacubex.one/config/rules/#and-or-not)[¶](https://wiki.metacubex.one/config/rules/#and-or-not)
LOGIC_TYPE,((payload1),(payload2)),Proxy

payload1、payload2 为 规则类型和其他 payload，如：DOMAIN,google.com

逻辑规则，需要注意括号的使用
