### ISSUE TITLE
[Feature] 希望给 fake-ip-filter 添加 geosite 支持

### ISSUE THREAD

**Issue by DustinWin** [MetaCubeX/Clash.Meta#511]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

针对中国大陆用户，很多国内域名不需要走 fake-ip，否则应用或网站会出现问题。
所以希望给 fake-ip-filter 添加 geosite 支持，如：
```
fake-ip-filter:
  - 'geosite:cn'
```

**Comment by Rafeal-Ma** [comment]
支持

**Comment by juewuy** [comment]
支持

**Comment by songcheng121** [comment]
很需要，刚需啊！

**Comment by DustinWin** [comment]
> 我也需要这个功能 但是类似的问题有人提过了 #366

谢谢提醒，我似乎记得有人提过，但忘记在哪里看到的了。

**Comment by InspoOnU** [comment]
希望有这个功能，目前openwrt上用dnsmasq分流的方法实在蛋疼

**Comment by xishang0128** [comment]
如有real ip需求,请使用redir-host,fakeip filter增加域名集合在当前clash比较难以实现,且开发者没需求

**Comment by wy580477** [comment]
meta 的开发者说过好几次不会加这个功能了，自己前面套个 mosdns 完事。
