### ISSUE TITLE
[Bug] alpha内核连接xtls vision节点时 udp全部丢包

### ISSUE THREAD

**Issue by RhythmNz** [MetaCubeX/Clash.Meta#514]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

alpha-bbdc894

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
我觉得和这个无关
```

### Description

使用本项目仓库alpha-bbdc894内核以及openclash项目最新alpha内核alpha-g8e5dbc7
在openclash环境下
连接VLESS-XTLS-Vision节点即可复现
所有的udp连接均被阻断

使用Meta项目最新正式版v1.14.3
替换内核 即可直接修复

**Comment by wwqgtxx** [comment]
fixed in https://github.com/MetaCubeX/Clash.Meta/commit/31095e4a8cf72d7f3b7c822d03b37e1cab702d46
