### ISSUE TITLE
[Feature] 自动选择测速逻辑和原本clash不一样，不会在启动后立马进行

### ISSUE THREAD

**Issue by ckaak** [MetaCubeX/Clash.Meta#521]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

efcb278

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
name: 自动选择
    type: url-test
    proxies:
      - xxxxxxx
    url: 'http://cp.cloudflare.com/generate_204'
    interval: 300
```

### Description

原版clash会在启动代理后，立马开始测速，并选择延迟最新的节点。
clash meta会首次启动以后（根据interval参数）隔一段时间再测速，但是这样的程序逻辑体验上并不友好，如果第一次没有测速，clash会选择节点排序第一位的节点， 这个节点可能延迟非常高。

开发者能修改这个测速代码吗？

**Comment by Skyxim** [comment]
一直都会立马测试
只要出现节点变化，provider 就会重新触发测试
