### ISSUE TITLE
[Feature] 是否可以增加DNS解析日志？

### ISSUE THREAD

**Issue by rockxsj** [MetaCubeX/Clash.Meta#523]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

DNS是比较复杂的东西，经常会需要通过不停的修改配置来达到正确域名解析的目的，没有直观的工具。所以能否增加DNS解析日志，可以打印出来域名通过哪个DNS的策略、服务器，最终解析到了哪个IP。

**Comment by BuBuxsy** [comment]
debug里面不是有么配置多个的时候同时向上游请求。取最快返回的一个dns的结果
