### ISSUE TITLE
Wiki文档中API部分到底是能不能用呀？

### ISSUE THREAD

**Issue by photkey** [MetaCubeX/Clash.Meta#526]
Clash.Meta Docs，API：https://clash-meta.wiki/api/
文档中有API功能说明，但是测试无法访问，所以Clash.Meta的API到底是能不能用呀？

**Comment by H1JK** [comment]
Yacd-meta depends on these APIs. If these APIs are not available, you will see errors or incorrect content on Yacd-meta.

Before testing, please make sure to use the Alpha kernel.
