### ISSUE TITLE
openclash启用meta内核后xshell无法连接

### ISSUE THREAD

**Issue by onlyLTY** [MetaCubeX/Clash.Meta#53]
使用meta内核并且启用流量（域名）探测以后会导致xshell无法连上ssh。其他ssh软件正常。确认不是节点问题。xshell提示Connection closed by foreign host

**Comment by Skyxim** [comment]
https://github.com/MetaCubeX/Clash.Meta/issues/48#issuecomment-1113071006

配置端口白名单，默认是全端口，可能有些网络有影响

**Comment by MetaCubeX** [comment]
@Skyxim 添加了个port-whitelist 参数 用于添加白名单端口，为空时匹配全端口

sniffer:
  port-whitelist:
    - 443
    - 8080-9090

**Comment by onlyLTY** [comment]
> [#48 (comment)](https://github.com/MetaCubeX/Clash.Meta/issues/48#issuecomment-1113071006)
> 
> 配置端口白名单，默认是全端口，可能有些网络有影响

感谢，解决了。
