### ISSUE TITLE
能否更新下http的自定义请求头

### ISSUE THREAD

**Issue by 51rxjh** [MetaCubeX/Clash.Meta#534]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [ ]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

原http本地模式(百度直连)，更新了验证，只有3个可用的节点了，附原始模式如下

- name: BaiduProxy
    type: http
    server: 14.215.179.244
    port: 443
    tls: false
    skip-cert-verify: true
    headers:
      X-T5-Auth: "683556433"
      Connection: "Keep-Alive"
      User-Agent: "baiduboxapp"

### Possible Solution

如今新的百度直连单独加了一个请求头，用来验证X-T5-Auth，希望哪位大佬可以给http的自定义请求头增加一个新的请求头，新的模式如下

- name: BaiduProxy
    type: http
    server: 153.3.236.22
    port: 443
    tls: false
    skip-cert-verify: true
    headers:
      Host: "153.3.236.22:443"
      X-T5-Auth: "683556433"
      Connection: "Keep-Alive"
      User-Agent: "baiduboxapp"

**Comment by Filterrr** [comment]
你好，怎么抓到特定IP下的X-T5-Auth呢？
