### ISSUE TITLE
最新的beta版，在OpenWRT上内核崩溃

### ISSUE THREAD

**Issue by InspoOnU** [MetaCubeX/Clash.Meta#55]
2022-05-08 12:44:55 守护程序：检测到 Clash 内核崩溃，重启中...
	gvisor.dev/gvisor@v0.0.0-20220422224113-2cca6b79d9f4/pkg/tcpip/transport/tcp/forwarder.go:94 +0x2b8
created by gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*Forwarder).HandlePacket
	github.com/Dreamacro/clash/listener/tun/ipstack/gvisor/tcp.go:69 +0x148
github.com/Dreamacro/clash/listener/tun/ipstack/gvisor.withTCPHandler.func1.1(0x40005b8200)
	github.com/Dreamacro/clash/listener/tun/ipstack/gvisor/tcp.go:88 +0x3c
github.com/Dreamacro/clash/listener/tun/ipstack/gvisor.setSocketOptions(0x40005b8200?, {0xad49c8, 0x4000ae4000})
	gvisor.dev/gvisor@v0.0.0-20220422224113-2cca6b79d9f4/pkg/tcpip/socketops.go:338 +0x3c
gvisor.dev/gvisor/pkg/tcpip.(*SocketOptions).SetKeepAlive(0x400034bbf0?, 0x0?)
	gvisor.dev/gvisor@v0.0.0-20220422224113-2cca6b79d9f4/pkg/tcpip/transport/tcp/endpoint.go:1731 +0x30
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*endpoint).OnKeepAliveSet(0x5ac?, 0x7?)
	gvisor.dev/gvisor@v0.0.0-20220422224113-2cca6b79d9f4/pkg/tcpip/transport/tcp/connect.go:1331 +0x9c
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*endpoint).resetKeepaliveTimer(0x4000ae4000, 0x1)
	gvisor.dev/gvisor@v0.0.0-20220422224113-2cca6b79d9f4/pkg/tcpip/transport/tcp/timer.go:141 +0x2c
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*timer).enable(0x4000ae42e0, 0x702ab4?)
goroutine 5728 [running]:
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x71ee0c]
panic: runtime error: invalid memory address or nil pointer dereference

**Comment by InspoOnU** [comment]
这个报错会在运行十几秒后出现，只有beta版会出现，release版没有这个问题。

**Comment by MetaCubeX** [comment]
@InspoOnU 建议使用alpha

**Comment by InspoOnU** [comment]
> @InspoOnU 建议使用alpha

Alpha确实没有这个问题
