### ISSUE TITLE
请问mac intel芯片，下载哪个clash.meta内核呢

### ISSUE THREAD

**Issue by sooway** [MetaCubeX/Clash.Meta#558]
请问mac intel芯片，下载哪个clash.meta内核呢，pc机装的黑苹果，请大神指教

**Comment by H1JK** [comment]
https://github.com/MetaCubeX/Clash.Meta/wiki/FAQ

**Comment by H1JK** [comment]
macOS=darwin  
Intel=amd64

**Comment by Skyxim** [comment]
@sooway darwin amd64
