### ISSUE TITLE
[Bug]  用户名含有特定字符竟然报错不用补了？多次测试确认5679e8这个用户名就用不了

### ISSUE THREAD

**Issue by naishi001** [MetaCubeX/Clash.Meta#566]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.4.4

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
- name: SK-out1
  type: socks5
  server: 121.5.xx.xx
  port: 1080
  username: 5679e8
  password: 123456
  udp: true
```

### Clash log

```shell
2023-05-18 21:54:12 level=warning msg="[TCP] dial SK-out1 (match SrcIPCIDR/192.168.88.1/32) 192.168.88.1:56330 --> firebaseinstallations.googleapis.com:443 error: rej
```

### Description

用户名含有特定的字符 就 会显示错误的用户名和密码

比如我用这个sk5  用户名为5679e8  就会显示错误的用户名和密码  

sk5代理本身没有问题 ，我用多个IP测试过了，只要是5679e8 就会错误

**Comment by naishi001** [comment]
又测试了一下。用户名含有5 和e 就会报错测，

xxx.dns36.cn|1298|567e98|740354|2023-06-13
xxx.dns36.cn|1298|4504e2|773147|2023-06-12
xxx.dns36.cn|1298|935e35|840971|2023-05-27
xxx.dns36.cn|1298|5077e7|857938|2023-05-24

都是错误 有一个共同点就是含有5 和e

**Comment by Skyxim** [comment]
yaml 自动判定字符串和数字，如果字符串全是数字会被识别成数字，而e则是科学计数法。对于字符串一律使用引号
