### ISSUE TITLE
[Feature] Android 上能否支持使用profile功能？

### ISSUE THREAD

**Issue by cxyzzz** [MetaCubeX/Clash.Meta#595]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

测试配置文件中启用后，在配置文件目录创建了一个cache.db的文件，但一直是空的，日志也有警告提示，请问profile的功能有办法支持Android吗？

配置文件：
```yaml
profile:
  store-selected: true
```
核心版本：
```bash
Clash Meta alpha-2af758e android arm64 with go1.20.4 Sat Jun  3 09:46:31 UTC 2023
Use tags: with_gvisor
```

运行环境：Android 12,adb shell用户执行（无root）

日志：
```
level=warning msg="[CacheFile] can't open cache file: function not implemented"
```

**Comment by xishang0128** [comment]
@cxyzzz 请确保运行内核的用户总有工作目录/cache.db文件的读写权限

**Comment by cxyzzz** [comment]
> @cxyzzz 请确保运行内核的用户总有工作目录/cache.db文件的读写权限

这个不太清楚， 但如果把cache.db文件删掉后，重启clash，会自己在配置目录创建cache.db，这应该是有读写权限吧？我是借助的Shizuku使用`shell`用户，在`/data/local/tmp`运行的，这个目录shell用户也拥有读写权限。（`drwxrwx--x 6 shell shell  /data/local/tmp`）

**Comment by Xinyu-Wu-0000** [comment]
我使用[图形客户端](https://github.com/MetaCubeX/ClashMetaForAndroid)是可以的

**Comment by cxyzzz** [comment]
root后测试能正常生成了，看来是SELinux拦截shell用户创建缓存文件的操作
