### ISSUE TITLE
[Bug] 同一个节点，meta和WireGuard客户端速度有明显差距

### ISSUE THREAD

**Issue by 111kb** [MetaCubeX/Clash.Meta#598]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

v1.14.5

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
- {name: wgcf, type: wireguard, server: 162.159.195.145, port: 1180, ip: 172.16.0.2, ipv6: 2606:4700:110:821e:3e-----, public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=, private-key: eFGD9dlNh/MaRwVtYn4ND---------, udp: true, reserved: [105,24,236], remote-dns-resolve: true, dns: [1.1.1.1, 8.8.8.8]}
```

### Description

同一个节点信息，WireGuard客户端油管能跑2w，meta只能跑5k

**Comment by othelloYu** [comment]
我感觉我这边也有这种问题，我使用的是openwrt-openclash使用
[Meta] 最新内核版本 alpha-g6b1a438，我这边甚至油管1k都达不到，而且我这边需要把meta设置的探测（嗅探）纯 IP 连接关闭才可以，难道是我设置的相关问题嘛？
- name: "WARP"
  type: wireguard
  server: 162.159.192.229
  port: 854
  udp: true
  ip: 172.16.0.2
  #ipv6: 2606:4700:110:8475:db7f:1c2e:9435:bdf6
  dns: [1.1.1.1]
  mtu: 1280
  remote-dns-resolve: true
  public-key: 
  private-key:

**Comment by H1JK** [comment]
@othelloYu The version `g6b1a438` marked as "latest" by OpenClash is actually NOT the latest Alpha, and the version tag is even not exist in our repository. I have talked about that with @wwqgtxx days before.

For OpenClash users, if you want to use the latest Alpha kernel, switch to Yacd-meta in settings and use "Update Alpha" feature in Yacd.

**Comment by rsgdn** [comment]
> 我感觉我这边也有这种问题，我使用的是openwrt-openclash使用 [Meta] 最新内核版本 alpha-g6b1a438，我这边甚至油管1k都达不到，而且我这边需要把meta设置的探测（嗅探）纯 IP 连接关闭才可以，难道是我设置的相关问题嘛？
> 
> * name: "WARP"
>   type: wireguard
>   server: 162.159.192.229
>   port: 854
>   udp: true
>   ip: 172.16.0.2
>   #ipv6: 2606:4700:110:8475:db7f:1c2e:9435:bdf6
>   dns: [1.1.1.1]
>   mtu: 1280
>   remote-dns-resolve: true
>   public-key:
>   private-key:

同样软路由，如果开着探测(嗅探)纯IP连接的话域名嗅探功能会失效，试过几个版本都这样。不知道算是openclash那边问题还是meta这边问题
