### ISSUE TITLE
[Bug] rule-providers文件不完整，核心也能启动

### ISSUE THREAD

**Issue by Rakau** [MetaCubeX/Clash.Meta#599]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

v1.14.5

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
RT
```

### Description

由于网络问题或者地址问题导致无法下载文件时，但核心依旧会启动，会导致侧漏

**Comment by ArchGuyWu** [comment]
@Rakau rule本身就支持延迟加载，这是预期行为

**Comment by xishang0128** [comment]
@Rakau meta的provider下载失败会跳过,使其可以经过inner(clash内部,匹配规则)下载

**Comment by Skyxim** [comment]
预期设计，下载可不需要下载和解析成功完成，但在本地存在文件会直接读取这是可以保证分流的

**Comment by Skyxim** [comment]
@izhangxm provider 在 meta 中就不是必须项，所以可以在不下载成功也可以启动内核这里没问题。但是下载失败不会导致原有规则被清理啊，有具体描述么

**Comment by Skyxim** [comment]
> @Skyxim 看看这个演示
> 
>  iShot_2023-07-16_10.26.32.mp4

你这个 http 服务器停止后，访问错误是什么，返回一个错误，还是直接 TCP 连接超时

**Comment by Rakau** [comment]
> @Skyxim  下面可能是bug的反馈。
> 
> 版本：1.15.0
> 平台：Openclash和ClashX.meta
> 问题：规则集下载失败时 规则集被清空 导致分流失效（更要命的情况是局域网分流规则也是远程规则集）
> 预期行为：下载失败时，应当继续使用未更新之前的规则集
> 备注：其他版本未测试，不清楚是否有这种情况，不清楚是gui问题还是核心问题。
> 
> 
> 
> 
> 
> 
> 

确实会清零0，当时我忘记提这件事了。

**Comment by Skyxim** [comment]
> 注意：域名为马赛克域名
> 
> ## 第一种情况
> ```
> curl -v https://cat.example.com/api/rule/bm7/Clash/OpenAI/OpenAI.yaml
> *   Trying 104.21.65.237:443...
> * Connected to cat.example.com (104.21.65.237) port 443 (#0)
> * ALPN: offers h2,http/1.1
> * (304) (OUT), TLS handshake, Client hello (1):
> *  CAfile: /etc/ssl/cert.pem
> *  CApath: none
> * (304) (IN), TLS handshake, Server hello (2):
> * (304) (IN), TLS handshake, Unknown (8):
> * (304) (IN), TLS handshake, Certificate (11):
> * (304) (IN), TLS handshake, CERT verify (15):
> * (304) (IN), TLS handshake, Finished (20):
> * (304) (OUT), TLS handshake, Finished (20):
> * SSL connection using TLSv1.3 / AEAD-CHACHA20-POLY1305-SHA256
> * ALPN: server accepted h2
> * Server certificate:
> *  subject: CN=example.com
> *  start date: Jun 25 16:48:25 2023 GMT
> *  expire date: Sep 23 16:48:24 2023 GMT
> *  subjectAltName: host "cat.example.com" matched cert's "*.example.com"
> *  issuer: C=US; O=Let's Encrypt; CN=E1
> *  SSL certificate verify ok.
> * using HTTP/2
> * h2 [:method: GET]
> * h2 [:scheme: https]
> * h2 [:authority: cat.example.com]
> * h2 [:path: /api/rule/bm7/Clash/OpenAI/OpenAI.yaml]
> * h2 [user-agent: curl/8.1.2]
> * h2 [accept: */*]
> * Using Stream ID: 1 (easy handle 0x15d00c600)
> > GET /api/rule/bm7/Clash/OpenAI/OpenAI.yaml HTTP/2
> > Host: cat.example.com
> > User-Agent: curl/8.1.2
> > Accept: */*
> > 
> < HTTP/2 502 
> < date: Sun, 16 Jul 2023 02:54:47 GMT
> < content-type: text/plain; charset=utf-8
> < content-length: 132
> < x-content-type-options: nosniff
> < cf-cache-status: DYNAMIC
> < report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=XUdnXg5ZDQW%2B4WNAbEJ63cEnPOs%2FEatIRjvC3cCIeGf%2BtFfqYyHWc9lEeQsfW4OvsdaLOMW5bYoOCzPSHOIMn%2FTdLobz8yAOkWZzU%2BnsPD5V4POx4ose9OFMQ3ec0okmAm%2FF"}],"group":"cf-nel","max_age":604800}
> < nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
> < server: cloudflare
> < cf-ray: 7e76f66b38129438-SJC
> < alt-svc: h3=":443"; ma=86400
> < 
> 502 Bad Gateway
> Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared
> * Connection #0 to host cat.example.com left intact
> ```
> 
> <img alt="image" width="968" src="https://user-images.githubusercontent.com/16874796/253782718-f50ed48e-d650-4323-b8ca-de7790629f40.png">
> ## 第二种情况
> ```
>     ~  curl -v https://cat.example.com/api/rule/bm7/Clash/OpenAI/OpenAI.yaml                                                              ✔  10:54:47  
> *   Trying 104.21.65.237:443...
> * Connected to cat.example.com (104.21.65.237) port 443 (#0)
> * ALPN: offers h2,http/1.1
> * (304) (OUT), TLS handshake, Client hello (1):
> *  CAfile: /etc/ssl/cert.pem
> *  CApath: none
> * (304) (IN), TLS handshake, Server hello (2):
> * (304) (IN), TLS handshake, Unknown (8):
> * (304) (IN), TLS handshake, Certificate (11):
> * (304) (IN), TLS handshake, CERT verify (15):
> * (304) (IN), TLS handshake, Finished (20):
> * (304) (OUT), TLS handshake, Finished (20):
> * SSL connection using TLSv1.3 / AEAD-CHACHA20-POLY1305-SHA256
> * ALPN: server accepted h2
> * Server certificate:
> *  subject: CN=example.com
> *  start date: Jun 25 16:48:25 2023 GMT
> *  expire date: Sep 23 16:48:24 2023 GMT
> *  subjectAltName: host "cat.example.com" matched cert's "*.example.com"
> *  issuer: C=US; O=Let's Encrypt; CN=E1
> *  SSL certificate verify ok.
> * using HTTP/2
> * h2 [:method: GET]
> * h2 [:scheme: https]
> * h2 [:authority: cat.example.com]
> * h2 [:path: /api/rule/bm7/Clash/OpenAI/OpenAI.yaml]
> * h2 [user-agent: curl/8.1.2]
> * h2 [accept: */*]
> * Using Stream ID: 1 (easy handle 0x130011e00)
> > GET /api/rule/bm7/Clash/OpenAI/OpenAI.yaml HTTP/2
> > Host: cat.example.com
> > User-Agent: curl/8.1.2
> > Accept: */*
> > 
> < HTTP/2 530 
> < date: Sun, 16 Jul 2023 02:57:24 GMT
> < content-type: text/html; charset=UTF-8
> < content-length: 6183
> < report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=SG99EME41HTl%2F2GgjosLvIB73mXsfoQc0psQVg0NZEvd%2Bnhr4fIFo9UuE9oD3KzeztPP7J3giYsCCjQfr7bwEEcW1MFxXcQSxmdQI212GeZmKWZAfEZ0YS6aESZiRKhzhDge"}],"group":"cf-nel","max_age":604800}
> < nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
> < x-frame-options: SAMEORIGIN
> < referrer-policy: same-origin
> < cache-control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
> < expires: Thu, 01 Jan 1970 00:00:01 GMT
> < server: cloudflare
> < cf-ray: 7e76fa41ebdb2516-SJC
> < alt-svc: h3=":443"; ma=86400
> < 
> <!DOCTYPE html>
> 
> 
> 
>  <html class="no-js" lang="en-US"> 
> <head>
> <title>Argo Tunnel error | cat.example.com | Cloudflare</title>
> <meta charset="UTF-8" />
> <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
> <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
> <meta name="robots" content="noindex, nofollow" />
> <meta name="viewport" content="width=device-width,initial-scale=1" />
> <link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/main.css" />
> 
> 
> <script>
> (function(){if(document.addEventListener&&window.XMLHttpRequest&&JSON&&JSON.stringify){var e=function(a){var c=document.getElementById("error-feedback-survey"),d=document.getElementById("error-feedback-success"),b=new XMLHttpRequest;a={event:"feedback clicked",properties:{errorCode:1033,helpful:a,version:1}};b.open("POST","https://sparrow.cloudflare.com/api/v1/event");b.setRequestHeader("Content-Type","application/json");b.setRequestHeader("Sparrow-Source-Key","c771f0e4b54944bebf4261d44bd79a1e");
> b.send(JSON.stringify(a));c.classList.add("feedback-hidden");d.classList.remove("feedback-hidden")};document.addEventListener("DOMContentLoaded",function(){var a=document.getElementById("error-feedback"),c=document.getElementById("feedback-button-yes"),d=document.getElementById("feedback-button-no");"classList"in a&&(a.classList.remove("feedback-hidden"),c.addEventListener("click",function(){e(!0)}),d.addEventListener("click",function(){e(!1)}))})}})();
> </script>
> 
> <script defer src="https://performance.radar.cloudflare.com/beacon.js"></script>
> </head>
> <body>
>   <div id="cf-wrapper">
>     <div class="cf-alert cf-alert-error cf-cookie-error hidden" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
>     <div id="cf-error-details" class="p-0">
>       <header class="mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-15 antialiased">
>          <h1 class="inline-block md:block mr-2 md:mb-2 font-light text-60 md:text-3xl text-black-dark leading-tight">
>            <span data-translate="error">Error</span>
>            <span>1033</span>
>          </h1>
>          <span class="inline-block md:block heading-ray-id font-mono text-15 lg:text-sm lg:leading-relaxed">Ray ID: 7e76fa41ebdb2516 &bull;</span>
>          <span class="inline-block md:block heading-ray-id font-mono text-15 lg:text-sm lg:leading-relaxed">2023-07-16 02:57:24 UTC</span>
>         <h2 class="text-gray-600 leading-1.3 text-3xl lg:text-2xl font-light">Argo Tunnel error</h2>
>       </header>
> 
>       <section class="w-240 lg:w-full mx-auto mb-8 lg:px-8">
>           <div id="what-happened-section" class="w-1/2 md:w-full">
>             <h2 class="text-3xl leading-tight font-normal mb-4 text-black-dark antialiased" data-translate="what_happened">What happened?</h2>
>             <p>You've requested a page on a website (cat.example.com) that is on the <a href="https://www.cloudflare.com/5xx-error-landing/" target="_blank">Cloudflare</a> network. The host (cat.example.com) is configured as an Argo Tunnel, and Cloudflare is currently unable to resolve it.
>             
>           </div>
> 
>           
>           <div id="resolution-copy-section" class="w-1/2 mt-6 text-15 leading-normal">
>             <h2 class="text-3xl leading-tight font-normal mb-4 text-black-dark antialiased" data-translate="what_can_i_do">What can I do?</h2>
>             <p><strong>If you are a visitor of this website:</strong><br />Please try again in a few minutes.</p><p><strong>If you are the owner of this website:</strong><br />Ensure that cloudflared is running and can reach the network. You may wish to enable <a rel="noopener noreferrer" href="https://developers.cloudflare.com/argo-tunnel/reference/load-balancing/">load balancing</a> for your tunnel.</p>
>           </div>
>           
>       </section>
> 
>       <div class="feedback-hidden py-8 text-center" id="error-feedback">
>     <div id="error-feedback-survey" class="footer-line-wrapper">
>         Was this page helpful?
>         <button class="border border-solid bg-white cf-button cursor-pointer ml-4 px-4 py-2 rounded" id="feedback-button-yes" type="button">Yes</button>
>         <button class="border border-solid bg-white cf-button cursor-pointer ml-4 px-4 py-2 rounded" id="feedback-button-no" type="button">No</button>
>     </div>
>     <div class="feedback-success feedback-hidden" id="error-feedback-success">
>         Thank you for your feedback!
>     </div>
> </div>
> 
> 
>       <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
>   <p class="text-13">
>     <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">7e76fa41ebdb2516</strong></span>
>     <span class="cf-footer-separator sm:hidden">&bull;</span>
>     <span id="cf-footer-item-ip" class="cf-footer-item hidden sm:block sm:mb-1">
>       Your IP:
>       <button type="button" id="cf-footer-ip-reveal" class="cf-footer-ip-reveal-btn">Click to reveal</button>
>       <span class="hidden" id="cf-footer-ip">123.112.11.206</span>
>       <span class="cf-footer-separator sm:hidden">&bull;</span>
>     </span>
>     <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>
>     
>   </p>
>   <script>(function(){function d(){var b=a.getElementById("cf-footer-item-ip"),c=a.getElementById("cf-footer-ip-reveal");b&&"classList"in b&&(b.classList.remove("hidden"),c.addEventListener("click",function(){c.classList.add("hidden");a.getElementById("cf-footer-ip").classList.remove("hidden")}))}var a=document;document.addEventListener&&a.addEventListener("DOMContentLoaded",d)})();</script>
> </div>
> 
> 
>     </div>
>   </div>
> 
>   <script>
>   window._cf_translation = {};
>   
>   
> </script>
> 
> </body>
> </html>
> * Connection #0 to host cat.example.com left intact
> ```
> 
> <img alt="image" width="915" src="https://user-images.githubusercontent.com/16874796/253782770-8e427cf1-70bb-4d71-9a15-45db6e366e06.png">

果然是这个
https://github.com/MetaCubeX/Clash.Meta/commit/a181e358658fa57619e9c00f81c083776fc0a3f3
试试

**Comment by Skyxim** [comment]
@izhangxm 失误，判断写错了
