### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by toyo2333** [MetaCubeX/Clash.Meta#605]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

meta速度明显比premium内核差

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
用的是机场的订阅。应该都是ss的，不知道怎么看
```

### Description

从verge那边过来的，切换meta后内核体验巨差

1，windows11，稳定版
2，用的是机场的订阅，应该都是ss
3，之前在CFW，ClashX，iOS上都稳定高速使用，装verge默认速度也不错，切换meta后，就卡了
4，页面刷新慢，youtube慢，刚刚在这里提交issus后直接断网了，什么都没保存，这里再写一遍
5，切回premium正常

**Comment by xishang0128** [comment]
@toyo2333 no log no bug
体验问题可能是你配置错误导致的,请贴出去敏配置以及debug log

**Comment by sleeeeeeepa** [comment]
确实有这个问题，同样的订阅过来 meta慢很多很多我的配置文件如下
mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
external-controller: '127.0.0.1:9090'
dns:
    enable: true
    ipv6: false
    listen: '0.0.0.0:1053'
    enhanced-mode: fake-ip
    fake-ip-range: 198.18.0.1/16
    default-nameserver: [180.76.76.76, 223.5.5.5, 119.29.29.29]
    nameserver: ['https://doh.pub/dns-query', 'https://dns.alidns.com/dns-query']
    fallback: ['tls://1.1.1.1:853', 'tls://1.0.0.1:853', '101.6.6.6:5353']
proxies:

proxy-groups:
    
rule-providers:
    icloud: { type: http, behavior: domain, url: 'http://xxx.xxx.xxx.xxx:13335/Loyalsoldier/clash-rules/release/icloud.txt', path: ./ruleset/icloud.yaml, interval: 86400 }
    apple: { type: http, behavior: domain, url: 'http://xxx.xxx.xxx.xxx:13335/Loyalsoldier/clash-rules/release/apple.txt', path: ./ruleset/apple.yaml, interval: 86400 }
    proxy: { type: http, behavior: domain, url: 'http://xxx.xxx.xxx.xxx:13335/Loyalsoldier/clash-rules/release/proxy.txt', path: ./ruleset/proxy.yaml, interval: 86400 }
    direct: { type: http, behavior: domain, url: 'http://xxx.xxx.xxx.xxx:13335/Loyalsoldier/clash-rules/release/direct.txt', path: ./ruleset/direct.yaml, interval: 86400 }
    private: { type: http, behavior: domain, url: 'http://xxx.xxx.xxx.xxx:13335/Loyalsoldier/clash-rules/release/private.txt', path: ./ruleset/private.yaml, interval: 86400 }
    gfw: { type: http, behavior: domain, url: 'http://xxx.xxx.xxx.xxx:13335/Loyalsoldier/clash-rules/release/gfw.txt', path: ./ruleset/gfw.yaml, interval: 86400 }
    greatfire: { type: http, behavior: domain, url: 'http://xxx.xxx.xxx.xxx:13335/Loyalsoldier/clash-rules/release/greatfire.txt', path: ./ruleset/greatfire.yaml, interval: 86400 }
    tld-not-cn: { type: http, behavior: domain, url: 'http://xxx.xxx.xxx.xxx:13335/Loyalsoldier/clash-rules/release/tld-not-cn.txt', path: ./ruleset/tld-not-cn.yaml, interval: 86400 }
    telegramcidr: { type: http, behavior: ipcidr, url: 'http://xxx.xxx.xxx.xxx:13335/Loyalsoldier/clash-rules/release/telegramcidr.txt', path: ./ruleset/telegramcidr.yaml, interval: 86400 }
    cncidr: { type: http, behavior: ipcidr, url: 'http://xxx.xxx.xxx.xxx:13335/Loyalsoldier/clash-rules/release/cncidr.txt', path: ./ruleset/cncidr.yaml, interval: 86400 }
    lancidr: { type: http, behavior: ipcidr, url: 'http://xxx.xxx.xxx.xxx:13335/Loyalsoldier/clash-rules/release/lancidr.txt', path: ./ruleset/lancidr.yaml, interval: 86400 }
    applications: { type: http, behavior: classical, url: 'http://xxx.xxx.xxx.xxx:13335/Loyalsoldier/clash-rules/release/applications.txt', path: ./ruleset/applications.yaml, interval: 86400 }
rules:
    - 'DOMAIN-SUFFIX,vps.hosting,DIRECT'
    - 'DOMAIN-SUFFIX,pyproxy.com,myip'
    - 'RULE-SET,applications,DIRECT'
    - 'DOMAIN,clash.razord.top,DIRECT'
    - 'DOMAIN,yacd.haishan.me,DIRECT'
    - 'RULE-SET,private,DIRECT'
    - 'RULE-SET,icloud,DIRECT'
    - 'RULE-SET,apple,DIRECT'
    - 'RULE-SET,proxy,myip'
    - 'RULE-SET,direct,DIRECT'
    - 'RULE-SET,lancidr,DIRECT'
    - 'RULE-SET,cncidr,DIRECT'
    - 'RULE-SET,telegramcidr,myip'
    - 'GEOIP,LAN,DIRECT'
    - 'GEOIP,CN,DIRECT'
    - 'DOMAIN-SUFFIX,services.googleapis.cn,myip'
    - 'DOMAIN-SUFFIX,xn--ngstr-lra8j.com,DIRECT'
    - 'DOMAIN-SUFFIX,sephora.com,myip'
    - 'DOMAIN-SUFFIX,ulta.com,myip'
    - 'DOMAIN-SUFFIX,nordstrom.com,myip'
    - 'DOMAIN-SUFFIX,macys.com,myip'
    - 'DOMAIN-SUFFIX,saksfifthavenue.com,myip'
    - 'DOMAIN-SUFFIX,neimanmarcus.com,myip'
    - 'DOMAIN-SUFFIX,bergdorfgoodman.com,myip'
    - 'DOMAIN-SUFFIX,barneys.com,myip'
    - 'DOMAIN-SUFFIX,bloomingdales.com,myip'
    - 'DOMAIN-SUFFIX,saks.com,myip'
    - 'DOMAIN-SUFFIX,cosbar.com,myip'
    - 'DOMAIN-SUFFIX,bluemercury.com,myip'
    - 'DOMAIN-SUFFIX,dermstore.com,myip'
    - 'DOMAIN-SUFFIX,revolve.com,myip'
    - 'DOMAIN-SUFFIX,net-a-porter.com,myip'
    - 'DOMAIN-SUFFIX,shopbop.com,myip'
    - 'DOMAIN-SUFFIX,beautylish.com,myip'
    - 'DOMAIN-SUFFIX,cultbeauty.com,myip'
    - 'DOMAIN-SUFFIX,lookfantastic.com,myip'
    - 'DOMAIN-SUFFIX,strawberrynet.com,myip'
    - 'DOMAIN-SUFFIX,harveynichols.com,myip'
    - 'DOMAIN-SUFFIX,debenhams.com,myip'
    - 'DOMAIN-SUFFIX,feelunique.com,myip'
    - 'DOMAIN-SUFFIX,spacenk.com,myip'
    - 'DOMAIN-SUFFIX,blissworld.com,myip'
    - 'DOMAIN-SUFFIX,beautybay.com,myip'
    - 'DOMAIN-SUFFIX,loccitane.com,myip'
    - 'DOMAIN-SUFFIX,us.caudalie.com,myip'
    - 'DOMAIN-SUFFIX,skinceuticals.com,myip'
    - 'DOMAIN-SUFFIX,kiehls.com,myip'
    - 'DOMAIN-SUFFIX,bareminerals.com,myip'
    - 'DOMAIN-SUFFIX,bobbibrowncosmetics.com,myip'
    - 'DOMAIN-SUFFIX,clinique.com,myip'
    - 'DOMAIN-SUFFIX,esteelauder.com,myip'
    - 'DOMAIN-SUFFIX,lauramercier.com,myip'
    - 'DOMAIN-SUFFIX,origins.com,myip'
    - 'DOMAIN-SUFFIX,smashbox.com,myip'
    - 'DOMAIN-SUFFIX,benefitcosmetics.com,myip'
    - 'DOMAIN-SUFFIX,urbandecay.com,myip'
    - 'DOMAIN-SUFFIX,shuuemura-usa.com,myip'
    - 'DOMAIN-SUFFIX,yslbeautyus.com,myip'
    - 'DOMAIN-SUFFIX,armani-beauty.com,myip'
    - 'DOMAIN-SUFFIX,clarinsusa.com,myip'
    - 'DOMAIN-SUFFIX,dior.com,myip'
    - 'DOMAIN-SUFFIX,giorgioarmanibeauty-usa.com,myip'
    - 'DOMAIN-SUFFIX,givenchybeauty.com,myip'
    - 'DOMAIN-SUFFIX,guerlain.com,myip'
    - 'DOMAIN-SUFFIX,hermes.com,myip'
    - 'DOMAIN-SUFFIX,lancome-usa.com,myip'
    - 'DOMAIN-SUFFIX,sk-ii.com,myip'
    - 'DOMAIN-SUFFIX,ysl.com,myip'
    - 'DOMAIN-SUFFIX,us.christianlouboutin.com,myip'
    - 'DOMAIN-SUFFIX,jomalone.com,myip'
    - 'DOMAIN-SUFFIX,aerosoles.com,myip'
    - 'DOMAIN-SUFFIX,amazon.com,myip'
    - 'DOMAIN-SUFFIX,anntaylor.com,myip'
    - 'DOMAIN-SUFFIX,anthropologie.com,myip'
    - 'DOMAIN-SUFFIX,armaniexchange.com,myip'
    - 'DOMAIN-SUFFIX,asos.com,myip'
    - 'DOMAIN-SUFFIX,athleta.com,myip'
    - 'DOMAIN-SUFFIX,bathandbodyworks.com,myip'
    - 'DOMAIN-SUFFIX,beautylish.com,myip'
    - 'DOMAIN-SUFFIX,beauty.com,myip'
    - 'DOMAIN-SUFFIX,beautyhabit.com,myip'
    - 'DOMAIN-SUFFIX,bergdorfgoodman.com,myip'
    - 'DOMAIN-SUFFIX,bhcosmetics.com,myip'
    - 'DOMAIN-SUFFIX,blissworld.com,myip'
    - 'DOMAIN-SUFFIX,bloomingdales.com,myip'
    - 'DOMAIN-SUFFIX,bluefly.com,myip'
    - 'DOMAIN-SUFFIX,bobbi.com,myip'
    - 'DOMAIN-SUFFIX,bonniehunt.com,myip'
    - 'DOMAIN-SUFFIX,brandymelvilleusa.com,myip'
    - 'DOMAIN-SUFFIX,bumbleandbumble.com,myip'
    - 'DOMAIN-SUFFIX,caudalie.com,myip'
    - 'DOMAIN-SUFFIX,chanel.com,myip'
    - 'DOMAIN-SUFFIX,clinique.com,myip'
    - 'DOMAIN-SUFFIX,coastal.com,myip'
    - 'DOMAIN-SUFFIX,cosme-de.com,myip'
    - 'DOMAIN-SUFFIX,cosmeticsnow.com,myip'
    - 'DOMAIN-SUFFIX,cvs.com,myip'
    - 'DOMAIN-SUFFIX,cvsphoto.com,myip'
    - 'DOMAIN-SUFFIX,dermstore.com,myip'
    - 'DOMAIN-SUFFIX,diptyqueparis.com,myip'
    - 'DOMAIN-SUFFIX,dolcegabbana.com,myip'
    - 'DOMAIN-SUFFIX,dsw.com,myip'
    - 'DOMAIN-SUFFIX,elfcosmetics.com,myip'
    - 'DOMAIN-SUFFIX,esteelauder.com,myip'
    - 'DOMAIN-SUFFIX,eyeslipsface.com,myip'
    - 'DOMAIN-SUFFIX,feelunique.com,myip'
    - 'DOMAIN-SUFFIX,firstaidbeauty.com,myip'
    - 'DOMAIN-SUFFIX,forever21.com,myip'
    - 'DOMAIN-SUFFIX,fragrancenet.com,myip'
    - 'DOMAIN-SUFFIX,fragranceX.com,myip'
    - 'DOMAIN-SUFFIX,freepeople.com,myip'
    - 'DOMAIN-SUFFIX,gap.com,myip'
    - 'DOMAIN-SUFFIX,giorgioarmanibeauty-usa.com,myip'
    - 'DOMAIN-SUFFIX,glossier.com,myip'
    - 'DOMAIN-SUFFIX,harryjosh.com,myip'
    - 'DOMAIN-SUFFIX,herbivorebotanicals.com,myip'
    - 'DOMAIN-SUFFIX,hudabeauty.com,myip'
    - 'DOMAIN-SUFFIX,iloveglasses.com,myip'
    - 'DOMAIN-SUFFIX,iman-cosmetics.com,myip'
    - 'DOMAIN-SUFFIX,inglotusa.com,myip'
    - 'DOMAIN-SUFFIX,itsugar.com,myip'
    - 'DOMAIN-SUFFIX,jeffreestarcosmetics.com,myip'
    - 'DOMAIN-SUFFIX,jomalone.com,myip'
    - 'DOMAIN-SUFFIX,juicycouture.com,myip'
    - 'DOMAIN-SUFFIX,katespade.com,myip'
    - 'DOMAIN-SUFFIX,kiehls.com,myip'
    - 'DOMAIN-SUFFIX,lancome-usa.com,myip'
    - 'DOMAIN-SUFFIX,loccitane.com,myip'
    - 'DOMAIN-SUFFIX,lorealparisusa.com,myip'
    - 'DOMAIN-SUFFIX,abercrombie.com,myip'
    - 'DOMAIN-SUFFIX,allbirds.com,myip'
    - 'DOMAIN-SUFFIX,coach.com,myip'
    - 'DOMAIN-SUFFIX,coachoutlet.com,myip'
    - 'DOMAIN-SUFFIX,colehaan.com,myip'
    - 'DOMAIN-SUFFIX,dooney.com,myip'
    - 'DOMAIN-SUFFIX,everlane.com,myip'
    - 'DOMAIN-SUFFIX,faurelepage.com,myip'
    - 'DOMAIN-SUFFIX,fossil.com,myip'
    - 'DOMAIN-SUFFIX,goyard.com,myip'
    - 'DOMAIN-SUFFIX,groupon.com,myip'
    - 'DOMAIN-SUFFIX,grouponcdn.com,myip'
    - 'DOMAIN-SUFFIX,gucci.com,myip'
    - 'DOMAIN-SUFFIX,hermes.com,myip'
    - 'DOMAIN-SUFFIX,herschel.com,myip'
    - 'DOMAIN-SUFFIX,katespade.com,myip'
    - 'DOMAIN-SUFFIX,kennethcole.com,myip'
    - 'DOMAIN-SUFFIX,lacoste.com,myip'
    - 'DOMAIN-SUFFIX,leatherology.com,myip'
    - 'DOMAIN-SUFFIX,lesportsac.com,myip'
    - 'DOMAIN-SUFFIX,littleunicorn.com,myip'
    - 'DOMAIN-SUFFIX,livingproof.com,myip'
    - 'DOMAIN-SUFFIX,louisvuitton.com,myip'
    - 'DOMAIN-SUFFIX,maisonvalentino.com,myip'
    - 'DOMAIN-SUFFIX,mansurgavriel.com,myip'
    - 'DOMAIN-SUFFIX,michaelkors.com,myip'
    - 'DOMAIN-SUFFIX,montblanc.com,myip'
    - 'DOMAIN-SUFFIX,mulberry.com,myip'
    - 'DOMAIN-SUFFIX,nordstrom.com,myip'
    - 'DOMAIN-SUFFIX,nordstromrack.com,myip'
    - 'DOMAIN-SUFFIX,pangaia.com,myip'
    - 'DOMAIN-SUFFIX,parkerny.com,myip'
    - 'DOMAIN-SUFFIX,prada.com,myip'
    - 'DOMAIN-SUFFIX,rag-bone.com,myip'
    - 'DOMAIN-SUFFIX,rebeccaminkoff.com,myip'
    - 'DOMAIN-SUFFIX,rothys.com,myip'
    - 'DOMAIN-SUFFIX,saksoff5th.com,myip'
    - 'DOMAIN-SUFFIX,senreve.com,myip'
    - 'DOMAIN-SUFFIX,soludos.com,myip'
    - 'DOMAIN-SUFFIX,sperry.com,myip'
    - 'DOMAIN-SUFFIX,stuartweitzman.com,myip'
    - 'DOMAIN-SUFFIX,telfar.net,myip'
    - 'DOMAIN-SUFFIX,thredup.com,myip'
    - 'DOMAIN-SUFFIX,tommy.com,myip'
    - 'DOMAIN-SUFFIX,tommybahama.com,myip'
    - 'DOMAIN-SUFFIX,toryburch.com,myip'
    - 'DOMAIN-SUFFIX,tous.com,myip'
    - 'DOMAIN-SUFFIX,trunkclub.com,myip'
    - 'DOMAIN-SUFFIX,verabradley.com,myip'
    - 'DOMAIN-SUFFIX,vincecamuto.com,myip'
    - 'DOMAIN-SUFFIX,vineyardvines.com,myip'
    - 'DOMAIN-SUFFIX,yoox.com,myip'
    - 'DOMAIN-SUFFIX,yoogiscloset.com,myip'
    - 'DOMAIN-SUFFIX,zara.com,myip'
    - 'DOMAIN-SUFFIX,zumiez.com,myip'
    - 'DOMAIN-SUFFIX,esteelauder.com,myip'
    - 'DOMAIN-SUFFIX,clinique.com,myip'
    - 'DOMAIN-SUFFIX,maccosmetics.com,myip'
    - 'DOMAIN-SUFFIX,bobbibrowncosmetics.com,myip'
    - 'DOMAIN-SUFFIX,origins.com,myip'
    - 'DOMAIN-SUFFIX,aveda.com,myip'
    - 'DOMAIN-SUFFIX,kiehls.com,myip'
    - 'DOMAIN-SUFFIX,smashbox.com,myip'
    - 'DOMAIN-SUFFIX,benefitcosmetics.com,myip'
    - 'DOMAIN-SUFFIX,toofaced.com,myip'
    - 'DOMAIN-SUFFIX,lauramercier.com,myip'
    - 'DOMAIN-SUFFIX,bareminerals.com,myip'
    - 'DOMAIN-SUFFIX,nyxcosmetics.com,myip'
    - 'DOMAIN-SUFFIX,stilacosmetics.com,myip'
    - 'DOMAIN-SUFFIX,urbandecay.com,myip'
    - 'DOMAIN-SUFFIX,narscosmetics.com,myip'
    - 'DOMAIN-SUFFIX,anastasiabeverlyhills.com,myip'
    - 'DOMAIN-SUFFIX,tartecosmetics.com,myip'
    - 'DOMAIN-SUFFIX,katvondbeauty.com,myip'
    - 'DOMAIN-SUFFIX,colourpop.com,myip'
    - 'DOMAIN-SUFFIX,elfcosmetics.com,myip'
    - 'DOMAIN-SUFFIX,juviasplace.com,myip'
    - 'DOMAIN-SUFFIX,morphe.com,myip'
    - 'DOMAIN-SUFFIX,patmcgrath.com,myip'
    - 'DOMAIN-SUFFIX,jeffreestarcosmetics.com,myip'
    - 'DOMAIN-SUFFIX,hudabeauty.com,myip'
    - 'DOMAIN-SUFFIX,fentybeauty.com,myip'
    - 'DOMAIN-SUFFIX,glossier.com,myip'
    - 'DOMAIN-SUFFIX,limecrime.com,myip'
    - 'DOMAIN-SUFFIX,beautylish.com,myip'
    - 'DOMAIN-SUFFIX,sephora.com,myip'
    - 'DOMAIN-SUFFIX,ulta.com,myip'
    - 'MATCH,myip'

**Comment by sleeeeeeepa** [comment]
日志中出现大量warning
![image](https://github.com/MetaCubeX/Clash.Meta/assets/26105843/481f9d5b-2a4f-4a57-8bf8-21c5ae5c498f)

**Comment by toyo2333** [comment]
> @toyo2333 no log no bug 体验问题可能是你配置错误导致的,请贴出去敏配置以及debug log

就是机场的后台面板提供的订阅连接，导入到CFW里没有任何问题，导入到verge的默认内核下。没问题，切换到meta就这各种缓慢卡顿。

机场是Tag，目前品质最好的机场之一。

你们自己搞来测试把。

不提供日志了，你们爱改不改。垃圾内核。

**Comment by Skyxim** [comment]
看不懂提示么，告诉你了，DNS 查询超时

**Comment by Skyxim** [comment]
> 日志中出现大量warning ![image](https://user-images.githubusercontent.com/26105843/243941453-481f9d5b-2a4f-4a57-8bf8-21c5ae5c498f.png)
试试吧 DNS 中的 fallback 删掉看看
