### ISSUE TITLE
[Feature] 实现不同代理组使用不同的本地端口

### ISSUE THREAD

**Issue by C63H88CoN14O14P** [MetaCubeX/Clash.Meta#607]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

我阅读了wiki中关于port的一些配置文档,但是并没有发现能够实现我目的的方案,所以在此提出issue,如有重复,请见谅

我希望实现的具体功能
情景模拟

1. 我有一个       proxy-groups/proxy-providers 名为A 其中假定包含P1,P2,P3三个不同的代理服务器
2. 我还有第二个proxy-groups/proxy-providers 名为B 其中假设包含P4,P5,P6三个不同的代理服务器

我希望实现的效果
使用127.0.0.1:[port1]连接clashmeta,调用的是A中的代理服务器
使用127.0.0.1:[port2]连接clashmeta,调用的是B中的代理服务器

我个人觉得这样会比开多个代理软件更加高效,希望得到回复,感谢

**Comment by xishang0128** [comment]
@C63H88CoN14O14P 使用listeners

**Comment by C63H88CoN14O14P** [comment]
> @C63H88CoN14O14P 使用listeners

感谢回复,请问可以详细些吗

**Comment by Skyxim** [comment]
@C63H88CoN14O14P - X]  我已经仔细看过 [Documentation 并无法找到这个功能 I have read the documentation and was unable to solve the issue.

**Comment by xishang0128** [comment]
@C63H88CoN14O14P https://clash-meta.wiki/config/listeners/

**Comment by C63H88CoN14O14P** [comment]
> @C63H88CoN14O14P https://clash-meta.wiki/config/listeners/

好的,我先研究下,如果有问题再来请教
