### ISSUE TITLE
规则集中配置 geodata 格式的 Cloudflare 规则不生效，但单独在配置文件中写出来就生效

### ISSUE THREAD

**Issue by UptonEdward** [MetaCubeX/Clash.Meta#61]
我启用了 geodata-mode，下载了 Loyalsoldier 的 geoip 和 geosite 文件，并在一个规则集中配置了：
```
payload:
  - GEOIP,cloudflare
  - GEOSITE,cloudflare
  - GEOIP,twitter
```
此规则集被设置为代理，且放在规则的第一条。

在查看 log 时，发现访问任意一个 Cloudflare 网站都不会被匹配到此规则集，而是会一路顺到兜底的 Match 规则：
`[2022-05-18 00:30:01][INFO] [TCP] 127.0.0.1:53642(Google Chrome Helper) --> www.cloudflare.com:443 match Match using 未知[Vultr 首尔2 Xray]`
但我访问 Twitter 网站，却会被正确地匹配到该规则集。

然后我将 Cloudflare 的规则从那个规则集中删除，并单独作为一个规则写在第一条：
`  - GEOIP,cloudflare,代理`
再次访问 Cloudflare 网站，查看 log，此时发现 Cloudflare被匹配到了这条独立规则，不再匹配兜底规则：
`[2022-05-18 00:30:01][INFO] [TCP] 127.0.0.1:53642(Google Chrome Helper) --> www.cloudflare.com:443 match GeoIP(cloudflare) using 代理[Vultr 首尔2 Xray]`

这一情况在 geosite:cloudflare 和 geoip:cloudflare 这两个类别中都发生了。且当作独立规则出现时，两个规则都可以生效，说明不是本地的 geodata 文件不支持 Cloudflare 类别，而是规则集的问题。同时，同一规则集中的 geoip:twitter 可以生效，也印证了这个问题。

这是因为Rule-Set的机制就如此吗？还是什么原因？

**Comment by Adlyq** [comment]
@UptonEdward 有没加no-resolve
