### ISSUE TITLE
[Feature] 怎么不是github-actions发布的了？

### ISSUE THREAD

**Issue by backed80405** [MetaCubeX/Clash.Meta#612]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

希望可以恢复成action发布的

**Comment by Skyxim** [comment]
@backed80405 什么玩意？
