### ISSUE TITLE
auto-detect-interface inaccurate on android devices

### ISSUE THREAD

**Issue by adiprasetya** [MetaCubeX/Clash.Meta#62]
Devices: Redmi Note 9 (Merlin) | Mediatek
Kernel used: v1.11.1 android arm64 

auto-detect-interface using ap0 which is Hotspot interface if Hotspot turned ON, instead of ccmni0 or ccmni1 which is data cellular. in v1.11.0 working fine.

**Comment by Skyxim** [comment]
重新打包v1.11.1 修复了这个问题
