### ISSUE TITLE
[Bug] 太多的 DNS 解析

### ISSUE THREAD

**Issue by WangHaonie** [MetaCubeX/Clash.Meta#620]
断网后又恢复的时候，发现日志里有一堆对 ```sz.tencent.com``` 的 DNS 解析，看样子应该是 QQ 连接的域名，但是因为 QQ 也不可能一下子有这么多的请求且在网络处于正常情况下重新登录 QQ 也没有出现这个问题，所以觉得这可能是个 Bug。
<details><summary>日志截图</summary>
<img src="https://github.com/MetaCubeX/Clash.Meta/assets/68315280/439b138c-eaeb-48a0-833c-850e95921ba3" />
</details>

Clash 版本：alpha-144890d
操作系统：Windows 11 22H2 x64 22631.1835
<details><summary>配置文件</summary>
<pre><code>
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
proxy-groups:
rules:
proxy-providers: {}
rule-providers: {}
profile:
  store-selected: true
  store-fake-ip: true
tun:
  enable: true
  stack: system
  auto-detect-interface: true
  auto-route: true
  dns-hijack:
    - any:53
dns:
  enable: true
  prefer-h3: true
  listen: 0.0.0.0:1053
  ipv6: false
  use-hosts: false
  default-nameserver:
    - 119.29.29.29
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.lan"
    - localhost.ptlogin2.qq.com
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - "*.n.n.srv.nintendo.net"
    - +.stun.playstation.net
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
    - WORKGROUP
  nameserver-policy:
    geosite:cn: 119.29.29.29
    geolocation-!cn: 119.29.29.29
    gfw: 119.29.29.29
  nameserver:
    - 119.29.29.29
  fallback:
    - 119.29.29.29
  proxy-server-nameserver:
    - 119.29.29.29
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
    domain:
      - +.google.com
      - +.facebook.com
      - +.youtube.com
geodata-mode: true
geox-url:
  geoip: https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat
  geosite: https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat
  mmdb: https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/Country.mmdb
find-process-mode: always
tcp-concurrent: true
hosts:
  diskgenius.cn: 0.0.0.0
  www.diskgenius.cn: 0.0.0.0
</pre></code>
</details>

<details><summary>日志</summary>
<pre><code>
time="2023-06-13T17:45:00.5550973+08:00" level=debug msg="[DNS] resolve sz.tencent.com from udp://119.29.29.29:53"
time="2023-06-13T17:45:00.5953146+08:00" level=debug msg="[DNS] sz.tencent.com --> [111.206.99.43 61.149.23.29 61.149.23.38 61.149.23.117 61.149.23.111 61.149.23.35 111.206.99.52 125.39.196.188 60.29.240.44 123.125.0.160 123.125.0.81 123.125.0.36 61.149.23.47 61.149.23.96 61.149.23.64 61.149.23.62], from udp://119.29.29.29:53"
time="2023-06-13T17:45:00.7665674+08:00" level=debug msg="[DNS] resolve sz.tencent.com from udp://119.29.29.29:53"
time="2023-06-13T17:45:00.8095711+08:00" level=debug msg="[DNS] sz.tencent.com --> [123.125.0.36 61.149.23.29 61.149.23.38 61.149.23.117 61.149.23.111 61.149.23.35 111.206.99.52 125.39.196.188 60.29.240.44 123.125.0.160 123.125.0.81 111.206.99.43 61.149.23.47 61.149.23.96 61.149.23.64 61.149.23.62], from udp://119.29.29.29:53"
time="2023-06-13T17:45:00.8095711+08:00" level=debug msg="[DNS] resolve sz.tencent.com from udp://119.29.29.29:53"
time="2023-06-13T17:45:00.8526076+08:00" level=debug msg="[DNS] sz.tencent.com --> [61.149.23.62 61.149.23.29 61.149.23.38 61.149.23.117 61.149.23.111 61.149.23.35 111.206.99.52 125.39.196.188 60.29.240.44 123.125.0.160 123.125.0.81 123.125.0.36 61.149.23.47 61.149.23.96 61.149.23.64 111.206.99.43], from udp://119.29.29.29:53"
----------- 省略了 1200+ 行 -----------
time="2023-06-13T17:47:00.8846675+08:00" level=debug msg="[DNS] resolve sz.tencent.com from udp://119.29.29.29:53"
time="2023-06-13T17:47:00.9217828+08:00" level=debug msg="[DNS] sz.tencent.com --> [61.149.23.29 111.206.99.43 61.149.23.38 61.149.23.117 61.149.23.111 61.149.23.35 111.206.99.52 125.39.196.188 60.29.240.44 123.125.0.160 123.125.0.81 123.125.0.36 61.149.23.47 61.149.23.96 61.149.23.64 61.149.23.62], from udp://119.29.29.29:53"
time="2023-06-13T17:47:05.8894258+08:00" level=debug msg="[DNS] resolve sz.tencent.com from udp://119.29.29.29:53"
time="2023-06-13T17:47:05.9331575+08:00" level=debug msg="[DNS] sz.tencent.com --> [61.149.23.62 61.149.23.29 61.149.23.38 61.149.23.117 61.149.23.111 61.149.23.35 111.206.99.52 125.39.196.188 60.29.240.44 123.125.0.160 123.125.0.81 123.125.0.36 61.149.23.47 61.149.23.96 61.149.23.64 111.206.99.43], from udp://119.29.29.29:53"
time="2023-06-13T17:47:08.5339583+08:00" level=debug msg="[DNS] resolve sz.tencent.com from udp://119.29.29.29:53"
time="2023-06-13T17:47:08.5698196+08:00" level=debug msg="[DNS] sz.tencent.com --> [123.125.0.81 61.149.23.29 61.149.23.38 61.149.23.117 61.149.23.111 61.149.23.35 111.206.99.52 125.39.196.188 60.29.240.44 123.125.0.160 111.206.99.43 123.125.0.36 61.149.23.47 61.149.23.96 61.149.23.64 61.149.23.62], from udp://119.29.29.29:53"
</pre></code>
</details>

顺带一提，能不能加一个功能，就是当无网络连接的时候暂停所有请求 (比如关闭系统代理、TUN 等)，等到恢复网络的时候再接受请求，今天换路由器的时候，回头看一眼日志都刷爆了。
<details><summary>日志截图</summary>
<img src="https://github.com/MetaCubeX/Clash.Meta/assets/68315280/54827687-6e63-4040-8e77-ab2314f7cb11" />
</details>

<details><summary>日志</summary>
<pre><code>
time="2023-06-13T14:19:29.4066779+08:00" level=warning msg="[TUN] default interface changed by monitor,  => 以太网"?
time="2023-06-13T17:39:15.7760943+08:00" level=debug msg="[DNS] resolve client.wns.windows.com error: all DNS requests failed, first error: interface not found"
time="2023-06-13T17:39:15.7760943+08:00" level=warning msg="[TCP] dial 🌍 国外流量 (match GeoSite/geolocation-!cn) 198.18.0.1:5365(svchost.exe) --> client.wns.windows.com:443 error: 节点域名:4016 connect error: dns resolve failed: all DNS requests failed, first error: interface not found"
time="2023-06-13T17:39:15.7760943+08:00" level=warning msg="[TCP] dial 🌍 国外流量 (match GeoSite/geolocation-!cn) 198.18.0.1:5366(svchost.exe) --> client.wns.windows.com:443 error: 节点域名:4016 connect error: dns resolve failed: all DNS requests failed, first error: interface not found"
----------- 省略了 5000+ 行 -----------
time="2023-06-13T17:57:54.2049799+08:00" level=warning msg="[TCP] dial 🌍 国外流量 (match GeoSite/geolocation-!cn) 127.0.0.1:9888(msedge.exe) --> edge.microsoft.com:443 error: 节点域名:4016 connect error: dns resolve failed: all DNS requests failed, first error: interface not found"
time="2023-06-13T17:57:54.2201295+08:00" level=warning msg="[TCP] dial 🌍 国外流量 (match GeoSite/geolocation-!cn) 127.0.0.1:9895(msedge.exe) --> functional.events.data.microsoft.com:443 error: 节点域名:4016 connect error: dns resolve failed: all DNS requests failed, first error: interface not found"
time="2023-06-13T17:57:54.2357774+08:00" level=warning msg="[TCP] dial 🎯 国内直连 (match GeoSite/CN) 198.18.0.1:9894(baidunetdisk.exe) --> pan.baidu.com:443 error: dns resolve failed: all DNS requests failed, first error: interface not found"
</pre></code>
</details>

**Comment by QIN2DIM** [comment]
使用外部 API 清掉 fakepool 的缓存，本机的 DNS 缓存也清一下

**Comment by Skyxim** [comment]
Debug 日志不是让你天天看的，是用来定位问题的

**Comment by vickyleu** [comment]
.... 我是域名持有人, 你这个ip以前是我的, 后来被回收了😓

**Comment by vickyleu** [comment]
刚收到邮件才知道
