### ISSUE TITLE
[Bug] openclash无法正常使用tuic v5

### ISSUE THREAD

**Issue by hux555** [MetaCubeX/Clash.Meta#644]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

v1.15.0

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
1
```

### Description

openclash更新了v1.15.0, 可以正常导入tuic v5,但是Dashboard控制面板手动测速能正常显示延时，没过几秒就失联了 无法使用状态。

**Comment by hux555** [comment]
![面板](https://github.com/MetaCubeX/Clash.Meta/assets/119776008/39d2edad-8745-43ce-b311-e31aebaf31fe)
![内核](https://github.com/MetaCubeX/Clash.Meta/assets/119776008/3defd3b7-080e-4b08-9444-215a79012153)
![内核](https://github.com/MetaCubeX/Clash.Meta/assets/119776008/8f55d87a-3b2e-4cad-ab2d-8dc302c6ebdd)
![面板](https://github.com/MetaCubeX/Clash.Meta/assets/119776008/7c2ede3e-43f5-472f-b804-e52ba417e2fb)

**Comment by hux555** [comment]
![面板](https://github.com/MetaCubeX/Clash.Meta/assets/119776008/a09475fd-c923-4ebd-905f-9cbba568bee1)
![内核](https://github.com/MetaCubeX/Clash.Meta/assets/119776008/ebe0b717-c8de-4005-9c99-057cd9f3b651)

**Comment by xianren78** [comment]
手动选中这个节点看能不能用，clash有黑洞节点的bug。

**Comment by hux555** [comment]
> 手动选中这个节点看能不能用，冲突有真空节点的bug。

已经尝试过手动了 无法连接， 但是clash for win 是没问题的

**Comment by ZevAlain** [comment]
同样遇到了这个问题

**Comment by gfwHacker** [comment]
@ZevAlain 我原版clash也能用

**Comment by ZevAlain** [comment]
@gfwHacker 
可否贴一下client和server配置。感谢

**Comment by hux555** [comment]
> @ZevAlain 我原版clash也能用

同样的配置文件，clash for win是可以的  但openclash 不行呢  你的可以吗？openclash？

**Comment by ZevAlain** [comment]
@hux555 跟你配置一样，也不行。stash可以使用

**Comment by xianren78** [comment]
可以试试clash meta做服务端，可能会出现openclash可用，但是windows不能用。

**Comment by sduwfc** [comment]
@hux555 请问这个问题怎么解决的
