### ISSUE TITLE
vless+h2好像不支持

### ISSUE THREAD

**Issue by guigeng** [MetaCubeX/Clash.Meta#65]
我看手册里面只有vless+tcp、vless+ws
好像没有vless+h2，vless+kcp的是不是还没支持？
谢谢

**Comment by MetaCubeX** [comment]
@guigeng 不写不等于没有

**Comment by guigeng** [comment]
请教一下，如何配置。
`  - name: "vlessh2"
    type: vless
    server: server
    port: 443
    uuid: uuid
    network: h2
    tls: true
    h2-opts:
      host:
        - example.com
      path: /path`

试了一下不行。谢谢

**Comment by MetaCubeX** [comment]
下载转换器直接转试试看

**Comment by guigeng** [comment]
> 下载转换器直接转试试看

```
	case "h2":
		c, err = v.streamTLSOrXTLSConn(c, true)
		if err != nil {
			return nil, err
		}

		h2Opts := &vmess.H2Config{
			Hosts: v.option.HTTP2Opts.Host,
			Path:  v.option.HTTP2Opts.Path,
		}

		c, err = vmess.StreamH2Conn(c, h2Opts)
```
看代码，h2-opts：里面应该写hosts还是host
不太懂go。
没看到vless下面有支持kcp

**Comment by guigeng** [comment]
搞定了，
h2-opts下面不需要指定host

**Comment by linkwanggo** [comment]
@MetaCubeX 在provider中使用v2ray的订阅，vless+h2协议虽然能解析出来，但实际并不可用（v2rayN中可用）
log错误显示error: io: read/write on closed pipe

**Comment by elvisw** [comment]
> 搞定了， h2-opts下面不需要指定host

我测试了一下，还是得有host字段，你在这里https://github.com/MetaCubeX/Clash.Meta/issues/65#issuecomment-1137004531
给出的例子是可以用的
