### ISSUE TITLE
[Feature] SRC-IP-CIDR 支持指定ipv6后缀

### ISSUE THREAD

**Issue by fengyang0317** [MetaCubeX/Clash.Meta#665]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

SRC-IP-CIDR目前只能指定前缀，比如1.1.1.1/24，2001::/64.
家用宽带的ipv6前缀是动态分配的，家里的主机没办法用SRC-IP-CIDR来指定。

希望允许SRC-IP-CIDR指定ipv6的后缀，比如::1*64可以指定后64位匹配::1的局域网内的主机。

### Possible Solution

格式可以随便，::1*64，::1-64
或者直接加一个SRC-IP-SUFFIX

**Comment by fengyang0317** [comment]
https://github.com/MetaCubeX/Clash.Meta/blob/53f9e1ee7104473da2b4ff5da29965563084482d/rules/common/ipcidr.go#L58

我去，文档里没写，但是这个功能已经存在了。亲测指定ipv6后缀好使

**Comment by fengyang0317** [comment]
我是这么写的
```
- SRC-IP-SUFFIX,::d5d/16,DIRECT
```

**Comment by y403321959** [comment]
搞定了，谢谢老哥，我是废物。

**Comment by about300** [comment]
> 我就是这么写的
> 
> ```
> - SRC-IP-SUFFIX,::d5d/16,DIRECT
> ```
这个/16是啥意思 我的完整ipv6地址是240e:3b4:231:5770:11:32ff:fe2f:fba5
