### ISSUE TITLE
[Bug] 不支持 dns enable false 

### ISSUE THREAD

**Issue by zizhuangfly** [MetaCubeX/Clash.Meta#677]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.15.0 windows 386 with go1.20.5

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
dns:
  enable: false
```

### Clash log

```shell
dns resolve failed: lookup h.trace.qq.com: i/o timeout
```

### Description

# 背景：
**我并不想使用 clash-meta的dns功能，而是想直接使用系统DNS（路由器：192.168.1.1）服务**，
规则列表主要是域名规则，有关ip的规则都加上了 no-resolve。（防止dns泄漏）
# 使用方式：
系统代理，没有使用 tun/tap模式，主要浏览器使用
操作系统，win10, 
clash-meta 版本: 1.15.0 windows 386 with go1.20.5
# 问题描述：
## case 1
当不开启系统代理的时候，国内网站访问速度很快，表现正常，
## case 2 
而当开启系统代理，且
当yaml配置文件使用 
```
dns:
  enable: false
```
也就是禁用clash自带dns模块时候，直连网站访问速度非常慢，并且常常不可访问，比如 **.microsoft.com, **.qq.com
日志里大量出现：
``` shell
dns resolve failed: lookup h.trace.qq.com: i/o timeout
```
但是访问需要代理网站速度还可以，比访问直连网站快多了。
## case3
使用文档里面的 demo dns 配置，也就是 enable: true加上其它的配置，访问国内网站也很快，也没有出现dns解析失败的日志
# 疑惑
clash-meta 不支持dns: enable :false 配置吗？
ps: 我很确信是不是走的直连

**Comment by zizhuangfly** [comment]
感觉 #673  这个issue 和我遇到的有点类似，应该是同一个问题(这是我第一次使用clash-meta)

**Comment by Skyxim** [comment]
@zizhuangfly https://github.com/MetaCubeX/Clash.Meta/blob/53f9e1ee7104473da2b4ff5da29965563084482d/docs/config.yaml#L169  尝试配置这个，试试调整到 1

**Comment by zizhuangfly** [comment]
> @zizhuangfly
> 
> https://github.com/MetaCubeX/Clash.Meta/blob/53f9e1ee7104473da2b4ff5da29965563084482d/docs/config.yaml#L169
> 
> 尝试配置这个，试试调整到 1

@Skyxim 
 还是一样的,直连无法访问，错误日志也是一样的。ipv6没有显式开启

**Comment by zizhuangfly** [comment]
这两天追踪了一下这个dns 解析问题，之所以在使用系统DNS的时候 clash 没有问题，clash-meta 有问题。是多方面因素综合导致。
首先声明对于golang预言只是这两天了解了一下，还很肤浅，不当之处敬请修正补充

# 原因

1. dns解析 clash-meta使用了go, clash 默认使用的是cgo
2. go dns 解析在有多个dns 服务器（一个ipv4, 一个ipv6，至于这个ipv6怎么在win10系统上禁止不清楚）**并不是并发查询，而是串行，而且这个顺序在我机器上是先ipv6再ipv4**, 其超时时间5s和clash-meta tcp超时时间（没错是`DefaultTCPTimeout`参数）一致,  而在我机器上查询ipv6表现为卡死状态，没有抓取到任何dns 包(可能是路由器不支持ipv6吧)。

# 解决方案
## 个人快速解决方案
下载源码，修改行为1：
修改[此处代码](https://github.com/MetaCubeX/Clash.Meta/blob/53f9e1ee7104473da2b4ff5da29965563084482d/component/dialer/resolver.go#L12C35-L12C35) `net.DefaultResolver.PreferGo = true` 改成 `net.DefaultResolver.PreferGo = false`， 重新build，即可正常使用系统dns时候愉快直连

## 大佬出手解决
### clash-meta 维护者可以考虑在yaml里加一个配置选项控制上述的行为1

### 向golang官方提issue, 官方库至少存在两个问题：

- dns server 排序问题（源码注释表明已经注意到该问题，但是没有动力去实现）
- dns server 串行而不是并行和通常认识和实践不符

### 有木有网络/系统大神可以解释一下一个ipv6地址的dns服务器是怎么出现的？如何调整自己系统配置？😂😂

**Comment by zizhuangfly** [comment]
对了，@Skyxim  提到的解决方案在dns: enable : true 的条件下应该管用，但是dns: enable: false 的时候不起作用

**Comment by peasoft** [comment]
> 一个ipv6地址的dns服务器是怎么出现的？

随着 IPv6 的发展，一些网站启用了 IPv6，DNS 服务器自然也会启用 IPv6。现在，支持 IPv6 的路由器默认会在 DHCP 服务中内置一个 IPv6 DNS。一般来说，如果你没有改过 DNS，电脑默认使用 DHCP 得来的 DNS 服务器，这就包括了 IPv6 服务器。

> 如何调整自己系统配置？

你可以直接禁用 IPv6，见 [此文](https://zhuanlan.zhihu.com/p/377418585)。**但是在看到最后一张图时，不做文章中的操作，而是把 `Internet 协议版本 6` 前的勾去掉，直接确定。**

以上是我的个人观点，如不对请指正！

**Comment by zizhuangfly** [comment]
@peasoft 之前对于ipv6几乎不了解，这两天为了弄清楚win10上面这个问题，稍微了解了一点。

可能是之前安装/卸载的一些vpn软件导致的我本机 ipv6 协议栈出现问题（有卸载不成功的vpn软件），虽然开启了ipv6，但是无法获取ipv6地址，最后是通过升级win10解决了问题，能够获取到 ipv6 地址了。
使用原版 clash-meta 在 `dns : enable : false `配置下也可以正常访问直连网站了。

以上是我提出这个bug的最根本原因，**虽然但是**，golang 实现的 dns resolve 肯定还是有瑕疵的：在 cgo良好运行条件下，go 无法运行。可以认为这个bug是 ipv4, ipv6 双栈兼容的一个问题。

ps: 补充一下我电脑升级的版本情况：从 win10 1803升级的（汗，忘记看升级后的版本了，应该是截止到目前最新版） 
另：之所以笃定是win10 ipv6 问题，是因为本地局域网另一台设备 ipv6 运行正常

**Comment by swRains** [comment]
解决了，感谢！每次都调用阿里云的dns给我整麻了，我这里是ipv4优先，ipv6能正常获取到全球单播地址，平板是纯ipv4，均无法访问自定义的dns，应该不是ipv6的问题。

**Comment by zizhuangfly** [comment]
> 解决了，感谢！每次都调用阿里云的dns给我整麻了，我这里是ipv4优先，ipv6能正常获取到全球单播地址，平板是纯ipv4，均无法访问自定义的dns，应该不是ipv6的问题。

**Comment by zizhuangfly** [comment]
> 解决了，感谢！每次都调用阿里云的dns给我整麻了，我这里是ipv4优先，ipv6能正常获取到全球单播地址，平板是纯ipv4，均无法访问自定义的dns，应该不是ipv6的问题。

看你问题描述，应该是go dns 在windows 上没有读取到 host 文件，我看到有过类似issue, 该issue状态还是open。大概和你的问题是同一个。
看你提到多个设备，改host不够跨平台，你的问题可以通过clash-meta dns实现，这样yaml可以通用。具体配置你可以看demo, 还是比较详细的。

**Comment by swRains** [comment]
> 
> 
> 
> 
> > 解决了，感谢！每次都调用阿里云的dns给我整麻了，我这里是ipv4优先，ipv6能正常获取到全球单播地址，平板是纯ipv4，均无法访问自定义的dns，应该不是ipv6的问题。
> 
> 看你问题描述，应该是go dns 在windows 上没有读取到 host 文件，我看到有过类似issue, 该issue状态还是open，相关代码还是TODO。大概和你的问题是同一个。
> 看你提到多个设备，改host不够跨平台，如果clash始终运行（服务/常驻进程），你的问题可以通过clash-meta dns实现，这样yaml可以通用，避免各个平台host文件路径、格式不一致问题。具体配置你可以看demo, 还是比较详细的。 

之前试过，改yaml里的，dns也无效，不过我也懒得折腾了。主要是我是订阅的机场的，一更新自定义dns就没了，用系统的dns或者doh就已经够用了。

**Comment by zizhuangfly** [comment]
> > > 解决了，感谢！每次都调用阿里云的dns给我整麻了，我这里是ipv4优先，ipv6能正常获取到全球单播地址，平板是纯ipv4，均无法访问自定义的dns，应该不是ipv6的问题。
> > 
> > 
> > 看你问题描述，应该是go dns 在windows 上没有读取到 host 文件，我看到有过类似issue, 该issue状态还是open，相关代码还是TODO。大概和你的问题是同一个。
> > 看你提到多个设备，改host不够跨平台，如果clash始终运行（服务/常驻进程），你的问题可以通过clash-meta dns实现，这样yaml可以通用，避免各个平台host文件路径、格式不一致问题。具体配置你可以看demo, 还是比较详细的。
> 
> 之前试过，改yaml里的，dns也无效，不过我也懒得折腾了。主要是我是订阅的机场的，一更新自定义dns就没了，用系统的dns或者doh就已经够用了。

- yaml 里面与此有关的是 `hosts` 配置项，该项不属dns子项（尽管属于dns功能）
- proxy-provider 功能是用来单独隔离节点信息，这样可以让节点配置信息动态订阅而其它配置保持不变

**Comment by Mythologyli** [comment]
> 这两天追踪了一下这个dns 解析问题，之所以在使用系统DNS的时候 clash 没有问题，clash-meta 有问题。是多方面因素综合导致。 首先声明对于golang语言只是这两天了解了一下，还很肤浅，不当之处敬请修正补充
> 
> # 原因
> 1. dns解析 clash-meta使用了go, clash 默认使用的是cgo
> 2. go dns 解析在有多个dns 服务器（一个ipv4, 一个ipv6，至于这个ipv6怎么在win10系统上禁止不清楚）**并不是并发查询，而是串行，而且这个顺序在我机器上是先ipv6再ipv4**, 其超时时间5s和clash-meta tcp超时时间（没错是`DefaultTCPTimeout`参数）刚好一致（导致dns超时的时候整个处理流程都超时了）,  而在我机器上查询ipv6表现为卡死状态，没有抓取到任何dns 包。
> 
> # 解决方案
> ## 个人快速解决方案
> 下载源码，修改行为1： 修改[此处代码](https://github.com/MetaCubeX/Clash.Meta/blob/53f9e1ee7104473da2b4ff5da29965563084482d/component/dialer/resolver.go#L12C35-L12C35) `net.DefaultResolver.PreferGo = true` 改成 `net.DefaultResolver.PreferGo = false`， 重新build，即可正常使用系统dns时候愉快直连
> 
> ## 大佬出手解决
> ### opt 1
> clash-meta 维护者可以考虑在yaml里加一个配置选项控制上述的行为1
> 
> ### opt 2
> 向golang官方提issue, 官方库至少存在两个问题：
> 
> * dns server 排序问题（源码注释表明已经注意到该问题，但是没有动力去实现）
> * dns server 串行而不是并行和通常认识和实践不符
> 
> ### opt best
> 有木有网络/系统大神可以解释一下一个ipv6地址的dns服务器是怎么出现的？如何调整自己系统配置？😂😂

我是在 OpenWrt LAN 设置里去掉了“通告该设备为 IPv6 DNS 服务器”
