### ISSUE TITLE
[Feature] fallback策略组添加回退功能

### ISSUE THREAD

**Issue by Toad-stool** [MetaCubeX/Clash.Meta#679]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

fallback策略组的意义是优先使用节点1
当节点1不可用时跳到节点2，当节点2不可用时跳到节点3，以此类推
但前提是保证节点1被优先使用，所以可否新增功能例如（back: true|false）
当back: true ，按interval进行周期检测时若节点1恢复可用，则继续使用节点1

proxy-groups:
  - name: "fallback"
    type: fallback
    proxies:
      - 节点1
      - 节点2
      - 节点3
    url: 'https://www.gstatic.com/generate_204'
    interval: 300
    back: true

**Comment by Skyxim** [comment]
@Toad-stool 现在逻辑并不会依次向下，你的意思是添加 false 时只向下回落，而不恢复到优先级高的节点？

**Comment by Toad-stool** [comment]
> @Toad-stool 现在逻辑并不会依次向下，你的意思是添加 false 时只向下回落，而不恢复到优先级高的节点？

呃，对于fallback策略组的运行机制，我的理解好像与你不同
我的理解是“当节点1不可用时跳到节点2，当节点2不可用时跳到节点3，以此类推”
至少clash原版官方文档的描述也是如此
![Screenshot_20230801144344](https://github.com/MetaCubeX/Clash.Meta/assets/26811405/7181bac1-607a-42cd-8c20-9671bfc79313)
clash.meta的文档对fallback策略组没有特别说明，并且结合我的使用来看，clash.meta的fallback也是如此
所以我的需求并不是节点向下回落，而是恢复到优先级高的节点。

**Comment by Skyxim** [comment]
@Toad-stool The first available server will be used.
只要检测到有效必定返回第一个

**Comment by Skyxim** [comment]
@Toad-stool 所以不需要任何修改就可以实现你的效果

**Comment by Toad-stool** [comment]
> @Toad-stool 所以不需要任何修改就可以实现你的效果，代码也是如此

是我理解错了，刚刚又去试验了一下，确如你所说不需要任何修改就能实现我想要的效果，感谢！
