### ISSUE TITLE
[Feature Request]命中Fallback-filter之后不再查询nameserver

### ISSUE THREAD

**Issue by InspoOnU** [MetaCubeX/Clash.Meta#68]
即使命中了fallback-filter里的geosite规则后，内核也会向nameserver和fallback并发查询。

这种情况只向fallback查询就可以了。如果实现这个特性，可以帮助防止DNS隐私泄漏，节省系统资源。

**Comment by Adlyq** [comment]
@InspoOnU 那么geosite的意义是什么

**Comment by InspoOnU** [comment]
> @InspoOnU 那么geosite的意义是什么

防止DNS污染到国内IP导致访问失败；比如nameserver填了国内DNS，可以防止隐私泄漏

**Comment by Skyxim** [comment]
@InspoOnU 现在的逻辑本来就是匹配geosite后 不并发， 不过不推荐折腾dns
