### ISSUE TITLE
[Feature] 安卓32位armv7

### ISSUE THREAD

**Issue by rwoss** [MetaCubeX/Clash.Meta#681]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

会支持armv7架构的安卓系统吗，看到只有linux的armv7

**Comment by xishang0128** [comment]
@rwoss 不会支持,并且armv7的安卓,内核过于古早,很多功能也没法支持

**Comment by rwoss** [comment]
ok 明白了
