### ISSUE TITLE
[Feature] 希望增加一个 使用 windows firewall 的开关，我的windows系统永久的禁用了firewall服务，新版本使用TUN模式时会报错。

### ISSUE THREAD

**Issue by lootwealth** [MetaCubeX/Clash.Meta#687]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

v1.14.5增加了这个功能 chore: Use API to create windows firewall rule by @Larvan2
level=error msg="External controller listen error: listen tcp 0.0.0.0:9090: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted."
在不能运行firewall服务的系统上使用TUN模式会报这个错，运行firewall服务时，则正常。希望增加一个开关。

**Comment by Skyxim** [comment]
@lootwealth Only one usage of each socket address (protocol/network address/port) is normally permitted 
通常只允许每个套接字地址（协议/网络地址/端口）使用一次 Powered by google translate
