### ISSUE TITLE
ruleset里不能用逻辑规则吗？

### ISSUE THREAD

**Issue by Telehub** [MetaCubeX/Clash.Meta#69]
payload:
  - NOT,(OR,((SRC-IP-CIDR,x.x.x.x/xx),(SRC-IP-CIDR,x.x.x.x/xx),(SRC-IP-CIDR,x.x.x.x/xx)))

rule provider里类似这样写，配置文件里用ruleset调用，但是匹配不了。

**Comment by Skyxim** [comment]
@Telehub 不可 设计如此，能调用只是meta对provider不支持的不会导致不会启动，而是采用忽略
