### ISSUE TITLE
[Bug] URL-Test 手动选择后，group/delay接口无法恢复自动选择

### ISSUE THREAD

**Issue by lixin-wei** [MetaCubeX/Clash.Meta#693]
### Clash version

1.15.0, Linux, arm64

### Description

url-test的group，通过Put `/proxy`接口选择了一个proxy之后，有办法恢复自动选择吗？

理想中是重新测速一下（`/group/delay`）就得恢复自动选择，但测试下来好像不行？

**Comment by lixin-wei** [comment]
@stitchrs 大佬能帮忙看一眼吗，感激不尽，我看url-test是您改的～

**Comment by Larvan2** [comment]
目前的逻辑是为了提供`手动选择urltest组的节点`的功能
如果手动选过就会锁定已选择的节点，此节点无法连接才会使用自动选择的节点

**Comment by lixin-wei** [comment]
@Larvan2 感谢回复！有办法提供一种方式，恢复自动选择吗？

我不小心在yacd上点了一下，就变不回去了Orz

**Comment by Larvan2** [comment]
> 我不小心在yacd上点了一下，就变不回去了Orz

临时解决方案的话，在yacd重启或者重载核心应该就行
![image](https://github.com/MetaCubeX/Clash.Meta/assets/78135608/2d676ef5-d924-4a28-a3ae-cbbc9cfb7c91)

**Comment by Larvan2** [comment]
b8a60261efb2ebe9f5a1df95f52e9669aa20e28c

**Comment by lixin-wei** [comment]
感谢修复
