### ISSUE TITLE
[Feature] 增加pac 功能

### ISSUE THREAD

**Issue by loyou22** [MetaCubeX/Clash.Meta#694]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

和cfw那样系统代理弄pac方式。谢谢

**Comment by xishang0128** [comment]
@loyou22 那是gui的功能,关内核啥事,需要的自己配置

**Comment by qist** [comment]
自己写pac 代理地址改成代理端口就是了。

**Comment by qist** [comment]
https://[raw.githubusercontent.com/petronny/gfwlist2pac/master/gfwlist.pac](https://raw.githubusercontent.com/petronny/gfwlist2pac/master/gfwlist.pac)

**Comment by Cikaros** [comment]
增加PAC也未尝不可，因为规则提供者提供到的规则，目前内核没有接口可以直接查询出规则数据，可以设立一个pac接口用于动态生成PAC以供PC机可以直接配置
例如：http://121.231.23.1:8080/pac
返回：var proxy = "PROXY 121.231.23.1:7890; SOCKS5 121.231.23.1:7890; DIRECT"; //这里根据clash.meta的配置决定
......

**Comment by Skyxim** [comment]
> 增加PAC也未尝不可，因为规则提供者提供到的规则，目前内核没有接口可以直接查询出规则数据，可以设立一个pac接口用于动态生成PAC以供PC机可以直接配置 例如：http://121.231.23.1:8080/pac 返回：var proxy = "PROXY 121.231.23.1:7890; SOCKS5 121.231.23.1:7890; DIRECT"; //这里根据clash.meta的配置决定 ......
> 
> 这样做的好处是，可以将其部署到远程服务器，客户机则可以直接配置PAC，就可直接使用

https://zh.wikipedia.org/wiki/代理自动配置

先了解下它是什么

**Comment by Cikaros** [comment]
> > 增加PAC也未尝不可，因为规则提供者提供到的规则，目前内核没有接口可以直接查询出规则数据，可以设立一个pac接口用于动态生成PAC以供PC机可以直接配置 例如：http://121.231.23.1:8080/pac 返回：var proxy = "PROXY 121.231.23.1:7890; SOCKS5 121.231.23.1:7890; DIRECT"; //这里根据clash.meta的配置决定 ......
> > 这样做的好处是，可以将其部署到远程服务器，客户机则可以直接配置PAC，就可直接使用
> 
> [https://zh.wikipedia.org/wiki/代理自动配置](https://zh.wikipedia.org/wiki/%E4%BB%A3%E7%90%86%E8%87%AA%E5%8A%A8%E9%85%8D%E7%BD%AE)
> 
> 先了解下它是什么

我非常清楚，它是什么。我的目的在于，减少客户端的操作，让它更好用（就是个为用户考虑的思维，因为这一步服务端不做，那么就需要客户端去做，也就需要用户在使用时再去解析一遍yaml文件中的规则，以保证代理规则和PAC完全一致，虽然用户可以自行编写其他的PAC，但那样编写出的PAC并不完全适配yaml中的规则）

上述说的场景，仅发生在作为服务端部署时存在，因为此时客户机上不会安装任何程序（GUI程序或其他代理程序）

**Comment by PuerNya** [comment]
@Cikaros 那为什么不开 tun

**Comment by Cikaros** [comment]
> @Cikaros 那为什么不开 tun

这不是在探讨PAC的场景嘛😄

**Comment by PuerNya** [comment]
@Cikaros 对于小白来说他们并不使用裸核，而是使用图形客户端，它们本来就有，如果需要更好的劫持流量，那就使用 tun，况且本来就不是所有程序都认系统代理

**Comment by Cikaros** [comment]
@PuerNya 但是其他情况下就不会这样用呀，因为客户机并不想让所有流量都走服务器

**Comment by Cikaros** [comment]
@PuerNya @Skyxim 非要举个例子，我就是这么用的，利用clash.meta和WireGuard建立虚拟网络去做
我只是提个建议，不是要拼个你死我活，实在不行我自己去改也未尝不可

**Comment by PuerNya** [comment]
@Cikaros 加油

**Comment by Cikaros** [comment]
追加这方面的支持，可以拓宽clash.meta的适用场景

**Comment by wwqgtxx** [comment]
> @PuerNya @Skyxim 非要举个例子，我就是这么用的，利用clash.meta和WireGuard建立虚拟网络去做 我只是提个建议，不是要拼个你死我活，实在不行我自己去改也未尝不可

欢迎自己去改，也欢迎改完后PR回来

**Comment by Cikaros** [comment]
> > @PuerNya @Skyxim 非要举个例子，我就是这么用的，利用clash.meta和WireGuard建立虚拟网络去做 我只是提个建议，不是要拼个你死我活，实在不行我自己去改也未尝不可
> 
> 欢迎自己去改，也欢迎改完后PR回来

这个代码封装的也太死了，数据都拿不出来

**Comment by ArchGuyWu** [comment]
@Cikaros 只有你一个在这样用为啥还要加？

**Comment by nb5p** [comment]
再开一个socks端口，这个端口根据你的需要编写规则。自己根据需要编写好PAC，放到external-ui: 目录里。得到URL后，配置到你需要PAC的地方

**Comment by Cikaros** [comment]
> 再开一个socks端口，这个端口根据你的需要编写规则。自己根据需要编写好PAC，放到external-ui: 目录里。得到URL后，配置到你需要PAC的地方

你说的这种方案解决不了我说的这种场景

> > > 增加PAC也未尝不可，因为规则提供者提供到的规则，目前内核没有接口可以直接查询出规则数据，可以设立一个pac接口用于动态生成PAC以供PC机可以直接配置 例如：http://121.231.23.1:8080/pac 返回：var proxy = "PROXY 121.231.23.1:7890; SOCKS5 121.231.23.1:7890; DIRECT"; //这里根据clash.meta的配置决定 ......
> > > 这样做的好处是，可以将其部署到远程服务器，客户机则可以直接配置PAC，就可直接使用
> > 
> > 
> > [https://zh.wikipedia.org/wiki/代理自动配置](https://zh.wikipedia.org/wiki/%E4%BB%A3%E7%90%86%E8%87%AA%E5%8A%A8%E9%85%8D%E7%BD%AE)
> > 先了解下它是什么
> 
> 我非常清楚，它是什么。我的目的在于，减少客户端的操作，让它更好用（就是个为用户考虑的思维，因为这一步服务端不做，那么就需要客户端去做，也就需要用户在使用时再去解析一遍yaml文件中的规则，以保证代理规则和PAC完全一致，虽然用户可以自行编写其他的PAC，但那样编写出的PAC并不完全适配yaml中的规则，因为规则是实时更新的）
> 
> 上述说的场景，仅发生在作为服务端部署时存在，因为此时客户机上不会安装任何程序（GUI程序或其他代理程序）

**Comment by qist** [comment]
> 再开一个socks端口，这个端口根据你的需要编写规则。自己根据需要编写好PAC，放到external-ui: 目录里。得到URL后，配置到你需要PAC的地方
对方想要的是用接口读取yaml 规则然后自动转换成pac 可读取的配置然后返回给使用者。也就在先用的api 接口加个pac 接口访问就拿到规则跟代理端口。
