### ISSUE TITLE
"Vless" unsupported, but "vless" supported

### ISSUE THREAD

**Issue by jba-tm** [MetaCubeX/Clash.Meta#695]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.15.1

### What OS are you seeing the problem on?

macOS, Windows

### Clash config

```yaml
proxies:
  - {"type":"Vless",    ... other configs}
```

### Description

**To Reproduce**
This is not work:

```
proxies:
  - {"type":"Vless",    ... other configs}
```

But this is work:

```
proxies:
  - {"type":"vless",    ... other configs}
```

**Screenshots**
<img width="360" alt="image" src="https://github.com/zzzgydi/clash-verge/assets/66518710/0afd9302-415b-413b-911c-0753eaa32f6d">

**Information**
 - OS: macos, windows 10
 - Clash Verge Version: [e.g. 1.3.4]
 - Clash Core: clash meta 1.15.1 Meta

**Comment by 13wenwen** [comment]
你就用vless不就完事了，有什么大惊小怪的

**Comment by xishang0128** [comment]
@jba-tm This is expected behavior and should be all lowercase

**Comment by xishang0128** [comment]
@jba-tm you should let subscriber modify

**Comment by jba-tm** [comment]
Okey I understand. 
Last question. What will be if I build my own core, and change behavior like I expected. What will go wrong?

**Comment by 13wenwen** [comment]
If you don't know these, you don't need to compile

**Comment by jba-tm** [comment]
It will be more durable and flexible

**Comment by xishang0128** [comment]
@jba-tm nothing will happen, you just need to modify https://github.com/MetaCubeX/Clash.Meta/blob/65071ea7d16724ef3262366f0c0877b4a73d815b/adapter/parser.go#L67

**Comment by jba-tm** [comment]
> If you don't know these, you don't need to compile

I think will not do this

**Comment by 13wenwen** [comment]
Please close this issue. Please do not abuse issue
