### ISSUE TITLE
[Feature] Juicity 协议支持

### ISSUE THREAD

**Issue by Misaka-blog** [MetaCubeX/Clash.Meta#697]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

希望在 Clash Meta 中增加对 Juicity 代理协议节点的支持

**Comment by xishang0128** [comment]
@Misaka-blog 不会支持,不用求了

**Comment by Zxis233** [comment]
> @Misaka-blog 不会支持,不用求了

为啥呢

**Comment by soffchen** [comment]
```
Juicity 是基于 Tuic 的改进，主要改进 Tuic 的 UDP 所存在的一些问题。

当 Tuic 的 udp_relay_mode 使用 native 时，在丢包线路中的应用层重试将变得严重，例如 DNS 的重试通常会发生在几秒后，较为影响体验。
当 Tuic 的 udp_relay_mode 使用 quic 时，每一个 UDP 数据报均使用单独的 unidirectional_stream 传输，消耗不必要的资源。
Juicity 使用 UDP over Stream 解决这上述问题，并在规范中给出更多实现建议和约束，以避免其他可能出现的问题。
```

feat: add udp-over-stream for tuic #https://github.com/MetaCubeX/Clash.Meta/commit/1181fd456077b68aaa4ffbacef6626f807638bc5
