### ISSUE TITLE
使用clashN开启TUN模式时CPU占用非常高, 系统直接卡死

### ISSUE THREAD

**Issue by HanHan666666** [MetaCubeX/Clash.Meta#70]
![image](https://user-images.githubusercontent.com/60591430/170989159-1636ce50-2aa6-47a4-a7a0-fbb2d3d6e0eb.png)

**Comment by ag2s20150909** [comment]
> @ag2s20150909 请把clashN的TUN部分配置贴出来瞧瞧

你回复错人了

**Comment by HanHan666666** [comment]
https://github.com/2dust/clashN/issues/49#event-6742579440
