### ISSUE TITLE
修改端口后，每次重启后又恢复7890

### ISSUE THREAD

**Issue by jymr92** [MetaCubeX/Clash.Meta#700]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

我试过多种办法

1.更多设置 里面无法更改端口，灰花。
<img width="497" alt="image" src="https://github.com/MetaCubeX/Clash.Meta/assets/44893500/4571692b-0275-4d68-a92b-8458b1c06d9d">

2.修改文件 ~/.config/clash.meta/config.yaml，不生效
<img width="459" alt="image" src="https://github.com/MetaCubeX/Clash.Meta/assets/44893500/ede8490f-642f-40ad-a55b-6fa8eb07c818">

3.打开https://yacd.metacubex.one/#/configs             修改端口有效，但是重启软件后端口恢复7890

### Possible Solution

本人使用的clash x pro，可以在 更多设置 里面设置端口。

**Comment by xishang0128** [comment]
@jymr92 这不是clash.meta的bug,发clashx.meta仓库
