### ISSUE TITLE
IPv6 后缀匹配支持

### ISSUE THREAD

**Issue by EkkoG** [MetaCubeX/Clash.Meta#72]
目标，支持如下配置方式

```
- SRC-IP-CIDR,::b1b/-64,DIRECT
```

运营商通常会分配一下 /56 的前缀地址，设备出口 IP 会不断的变化，造成无法使用前缀来进行准确的规则匹配

通常设备的 IPv6 地址后缀是固定的，https://ccie.lol/knowledge-base/ipv6-use-eui-64-convert-link-local-address/

所以可以根据后缀匹配，之前在上游提过一个 PR，不过没有合并 https://github.com/Dreamacro/clash/pull/1329

另外观察到现在地址匹配用了新的包 netip，之前的修改是基于旧实现改的

**Comment by MetaCubeX** [comment]
@EkkoG 你可以pr到这边😬

**Comment by Adlyq** [comment]
@EkkoG 建议修改下pr到这里，ipcidr,::1234/-16,direct
表示后16位匹配

**Comment by Adlyq** [comment]
@Adlyq 算了，我写吧

**Comment by EkkoG** [comment]
<img width="1188" alt="CleanShot 2022-06-03 at 14 09 23@2x" src="https://user-images.githubusercontent.com/3138493/171797059-7ca4d98a-b656-4908-a693-de099a942bb0.png">

已经用上了，感谢！辛苦！

**Comment by MetaCubeX** [comment]
@EkkoG 有其他好建议且有能力写的，欢迎直接pr
