### ISSUE TITLE
[功能请求]希望添加Hysteria 2的支持

### ISSUE THREAD

**Issue by Moexin** [MetaCubeX/Clash.Meta#720]
Hysteria那边已经更新到2.0了，但是并不能向下兼容，所以一旦Hysteria更新到了2.0及以上版本，Clash.Meta就无法连接了。

**Comment by STEVENTAN100** [comment]
hysteria2的安卓插件我没有找到在哪里下载，不过这次更新是挺突然的

**Comment by Moexin** [comment]
> hysteria2的安卓插件我没有找到在哪里下载，不过这次更新是挺突然的

只能等各位大佬更新适配了，在此期间只能用1.x.x版本先顶着了

**Comment by bladethirst** [comment]
相比hysteria1,用它的客户端测试了一下，hysteria2速度更快，希望项目组能够早日适配hysteria2，感谢

**Comment by lchecho** [comment]
+1，希望能支持，谢谢

**Comment by houpi** [comment]
+1，希望能支持，谢谢

**Comment by CberYellowstone** [comment]
围观，持续关注

**Comment by Misaka-blog** [comment]
希望能尽快支持

**Comment by rgshendong** [comment]
+1

**Comment by ZevAlain** [comment]
+1 关注

**Comment by baiyigumeng** [comment]
+1

**Comment by makessr** [comment]
持续关注

**Comment by CUWorld** [comment]
+1

**Comment by Entoryvekum** [comment]
+1

**Comment by cytown** [comment]
+1

**Comment by mewtwo-git** [comment]
+1

**Comment by hubumulity** [comment]
+1

**Comment by wwqgtxx** [comment]
fixed by https://github.com/MetaCubeX/Clash.Meta/commit/9b8e2d93435dcd13b9266c6213557c6230fc1c61

**Comment by JianleiZhang** [comment]
#hysteria2
  - name: "hysteria2"
    type: hysteria2
    server: server.com
    port: 443
    #  up和down均不写或为0则使用BBR流控
    # up: "30 Mbps" # 若不写单位，默认为 Mbps
    # down: "200 Mbps" # 若不写单位，默认为 Mbps
    password: yourpassword
    # obfs: salamander # 默认为空，如果填写则开启obfs，目前仅支持salamander
    # obfs-password: yourpassword
    # sni: server.com
    # skip-cert-verify: false
    # fingerprint: xxxx
    # alpn:
    #   - h3
    # ca: "./my.ca"
    # ca-str: "xyz"

**Comment by imhansai** [comment]
https://v2.hysteria.network/zh/docs/advanced/Port-Hopping/

蹲端口跳跃特性

**Comment by wwqgtxx** [comment]
@imhansai 不会支持

**Comment by firewiki** [comment]
> @imhansai 不会支持

@wwqgtxx 想知道不会支持的原因.

**Comment by tianzhuwei** [comment]
> @imhansai 不会支持

是因为什么原因不打算进行支持呢？

**Comment by DoiiarX** [comment]
凉

**Comment by Meow7575** [comment]
> > @imhansai 不会支持
> 
> 是因为什么原因不打算进行支持呢？

~~因为没啥用吧~~
