### ISSUE TITLE
Macbook i5, meta用哪个版本替换？

### ISSUE THREAD

**Issue by tulio2833466386** [MetaCubeX/Clash.Meta#722]
Macbook i5, 用哪个版本替换？clash.meta-linux-amd64-compatible-v1.15.1.gz？？

**Comment by covenant-stars** [comment]
MacBook如果用的是MacOS的话你应该去用darwin而不是linux
如果你用的是其他的系统那么用对应的核心（能用标准版就不用兼容compatible）

**Comment by tulio2833466386** [comment]
•	clash.meta-darwin-amd64-cgo-v1.15.1.gz   clash.meta-darwin-amd64-v1.15.1.gz   clash.meta-darwin-arm64-cgo-v1.15.1.gz   [clash.meta-darwin-arm64-v1.15.1.gz]
