### ISSUE TITLE
请问如何linux部署webui的控制界面？docker hub拉取的镜像好像只是核心程序

### ISSUE THREAD

**Issue by r81892489** [MetaCubeX/Clash.Meta#723]
拉取了docker镜像不知道如何使用，想在docker里部署自动定期拉取yam配置信息，meta版不知道怎么操作了。。没有控制面板没有docker参数，请教有相关的教程或者指导吗？windows一样替换核心是否可行？

**Comment by r81892489** [comment]
以解决，是yaml合适不对，套用官网wiki的配置已经成功运行了。

**Comment by shuaixiaomi** [comment]
大佬，可以看下你的docker是怎么部署的吗
