### ISSUE TITLE
apple 备忘录无法同步 

### ISSUE THREAD

**Issue by fredericky123** [MetaCubeX/Clash.Meta#729]
已经在规则里设置了apple,direct 请问为何备忘录只有在退出clash时才会自动同步？
需要把具体的同步网址再写一下么？
  apple:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

**Comment by stevejohnson7** [comment]
自行检查规则设置问题
