### ISSUE TITLE
使用mate内核或新版内核 手游分流异常

### ISSUE THREAD

**Issue by sniper3209** [MetaCubeX/Clash.Meta#73]
新版mate内核或DEV内核都存在手游分流异常的问题，主要是针对《和平精英》，进不去服务器，或者网络波动异常，或者与服务器通讯时断时续，严重影响运行。目前不使用mate内核，DEV内核回滚至v1.7.1-5-gced9749，fake-ip增强模式，游戏基本正常！恳请作者予以关注，谢谢！！！

**Comment by Adlyq** [comment]
@sniper3209 贴你规则出来

**Comment by vj23456** [comment]
@sniper3209 不要用fake ip游戏

**Comment by sniper3209** [comment]
> @sniper3209贴你规则出来

规则使用的是ACL4SSR规则在线完整Netflix，没用第三方规则。

**Comment by sniper3209** [comment]
> @sniper3209不要用fake ip游戏

redir-host到是试过了，比fake ip好些，但也还是会时不时的抽风，关键是看netfilx和disney+用fake ip速度杠杠滴，但是手游又不行，不能兼顾好伤心

**Comment by Adlyq** [comment]
@sniper3209 你试一下直全局走直连。如果正常的话证明是你规则有问题。

**Comment by vj23456** [comment]
@sniper3209 网飞用redirhost开sniffer

**Comment by sniper3209** [comment]
sniffer是什么？我不太懂，还请指教，非常感谢

**Comment by sniper3209** [comment]
> @sniper3209 你试一下直全局走直连。如果正常的话证明是你规则有问题。

好的，我试试

**Comment by vj23456** [comment]
@sniper3209 看wiki

**Comment by vj23456** [comment]
@sniper3209 https://docs.metacubex.one/

**Comment by sniper3209** [comment]
> @sniper3209 你试一下直全局走直连。如果正常的话证明是你规则有问题。

刚才测试了，问题复现。

**Comment by Adlyq** [comment]
@sniper3209 有日志吗

**Comment by sniper3209** [comment]
> @sniper3209 有日志吗
开始没有启动日志，目前状态：不使用mate内核，DEV内核回滚至v1.7.1-5-gced9749，fake-ip增强模式，游戏基本正常！奈飞正常，disney+正常，速度也不错。我觉得达到目的了。后续再有新版本的话，我开日志，如果问题复现，我再和大家分享一下

**Comment by akaet** [comment]
> @sniper3209 网飞用redirhost开sniffer

这样的话IPv6是不是就不能用了？
