### ISSUE TITLE
sniffer下的override-destination选项不生效

### ISSUE THREAD

**Issue by InspoOnU** [MetaCubeX/Clash.Meta#733]
使用最新alpha版本，配置文件如下：
- name: "sock"
  type: socks5
  server: 
  port: 52541
  udp: true
dns:
  enable: false
sniffer:
  enable: false
  force-dns-mapping: false
  parse-pure-ip: false
  override-destination: false
  sniff:
    TLS:
      ports: [443]
    HTTP:
      ports: [80]

客户端用的是tun模式，Clash Meta还是会把嗅探到的域名传到socks5服务端，而不是本来的目标IP

**Comment by InspoOnU** [comment]
> 这个好像就是这么设计的 想传ip可以用sing-box

不是这样设计的吧，不然这选项就没意义了

**Comment by xishang0128** [comment]
tun会进行dns劫持,无需嗅探,依旧可以获得域名,依旧会发送域名,而不是ip

**Comment by InspoOnU** [comment]
> tun会进行dns劫持,无需嗅探,依旧可以获得域名,依旧会发送域名,而不是ip

不是这个原因，关掉sniffer就发IP了
