### ISSUE TITLE
安卓下Clash Meta核心在蜂窝数据网络下无法连接tuic服务器

### ISSUE THREAD

**Issue by reF1nd** [MetaCubeX/Clash.Meta#740]
Android13，root之后跑clash-meta裸核，版本为Alpha-7286391。在蜂窝数据网络下使用tuic服务器会疯狂断流，虽然偶尔能连上，几乎处于不可用的状态。

在蜂窝数据网络下抓取日志，出现大量此错误：
`time="2023-09-08T12:47:25.6802971Z" level=warning msg="[TCP] dial GLOBAL 127.0.0.1:45114 --> 149.154.175.100:443 error: INTERNAL_ERROR (local): write udp [::]:37055->服务器IP:端口: sendmsg: invalid argument"`

但是Wi-Fi下tuic不会遇到此问题，蜂窝数据网络下用其他TCP协议（测试过vless, shadowsocks）也没问题。

Clash-Meta正式版v1.15.1无此问题。

**Comment by ArchGuyWu** [comment]
@reF1nd 这个改小点试试？https://wiki.metacubex.one/config/general/#tcp-keep-alive

**Comment by reF1nd** [comment]
@ArchGuyWu 测试了，没有效果。我改成1也没用。

**Comment by ahdiua** [comment]
用sing-box遇到过一样的问题，可以参考下https://github.com/SagerNet/sing-box/issues/821

**Comment by reF1nd** [comment]
@ahdiua 破案了，确实是GSO的问题，用环境变量关闭了就好了。那么问题来了，我有root我可以改环境变量，那么没有root权限的CMFA用户怎么办？

**Comment by ahdiua** [comment]
> @ahdiua 破案了，确实是GSO的问题，用环境变量关闭了就好了。
> 
> 那么问题来了，我有root我可以改环境变量，那么没有root权限的CMFA用户怎么办？

或许在CFMA里加一个GSO的开关？更狠一点编译时禁用掉GSO

**Comment by NevadaCities** [comment]
@ahdiua 去Clash.Meta看Commit已经加了新的实验性开关了 https://github.com/MetaCubeX/Clash.Meta/commit/90acce7fa15884eabd8ee8f0783cdc26b9d1c6ab
