### ISSUE TITLE
[ReOpen ]对代理服务器的域名进行DNS请求十分频繁

### ISSUE THREAD

**Issue by 0xCandy** [MetaCubeX/Clash.Meta#748]
很多机场提供的代理服务器都是域名，每次通过该服务器链接外网时都会对代理服务器的域名进行DNS请求，这种请求是通过直连的方式获取的，并且这种DNS请求非常频繁（如果经常使用代理），这种奇怪的请求也可能被被其他DNS服务器（非本机）记录下来，从而被针对。

我想能否将代理服务器的域名与IP地址记录在本地，每次使用代理服务器时，直接使用域名即可，所以每个代理服务器只需一次DNS请求即可，这样不仅能够降低延迟，还更加安全。

参考 [#743](https://github.com/MetaCubeX/Clash.Meta/issues/743#issue-1889718966)

**Comment by Skyxim** [comment]
#741
