### ISSUE TITLE
[Feature Request] 请求支持Hysteria 2

### ISSUE THREAD

**Issue by istek** [MetaCubeX/Clash.Meta#756]
请求支持。谢谢。

**Comment by Skyxim** [comment]
@nick008a 你到底看过 hy2 说明没

**Comment by istek** [comment]
![image](https://github.com/MetaCubeX/Clash.Meta/assets/8424803/e1626487-d2a4-4d83-b90c-fabecc695549)
@nick008a

**Comment by Larvan2** [comment]
duplicate
