### ISSUE TITLE
从gitlab导入自己的yaml文件提示错误

### ISSUE THREAD

**Issue by vm669** [MetaCubeX/Clash.Meta#757]
Clash Meta for Android从gitlab导入自己的yaml文件提示错误
信息是profile dose not contain `proxies` or `proxy-providers`
，可是直接用文件导入却可以使用

请教

proxies:
#==============================（wireguard节点）
  - {"name":"wg_24pb_1","type":"wireguard","server":"188.114.98.134","port":2371,"udp":true,"ip":"172.16.0.2","ipv6":"2606:4700:110:8c6f:f3d8:9ad3:aab5:f187","private-key":"EE3GP0MMmIK88OsoB1vxHAR6VuQWSlNW28oOp96zsFw=","public-key":"bmXOC+F1FxEMF9dyiK2H8/1SUtzH0JuVo51h2wPfgyo=","dns":["1.1.1.1","1.0.0.1"],"mtu":1280,"remote-dns-resolve":true}

proxy-groups:
  - name: 🚀 节点选择
    type: select
    proxies:
      - ♻️ 自动选择
      - DIRECT
      - 🔮 负载均衡-CF_WG节点                  #CF_WireGuard-节点，负载均衡-散列

**Comment by stevejohnson7** [comment]
链接错了？用浏览器打开看看能不能正常看到节点信息

**Comment by qgshaha** [comment]
我用Clash for Android会出现这个问题，换成Clash Meta for Android就没问题了

**Comment by yzgolden86** [comment]
是的，我用的就是clash meta for android ，我后来排查了一下发现了问题，原来是配置文件的名字中不能用空格，我把空格删除后，就可以通过URL导入了

**Comment by tinydoot** [comment]
我的两个手机，同样的app版本，一个可以，另外一个突然就不行了

**Comment by xiangyingchang** [comment]
”配置文件的名字“具体是指什么呀？

**Comment by wmsxwddd** [comment]
> ”配置文件的名字“具体是指什么呀？
应该是订阅链接吧。我也遇到这个问题，发现是订阅链接带空格了。删除空格就正常了

**Comment by Marshall1115** [comment]
我的是机场到期了，才发现
