### ISSUE TITLE
[Feature] 是否为tuic v5添加端口跳跃

### ISSUE THREAD

**Issue by nkta3m** [MetaCubeX/Clash.Meta#766]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

为tuic v5 添加端口跳跃，以避免单一端口被运营商QoS。

**Comment by PuerNya** [comment]
@nkta3m 协议不支持
