### ISSUE TITLE
proxy-providers:模式下怎么样让节点出现在全局

### ISSUE THREAD

**Issue by vvyoko** [MetaCubeX/Clash.Meta#787]
使用 https://wiki.metacubex.one/example/#meta 的配置
然后全局不像正常订阅的那样显示所有结点

而只显示proxies下节点以及proxy-groups下的所有代理集合,甚至连DIRECT和REJECT都显示了...
目前就操作很奇怪
代理集合需要先在规则中指定集合先选中节点,然后才能在全局中使用...
当然有个好处就是全局里也能有自动选择了

有没有什么配置能够控制让proxy-providers下所有节点都显示在全局
以及控制proxy-groups下的集合是否显示在全局的?

如图,不显示订阅节点只显示集合了
![20231010161134](https://github.com/MetaCubeX/Clash.Meta/assets/2145741/64e8be84-61e9-42d1-ab5f-387999ba60e3)

**Comment by stevejohnson7** [comment]
这个好像是clash-verge特地写成这样的，之前用cfw的时候就不会这样。可能要去clash-verge那边反馈
