### ISSUE TITLE
[Bug] Mac版不能启用最新Meta核心

### ISSUE THREAD

**Issue by lukaschan** [MetaCubeX/Clash.Meta#788]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.3.7

### What OS are you seeing the problem on?

macOS

### Clash config

```yaml
不涉及
```

### Description

从Clash.Meta核心github下载最新Darwin核心，命名为clash-meta后，替换到 APP/contents/MacOS目录。重新启动verge，到core界面无法启用Meta核心。

是姿势不对？

**Comment by a904055262** [comment]
time="2023-10-10T18:08:52.181385512+08:00" level=info msg="Start initial configuration in progress"
panic: non-positive interval for NewTicker

goroutine 21 [running]:
time.NewTicker(0x0?)
        time/tick.go:22 +0xe5
github.com/Dreamacro/clash/adapter/provider.(*HealthCheck).process(0xc0001365a0)
        github.com/Dreamacro/clash/adapter/provider/healthcheck.go:53 +0x34
created by github.com/Dreamacro/clash/adapter/provider.NewProxySetProvider in goroutine 1
        github.com/Dreamacro/clash/adapter/provider/provider.go:186 +0x2cb

因为最新alpha本来就坏了

**Comment by a904055262** [comment]
time="2023-10-10T18:08:52.181385512+08:00" level=info msg="Start initial configuration in progress"
panic: non-positive interval for NewTicker

goroutine 21 [running]:
time.NewTicker(0x0?)
        time/tick.go:22 +0xe5
github.com/Dreamacro/clash/adapter/provider.(*HealthCheck).process(0xc0001365a0)
        github.com/Dreamacro/clash/adapter/provider/healthcheck.go:53 +0x34
created by github.com/Dreamacro/clash/adapter/provider.NewProxySetProvider in goroutine 1
        github.com/Dreamacro/clash/adapter/provider/provider.go:186 +0x2cb

因为最新alpha本来就坏了

**Comment by jinhuaitao** [comment]
+1

**Comment by Ssiswent** [comment]
你好，请问你在macOS上是如何使用服务的呢，我看wiki似乎只有Linux的运行教程
https://wiki.metacubex.one/startup/service/

**Comment by Ssiswent** [comment]
> macos14 clash-meta核心直接启动可用并无任何问题，API用的是metacubexd Dashboard。如果你用的是客户端那就等作者更新吧

你好，请问你在macOS上是如何使用服务的呢，我看wiki似乎只有Linux的运行教程
https://wiki.metacubex.one/startup/service/
