### ISSUE TITLE
[Feature] 和原clash内核unfork分离

### ISSUE THREAD

**Issue by stevejohnson7** [MetaCubeX/Clash.Meta#789]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

meta内核和原版内核分道扬镳已久，应该可以unfork了。unfork可以解决一些现有问题：
- GitHub搜索项目名称搜索不到，不利于开发者发现项目
- 主页可以更好地显示贡献者和Used by信息
- 发起新PR时不会被引导到原项目，引起困惑

### Possible Solution

https://support.github.com/contact?flow=detach_fork&subject=Detach%20Fork&tags=rr-forks
（参见 https://zhuanlan.zhihu.com/p/480715624 ）

**Comment by lux5am** [comment]
no

**Comment by cy18** [comment]
我说怎么github里面搜了半天搜不到项目，原来是fork的关系...

**Comment by 8MiYile** [comment]
> 我说怎么github里面搜了半天搜不到项目，原来是fork的关系...

还好我是直接记住了组织名称 在URL内输入 github.com/MetaCubeX 就能找到。。。

**Comment by 8MiYile** [comment]
@stevejohnson7 那个 打一个 not planted 的 关闭 issues...
