### ISSUE TITLE
版本号问题

### ISSUE THREAD

**Issue by wangjianpro999** [MetaCubeX/Clash.Meta#79]
![Screenshot_2022-06-08-06-36-53-131_com microsoft emmx](https://user-images.githubusercontent.com/79621192/172494769-3fcc7c9b-354d-4b82-bbef-49433d7aabc9.jpg)

![Screenshot_2022-06-08-06-37-02-333_com microsoft emmx](https://user-images.githubusercontent.com/79621192/172494792-1b77ebae-6a81-4032-b1aa-e285e68c00d9.jpg)

以上三个版本究竟哪个最新？建议更改版本命名规则，便于分清版本顺序。
此外，r2s的404大佬用的是哪里的版本？版本号为什么与此页面上的不同？

**Comment by vj23456** [comment]
@wangjianpro999 aplpha为每次pr自动编译版本，版本号为每次的commits，自动覆盖上一版本

你插件里没有同步meta的最新版本

**Comment by wangjianpro999** [comment]
我不知道504大佬的固件用的版本为什么与这里的不一致，所以我也不知道哪个版本新

vj23456 ***@***.***> 于 2022年6月8日周三 07:33写道：

**Comment by Skyxim** [comment]
@wangjianpro999 肯定是 github看到的最新 不过 这个 最好别最 毕竟是自动更新 有什么问题不好搞 你可以看看beta和 vx.x.x这些版本

**Comment by wangjianpro999** [comment]
我不知道404大佬的固件用的版本为什么与这里的不一致，所以我也不知道哪个版本新，但是我依然喜欢用最新版


Skyxim ***@***.***> 于 2022年6月8日周三 07:41写道：

**Comment by Skyxim** [comment]
正如 @vj23456 所说 alpha 它和beta版本不保留历史 这两个只是测试版。vx.x.x才会保留
