### ISSUE TITLE
[Feature] 增加新功能，从机场订阅下载配置文件时，将Subscription-Userinfo 增加到配置文件中

### ISSUE THREAD

**Issue by JMVoid** [MetaCubeX/Clash.Meta#792]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

当从机场下载clash配置文件时，不论是在直接下载配置文件，还是从proxy-provider. 如果机场已经在http header中有Subscription-Userinfo信息时，将该属性添加到下载回来的配置文件中。并且在proxy provider中增加Subscription-Userinfo属性。这样可以让用户直接掌握机场的使用情况

**Comment by xishang0128** [comment]
provider已有流量信息,自行从api获取
