### ISSUE TITLE
[Feature] 为 Clash Meta for Android 配置依赖与内核自动更新

### ISSUE THREAD

**Issue by stevejohnson7** [MetaCubeX/Clash.Meta#799]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

尝试在缺乏维护者的情况下暂时维持meta for android运转。计划写github actions 自动更新golang依赖和内核版本，根据内核升级自动推送新版。

**Comment by cnxianyi** [comment]
同问，再问问如果自己编译的话第一步 `git submodule update --init --recursive` 出现：
```
git submodule update --init --recursive                                        (main✱)
fatal: remote error: upload-pack: not our ref f91418967ebda8aab1c5952ee93c26acee5956be
fatal: Fetched in submodule path 'core/src/foss/golang/clash', but it did not contain f91418967ebda8aab1c5952ee93c26acee5956be. Direct fetching of that commit failed.
```
错误该怎么办/(ㄒoㄒ)/~~

**Comment by qist** [comment]
@cnxianyi  你要修改一下代码才可以默认使用的是android-open 分支的。`git submodule update --force --recursive --init --remote`

**Comment by stevejohnson7** [comment]
> @qist 又有新问题：最终构建时`./gradlew app:assembleMeta-AlphaRelease` 提示：
> 
> ```
> % ./gradlew app:assembleMeta-AlphaRelease                                                                         1 ↵ ✹
> 
> > Configure project :core
> Checking the license for package SDK Patch Applier v4 in /opt/android-sdk/licenses
> Warning: License for package SDK Patch Applier v4 not accepted.
> Checking the license for package NDK (Side by side) 23.0.7599858 in /opt/android-sdk/licenses
> Warning: License for package NDK (Side by side) 23.0.7599858 not accepted.
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem occurred configuring project ':core'.
> > com.android.builder.sdk.LicenceNotAcceptedException: Failed to install the following Android SDK packages as some licences have not been accepted.
>      ndk;23.0.7599858 NDK (Side by side) 23.0.7599858
>      patcher;v4 SDK Patch Applier v4
>   To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
>   Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
> 
>   Using Android SDK: /opt/android-sdk
> 
> * Try:
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 731ms
> ```
> 
> 现在jdk是安装的 jdk17
> 
> ```
> % java --version                                                                                                  1 ↵ ✹
> openjdk 17.0.8 2023-07-18
> OpenJDK Runtime Environment (build 17.0.8+7-Debian-1deb12u1)
> OpenJDK 64-Bit Server VM (build 17.0.8+7-Debian-1deb12u1, mixed mode, sharing)
> ```
> 
> 安装openjdk 11 构建会提示jdk版本过低 就装了jdk17
> 
> 许可证 `sdkmanager --licenses` 也都选y了 版本是官网最新的：
> 
> ```
> sdkmanager --version                                                                                                ✹
> 11.0
> ```
> 
> 构建不出来了又
> 
> 对了我是用的wsl2 debian12 会有影响吗

构建的话其实github actions已经写好了，可以commit之后直接从actions拿，不需要咱们本地编译。

**Comment by cnxianyi** [comment]
@stevejohnson7 fork完 直接在actions build_release Run workflow吗 需要修改默认分支android-open吗

**Comment by cnxianyi** [comment]
@stevejohnson7 构建了两次都是
```
[BuildRelease](https://github.com/cnxianyi/ClashMetaForAndroid/actions/runs/6535803867/job/17746054880#step:8:274)
Gradle build failed: see console output for details
```

**Comment by stevejohnson7** [comment]
有点麻烦了。。这android-open分支是单独维护的啊。。
那光这边GUI编译起来恐怕不够，那边内核也得有人维护更新才行

**Comment by stevejohnson7** [comment]
alpha和android-open两个分支的区别是啥，为啥要分开维护emm
问问@stitchrs

**Comment by stevejohnson7** [comment]
现在两个分支的内核在`./core/src/foss/golang/`跑`go mod tidy`都报错

**Comment by cnxianyi** [comment]
怎么样能编译出新版了不

**Comment by stevejohnson7** [comment]
> 怎么样能编译出新版了不

依赖更新搞定了，等会试试编译。
不过我这里把内核切到Alpha分支了，貌似有一些安卓的patch要单独补一下。我后面再问问维护者

**Comment by stevejohnson7** [comment]
Help wanted:
最近较忙，没太多时间深入读源码，切到Alpha之后编译有一些问题，希望大佬们可以帮忙看看
https://github.com/stevejohnson7/ClashMetaForAndroid/actions/runs/6583035264/job/17885437919?pr=7

**Comment by Larvan2** [comment]
android-open 同步到 alpha了，可以尝试测试

**Comment by stevejohnson7** [comment]
> android-open 同步到 alpha了，可以尝试测试

巧了，正好刚刚也在本地把android rebase了之后在测编译。不过还是有些小问题
![image](https://github.com/MetaCubeX/Clash.Meta/assets/144257728/68fe4b31-a302-496c-846c-5483c41941cf)

**Comment by stevejohnson7** [comment]
代码里有一些新旧并存的情况，非常奇怪。以第一个http.go:19:51的报错为例：
main下调用处的代码为：
![image](https://github.com/MetaCubeX/Clash.Meta/assets/144257728/8c0e1055-0347-42d3-b120-c57dca0da2ee)

但是clash core中对应的接口为：
![image](https://github.com/MetaCubeX/Clash.Meta/assets/144257728/ed75058e-150e-4602-a599-9aed0f719056)

显然数据类型不对。而在Kr238对clash的patch里面（https://github.com/Kr328/clash/commit/8e209eb9f7eb43046cab2429766b61fb6a1c1341 ）已经将`NewWithAuthenticate`的数据类型修正过了：
![image](https://github.com/MetaCubeX/Clash.Meta/assets/144257728/a41f9979-3c81-4e39-9dc0-6cfa0770d363)

目测是Clash.Meta android-open分支的patch未打完善造成？
刚刚修复的一个配置文件缺失成员的问题也是因为类似的原因（https://github.com/stevejohnson7/Clash.Meta/commit/5f531447b78a10a2f7031bd13f6b744b491e48d3）

**Comment by stevejohnson7** [comment]
> 代码里有一些新旧并存的情况，非常奇怪。以第一个http.go:19:51的报错为例： main下调用处的代码为： ![image](https://user-images.githubusercontent.com/144257728/277121002-8c0e1055-0347-42d3-b120-c57dca0da2ee.png)
> 
> 但是clash core中（android-open分支）对应的接口为： ![image](https://user-images.githubusercontent.com/144257728/277121258-ed75058e-150e-4602-a599-9aed0f719056.png)
> 
> 显然数据类型不对。而在Kr238对clash的patch里面（[Kr328@8e209eb](https://github.com/Kr328/clash/commit/8e209eb9f7eb43046cab2429766b61fb6a1c1341) ）已经将`NewWithAuthenticate`的数据类型修正过了，连带着后面修改了很多类似的逻辑： ![image](https://user-images.githubusercontent.com/144257728/277121480-a41f9979-3c81-4e39-9dc0-6cfa0770d363.png)
> 
> 所以是Clash.Meta android-open分支的patch未打完善造成？团队里面有无熟悉相关内容的维护者能帮忙看看是啥情况 刚刚修复的一个配置文件缺失成员的问题也是因为类似的原因（[stevejohnson7@5f531447b78a10a2f7031bd13f6b744b491e48d3）](https://github.com/stevejohnson7/Clash.Meta/commit/5f531447b78a10a2f7031bd13f6b744b491e48d3）) 

补：
`tun.go:153:22`也是同样的原因，接口和代码不协调。

**Comment by stevejohnson7** [comment]
编译已通过
https://github.com/stevejohnson7/ClashMetaForAndroid/actions/runs/6601370255

希望可以尽快合并此PR #812

**Comment by stevejohnson7** [comment]
https://github.com/MetaCubeX/ClashMetaForAndroid/pull/147

**Comment by stevejohnson7** [comment]
> 大佬，今天能打包一个版本出来么？
稍等，应该可以

**Comment by cnxianyi** [comment]
厉害啊666666

**Comment by stevejohnson7** [comment]
> 大佬，今天能打包一个版本出来么？

wwqgtxx说先修修bug再发新版，再等等吧。目前直接去github release下最新的pre-release就行，昨天晚上更新过了

**Comment by stevejohnson7** [comment]
> > wwqgtxx说先修修bug再发新版，再等等吧。目前直接去github release下最新的pre-release就行，昨天晚上更新过了
> 
> 这个能修吗？ [MetaCubeX/ClashMetaForAndroid#154](https://github.com/MetaCubeX/ClashMetaForAndroid/issues/154)
> 
> CMFA 用着用着会无法上网，不知道是不是这个的原因？手机移动网都是有 IPv6 的，如果解析到 IPv6，tun 设备接收不了，就无法上网。

@wwqgtxx
