### ISSUE TITLE
error: not rule must contain one rule

### ISSUE THREAD

**Issue by htfcuddles** [MetaCubeX/Clash.Meta#80]
### 规则如下：

`AND,((SRC-IP-CIDR,192.168.2.192/26),(OR,(NETWORK,TCP),(NOT,(DST-PORT,123)))),REJECT`
在最新版中报错：_error: not rule must contain one rule_

### 截图如下：

<img width="322" alt="image" src="https://user-images.githubusercontent.com/23210827/172667402-9034a4dc-dc1f-447a-a474-7989e28576a7.png">

### 版本为alpha-g01d2e88（来自OpenClash），之前版本可以正常使用

**Comment by MetaCubeX** [comment]
@htfcuddles 你除了and的括号，里面的OR和NOT都好了个括号

**Comment by MetaCubeX** [comment]
@htfcuddles 少了个括号

**Comment by htfcuddles** [comment]
@MetaCubeX 感谢回复，应该是之前版本没检测出语法错误，  0e1601e5b60f123dac82970b6c37fbf0e70d6dc8 修复了
