### ISSUE TITLE
[Feature] 能不能让clash内置的DNS向系统DNS发起请求

### ISSUE THREAD

**Issue by Ohdmire** [MetaCubeX/Clash.Meta#802]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

这个问题在原版clash就提出来过
https://github.com/Dreamacro/clash/issues/908

在开启内置的DNS后，没有找到向系统DNS发起请求的选项

上游的一些公共DNS解析在部分情况下是不如运营商的DNS解析的，使用运营商的DNS会有CDN优化。
所以我想在访问国内网站的时候使用运营商的DNS，被污染了再使用223.5.5.5等公共DNS

所以我想是否能添加一个向系统发起DNS请求的字段

**Comment by Ohdmire** [comment]
感谢

**Comment by covenant-stars** [comment]
@Ohdmire default-nameserver:
    - system

**Comment by walterclozet** [comment]
> [@Ohdmire](https://github.com/Ohdmire) default-nameserver: - system
在安卓上不能使用-system
{"type":"debug","payload":"[DNS] resolve g.alicdn.com A from system()"}
{"type":"warning","payload":"[TCP] dial DIRECT (match RuleSet/Free) 28.0.0.1:51928 --\u003e g.alicdn.com:443 error: dns resolve failed: all DNS requests failed, first error: failed to read /etc/resolv.conf: open /etc/resolv.conf: no such file or directory"}

**Comment by PoseidonWake** [comment]
> > [@Ohdmire](https://github.com/Ohdmire) default-nameserver: - system
> > 在安卓上不能使用-system
> > {"type":"debug","payload":"[DNS] resolve g.alicdn.com A from system()"}
> > {"type":"warning","payload":"[TCP] dial DIRECT (match RuleSet/Free) 28.0.0.1:51928 --\u003e g.alicdn.com:443 error: dns resolve failed: all DNS requests failed, first error: failed to read /etc/resolv.conf: open /etc/resolv.conf: no such file or directory"}

@walterclozet 安卓上确实用不了， 请问您有解决方法了吗
