### ISSUE TITLE
[Feature] 不支持(非错误的配置)的协议能否只是警告，而非报错？

### ISSUE THREAD

**Issue by arkxfly** [MetaCubeX/Clash.Meta#807]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

在低版本 clash meta 内核，订阅中有一些代理是新协议 tuic/hy2，低版本内核不支持该协议，结果报错无法更新订阅。

其实还是有其他可用的协议的，不用报错。安卓版就是因为内核版本低，而又没有采用新版内核的版本。

希望可以有这个功能，解决后续类似这种情况。

### Possible Solution

忽略不支持的协议，打印警告日志。

**Comment by stevejohnson7** [comment]
安卓已经升级到最新版内核，支持所有新协议。可以前往https://github.com/MetaCubeX/ClashMetaForAndroid/releases/tag/Prerelease-alpha下载使用
