### ISSUE TITLE
[Feature] 项目中android-open和Alpha分支的差别

### ISSUE THREAD

**Issue by stevejohnson7** [MetaCubeX/Clash.Meta#808]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

计划为Meta for Android做自动依赖更新，以维持项目继续维护。

发现目前Meta for Android使用的是内核的android-open分支，刚看了一下，此分支已经落后主分支Alpha较多，如果后续需要一直手动从Alpha合并提交的话可能比较麻烦。
想问一下能否将Alpha分支略加修改（比如打上android-open上的某些patch）后直接用于Meta for Android编译？

**Comment by stevejohnson7** [comment]
@wwqgtxx  @stitchrs @riolurs

**Comment by Larvan2** [comment]
android-open 同步到alpha了，可以再试一下

**Comment by Larvan2** [comment]
duplicated https://github.com/MetaCubeX/Clash.Meta/issues/799
