### ISSUE TITLE
[Feature] Why we are all using geosite, and what are the advantages?

### ISSUE THREAD

**Issue by Patriarchmeet** [MetaCubeX/Clash.Meta#827]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

Clash.Meta supports v2ray-format geosite rules, and so many examples are using geosite instead of rule-providers. Also, meta provides its own dat file at MetaCubeX/meta-rules-dat.

But as a user from Dreamacro clash, I found that `geosite.dat` has many disadvantages:
- Hard to read and edit manually, without any instruction or tutorial about how to do it on google.
- Neither clash-verge nor meta for android provide good support for geoip/geosite updates, whereas traditional rule-providers are already well supported. 
- From v2fly to Loyalsoldier to meta-rules-dat, none of these projects have provided full explanations of the contents of `geosite.dat`, but merely give examples and descriptions in README. This is extremely confusing, and one can only write rules by referring to existing examples and guessing on his own.
- It seems that geosite does not contains gfwlist, which is a more perfect solution for proxy tools. Rule matches only for a site's geographic information may lead to waste of traffic and is not necessary.

### Possible Solution

Considering the issues stated above, I'm confused that why geosite is used so widely in meta. In my opinion, the only possible explanation is that the wide-range usage of geosite in v2ray series can help reduceing maintenance pressure of clash rules. 

My proposed solution to this problem is: To convert the existing geosite data source into clash text-format rules with github actions, and then release rule-providers, which can solve the current lack of well-maintained clash rules and avoid the drawbacks of geosite.

**Comment by kkocdko** [comment]
The geosite is awesome and works well.

You should not edit geosite file but append your own DOMAIN-SUFFIX rules in the config file. Or you can regenerate the geosite file, for more, you can see the origin geosite repo.

About to use gfwlist instead, yeah, it's ok for your traffic saving purpose, however in china many foreign site was not fully banned by gfw but still has weak connectivity (the best example is github), we need these site to use proxy.

Maybe you can try to contribute the docs, and I think that the usage of geosite in default example is accetable.

**Comment by Skyxim** [comment]
Examples are just examples, you can use whatever method you want, I don't use geosite at all

**Comment by alpha-hypermox** [comment]
I don't quite understand why you created this issue. Based on your description, you've already looked into Loyalsoldier's GitHub repository, where the geosite file actually includes the gfwlist. It's labeled as `geosite:gfw`.

If you switch to the [release](https://github.com/Loyalsoldier/v2ray-rules-dat/tree/release) branch, you can see the daily updated txt files (which meets your readability requirements).

**Comment by CHIZI-0618** [comment]
> My proposed solution to this problem is: To convert the existing geosite data source into clash text-format rules with github actions, and then release rule-providers, which can solve the current lack of well-maintained clash rules and avoid the drawbacks of geosite.

https://github.com/Kr328/V2rayDomains2Clash

**Comment by Paulgudring** [comment]
My pal, [I almost got the right opposite idea of yours](https://github.com/MetaCubeX/mihomo/discussions/949) 😂. I do enjoy geox‘s tidyness and inclusiveness. It's better to offer an option, which makes meta a mixture of clash, v2ray, and sing-box. As for looking up, you can try [geo developed by Metacubex org](https://github.com/MetaCubeX/geo). 

An hindsight: now mihomo has supported upgrading geox (see #857) and some gui client has followed, while the guide provides an example for rule-set preferers -  and it nerves geox rule users like me. Rome wasnt built in one day, especially when there is great legacy of clash (and its gui clients, say, cfw and cfa).
