### ISSUE TITLE
Windows上用一段时间会崩溃

### ISSUE THREAD

**Issue by csy19960309** [MetaCubeX/Clash.Meta#83]
> runtime: marked free object in span 0x18fb15e6078, elemsize=576 freeindex=4 (bad use of unsafe.Pointer? try -d=checkptr)
> 0xc003df0000 alloc unmarked
> 0xc003df0240 alloc unmarked
> 0xc003df0480 alloc unmarked
> 0xc003df06c0 alloc unmarked
> 0xc003df0900 free  unmarked
> 0xc003df0b40 free  unmarked
> 0xc003df0d80 free  unmarked
> 0xc003df0fc0 free  unmarked
> 0xc003df1200 free  unmarked
> 0xc003df1440 free  unmarked
> 0xc003df1680 free  unmarked
> 0xc003df18c0 free  unmarked
> 0xc003df1b00 free  unmarked
> 0xc003df1d40 free  marked   zombie
> 0x000000c003df1d40:  0x0000000000000000  0x0000000000000000 
> 0x000000c003df1d50:  0x0000000000000000  0x0000000000000000 
> 0x000000c003df1d60:  0x0000000000000000  0x0000000000000000 
> 0x000000c003df1d70:  0x0000000000000000  0x0000000000000000 
> 0x000000c003df1d80:  0x0000000000000000  0x0000000000000000 
> 0x000000c003df1d90:  0x0000000000000000  0x0000000000000000 
> 0x000000c003df1da0:  0x0000000000000000  0x0000000000000000 
> 0x000000c003df1db0:  0x0000000000000000  0x0000000000000000 
> 0x000000c003df1dc0:  0x0000000000000000  0x0000000000000000 
> 0x000000c003df1dd0:  0x0000000000000000  0x0000000000000000 
> 0x000000c003df1de0:  0x0000000000000000  0x0000000000000000 
> 0x000000c003df1df0:  0x0000000000000000  0x0000000000000000 
> 0x000000c003df1e00:  0x0000000000000000  0x0000000000000000 
> 0x000000c003df1e10:  0x0000000000000000  0x0000000000000000 
> 0x000000c003df1e20:  0x0000000000000000  0x0000000000000000 
> 0x000000c003df1e30:  0x0000000000000000  0x0000000000000000 
> 0x000000c003df1e40:  0x0000000000000000  0x0000000000000000 
> 0x000000c003df1e50:  0x0000000000000000  0x0000000000000000 
> 0x000000c003df1e60:  0x0000000000000000  0x0000000000000000 
> 0x000000c003df1e70:  0x0000000000000000  0x0000000000000000 
> 0x000000c003df1e80:  0x0000000000000000  0x0000000000000000 
> 0x000000c003df1e90:  0x0000000000000000  0x0000000000000000 
> 0x000000c003df1ea0:  0x0000000000000000  0x0000000000000000 
> 0x000000c003df1eb0:  0x0000000000000000  0x0000000000000000 
> 0x000000c003df1ec0:  0x0000000000000000  0x0000000000000000 
> 0x000000c003df1ed0:  0x0000000000000000  0x0000000000000000 
> 0x000000c003df1ee0:  0x0000000000000000  0x0000000000000000 
> 0x000000c003df1ef0:  0x0000000000000000  0x0000000000000000 
> 0x000000c003df1f00:  0x0000000000000000  0x0000000000000000 
> 0x000000c003df1f10:  0x0000000000000000  0x0000000000000000 
> 0x000000c003df1f20:  0x0000000000000000  0x0000000000000000 
> 0x000000c003df1f30:  0x0000000000000000  0x0000000000000000 
> 0x000000c003df1f40:  0x59d75a7f89532d24  0x61758560425438b9 
> 0x000000c003df1f50:  0x422d060a5bfaa8cd  0x406c2180075edf39 
> 0x000000c003df1f60:  0x6fd3c6fbcde1a5d0  0x2bb18219c7d39b9b 
> 0x000000c003df1f70:  0x020cf2f4e89caadb  0xee4470d2ddefaabd 
> fatal error: found pointer to free object
> 
> runtime stack:
> runtime.throw({0xe5dc87?, 0xc003df1f80?})
> 	runtime/panic.go:992 +0x76
> runtime.(*mspan).reportZombies(0x18fb15e6078)
> 	runtime/mgcsweep.go:776 +0x2e5
> runtime.(*sweepLocked).sweep(0x0?, 0x0)
> 	runtime/mgcsweep.go:609 +0x846
> runtime.(*mcentral).uncacheSpan(0x3?, 0x18fb0f4bc78?)
> 	runtime/mcentral.go:226 +0xa9
> runtime.(*mcache).releaseAll(0x18f8a230eb8)
> 	runtime/mcache.go:259 +0x125
> runtime.(*mcache).prepareForSweep(0x18f8a230eb8)
> 	runtime/mcache.go:295 +0x39
> runtime.gcMarkTermination.func4.1(0x371efffd90?)
> 	runtime/mgc.go:1057 +0x1d
> runtime.forEachP(0xeab528)
> 	runtime/proc.go:1603 +0x11a
> runtime.gcMarkTermination.func4()
> 	runtime/mgc.go:1056 +0x25
> runtime.systemstack()
> 	runtime/asm_amd64.s:469 +0x4e
> 
> goroutine 34 [running]:
> runtime.systemstack_switch()
> 	runtime/asm_amd64.s:436 fp=0xc00050fd40 sp=0xc00050fd38 pc=0x461dc0
> runtime.gcMarkTermination(0x1683fe0?)
> 	runtime/mgc.go:1055 +0x5a9 fp=0xc00050fef8 sp=0xc00050fd40 pc=0x41b489
> runtime.gcMarkDone()
> 	runtime/mgc.go:904 +0x2cd fp=0xc00050ff58 sp=0xc00050fef8 pc=0x41ac4d
> runtime.gcBgMarkWorker()
> 	runtime/mgc.go:1331 +0x2e5 fp=0xc00050ffe0 sp=0xc00050ff58 pc=0x41bfa5
> runtime.goexit()
> 	runtime/asm_amd64.s:1571 +0x1 fp=0xc00050ffe8 sp=0xc00050ffe0 pc=0x464121
> created by runtime.gcBgMarkStartWorkers
> 	runtime/mgc.go:1131 +0x25
> 
> goroutine 1 [chan receive, 45 minutes]:
> main.main()
> 	github.com/Dreamacro/clash/main.go:120 +0x8df
> 
> goroutine 6 [chan receive, 1 minutes]:
> github.com/Dreamacro/clash/common/observable.(*Observable[...]).process(0xc000048560)
> 	github.com/Dreamacro/clash/common/observable/observable.go:16 +0x65
> created by github.com/Dreamacro/clash/common/observable.NewObservable[...]
> 	github.com/Dreamacro/clash/common/observable/observable.go:63 +0xcf
> 
> goroutine 7 [chan receive, 1 minutes]:
> github.com/Dreamacro/clash/tunnel/statistic.(*Manager).handle(0xc000070540)
> 	github.com/Dreamacro/clash/tunnel/statistic/manager.go:83 +0x93
> created by github.com/Dreamacro/clash/tunnel/statistic.init.0
> 	github.com/Dreamacro/clash/tunnel/statistic/manager.go:22 +0x17c
> 
> goroutine 8 [chan receive, 1 minutes]:
> github.com/Dreamacro/clash/tunnel.process()
> 	github.com/Dreamacro/clash/tunnel/tunnel.go:143 +0x85
> created by github.com/Dreamacro/clash/tunnel.init.0
> 	github.com/Dreamacro/clash/tunnel/tunnel.go:59 +0x25
> 
> goroutine 18 [chan receive]:
> github.com/Dreamacro/clash/tunnel.processUDP()
> 	github.com/Dreamacro/clash/tunnel/tunnel.go:128 +0x4d
> created by github.com/Dreamacro/clash/tunnel.process
> 	github.com/Dreamacro/clash/tunnel/tunnel.go:139 +0x46
> 
> goroutine 19 [chan receive]:
> github.com/Dreamacro/clash/tunnel.processUDP()
> 	github.com/Dreamacro/clash/tunnel/tunnel.go:128 +0x4d
> created by github.com/Dreamacro/clash/tunnel.process
> 	github.com/Dreamacro/clash/tunnel/tunnel.go:139 +0x46
> 

版本是Clash Meta alpha-73d5042 windows amd64 with go1.18.3 Tue Jun  7 02:56:33 UTC 2022
其中使用了 tun gvisor

**Comment by csy19960309** [comment]
system stack 也会。
并且在下次启动时会出现：

> time="2022-06-10T17:19:05+08:00" level=info msg="[TUN] Using existing driver 0.14"
> time="2022-06-10T17:19:05+08:00" level=info msg="[TUN] Creating adapter"
> time="2022-06-10T17:19:20+08:00" level=error msg="[TUN] Timed out waiting for device query: 等待的操作过时。 (Code 0x00000102)"
> time="2022-06-10T17:19:20+08:00" level=error msg="[TUN] Failed to setup adapter (problem code: 0x1F, ntstatus: 0xC0000035): 当文件已存在时，无法创建该文件。 (Code 0x000000B7)"
> time="2022-06-10T17:19:20+08:00" level=error msg="Start TUN listening error: can't open tun: create tun: Error creating interface: Cannot create a file when that file already exists."

**Comment by Skyxim** [comment]
@csy19960309 之前的进程没有关闭
