### ISSUE TITLE
配置文件示例中存在关于 tun route address 的写法错误

### ISSUE THREAD

**Issue by plzfgme** [MetaCubeX/Clash.Meta#831]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

目前各个配置文件（yaml）示例（包括官网和Github上的）的 tun route address 的写法都是 `inet4-route-address` 和 `inet6-route-address`，而实际上根据 [config/config.go](https://github.com/MetaCubeX/Clash.Meta/blob/Alpha/config/config.go#L234-L235)，应该是 `inet4_route_address` 和 `inet6_route_address`。

### Possible Solution

修改文档或者统一成用`-`的形式

**Comment by xishang0128** [comment]
@plzfgme 改了,现在是-了
