### ISSUE TITLE
[Feature] 移植mosdns的black_hole功能.

### ISSUE THREAD

**Issue by daiaji** [MetaCubeX/Clash.Meta#840]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

https://github.com/XIU2/CloudflareSpeedTest/discussions/317
现在主要用途是优选CF IP（我这边的QoS貌似让一部分的CF节点只有几十KB的速度，不优选简直要死了。）
https://irine-sistiana.gitbook.io/mosdns-wiki/mosdns-v5/ru-he-pei-zhi-mosdns/sequence-cha-jian#black_hole

**Comment by xishang0128** [comment]
https://wiki.metacubex.one/config/dns/hosts/

**Comment by daiaji** [comment]
不一样，如果只是hosts早就弄完了。
black_hole是先用DNS解析，获取到IP匹配CF的ips之后，抛弃掉原先的解析结果，然后修改为你希望的结果。

**Comment by xishang0128** [comment]
最终都是修改结果,最终目的是一样的

**Comment by daiaji** [comment]
在遭遇大范围QoS之后，你不可能把所有用CF CDN的域名全加到hosts里啊，black_hole的解决方案肯定更优雅啊～

**Comment by xishang0128** [comment]
> 在遭遇大范围QoS之后，你不可能把所有用CF CDN的域名全加到hosts里啊，black_hole的解决方案肯定更优雅啊～

单个black hole的最终效果就是hosts的效果,除非你加入其他流程,如果是这样,建议直接使用mosdns

**Comment by yegetables** [comment]
hosts的key能否支持 rule-set/geosite? 我想将值填为优选ip
非优选的cfip即使经过代理也经常打不开
