### ISSUE TITLE
osx 求解决方案

### ISSUE THREAD

**Issue by alsojin0806** [MetaCubeX/Clash.Meta#85]
time="2022-06-11T01:06:56+08:00" level=info msg="Start initial configuration in progress"
time="2022-06-11T01:06:56+08:00" level=warning msg="Auto detect interface: en0"
time="2022-06-11T01:06:56+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2022-06-11T01:06:56+08:00" level=info msg="Initial configuration complete, total time: 21ms"
time="2022-06-11T01:06:56+08:00" level=info msg="Use interface name: en0"
time="2022-06-11T01:06:56+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7893"
time="2022-06-11T01:06:56+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7894"
time="2022-06-11T01:06:56+08:00" level=warning msg="Failed to start TUN interface: can't open tun: create tun: Interface name must be utun[0-9]*"
time="2022-06-11T01:06:56+08:00" level=error msg="Start TUN listening error: can't open tun: create tun: Interface name must be utun[0-9]*"

**Comment by alsojin0806** [comment]
tun:
  enable: true
  stack: system
  dns-hijack:
    - tcp://8.8.8.8:53
  auto-route: true
  auto-detect-interface: true

**Comment by alsojin0806** [comment]
相同的配置 clash x 日志
2022/06/11 01:10:20.978  [info] Setup TUN createDeviceObservable
2022/06/11 01:10:20.980  [info] Setup TUN: get tuninfo TunInfo(tunName: "utun3", ip: "198.18.0.1", netmask: "255.255.0.0", dns: "198.18.0.2")
2022/06/11 01:10:20.980  [info] Setup TUN prepareTunAndRouteObservable
2022/06/11 01:10:21.076  [info] Setup TUN prepare deviec finsih
2022/06/11 01:10:21.076  [info] Setup TUN createClashTunObservable
2022/06/11 01:10:21.076  [info] SetupTun: createClashTunObservable done:utun3
2022/06/11 01:10:21.076  [info] Create Clash Tun use System

**Comment by MetaCubeX** [comment]
@alsojin0806 can't open tun: create tun: Interface name must be utun[0-9]
你device填utun0

**Comment by alsojin0806** [comment]
Tun: RawTun{
			Enable:    false,
			Device:    "utun0",
			Stack:     C.TunGvisor,
			DNSHijack: []string{"0.0.0.0:53"}, // default hijack all dns query
			A

**Comment by alsojin0806** [comment]
这里不？
time="2022-06-11T01:14:43+08:00" level=info msg="Start initial configuration in progress"
time="2022-06-11T01:14:43+08:00" level=warning msg="Auto detect interface: en0"
time="2022-06-11T01:14:43+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2022-06-11T01:14:44+08:00" level=info msg="Initial configuration complete, total time: 27ms"
time="2022-06-11T01:14:44+08:00" level=info msg="Use interface name: en0"
time="2022-06-11T01:14:44+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9091"
time="2022-06-11T01:14:44+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7893"
time="2022-06-11T01:14:44+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7894"
time="2022-06-11T01:14:44+08:00" level=warning msg="Failed to start TUN interface: can't open tun: create tun: operation not permitted"
time="2022-06-11T01:14:44+08:00" level=error msg="Start TUN listening error: can't open tun: create tun: operation not permitted"

**Comment by alsojin0806** [comment]
config 
tun:
  enable: true
  stack: gvisor
  dns-hijack:
  - 0.0.0.0:53
  auto-route: true
  auto-detect-interface: true

**Comment by MetaCubeX** [comment]
@alsojin0806 tun: 
  device: utun0

**Comment by alsojin0806** [comment]
tun:
  enable: true
  stack: gvisor
  device: utun0
  # device: utun0
  dns-hijack:
  - 0.0.0.0:53
  auto-route: true
  auto-detect-interface: true

**Comment by alsojin0806** [comment]
<img width="285" alt="image" src="https://user-images.githubusercontent.com/3974508/173118986-c0997dab-c283-4e09-92a9-54cb53818a52.png">

**Comment by alsojin0806** [comment]
也不行

**Comment by MetaCubeX** [comment]
@alsojin0806 你用cfw换核试试

**Comment by alsojin0806** [comment]
Premium 好像不开源
用这些配置
tun:
  enable: true
  stack: system
  device: utun0
  auto-route: true
  auto-detect-interface: true

**Comment by alsojin0806** [comment]
time="2022-06-11T01:30:38+08:00" level=info msg="Start initial compatible provider 📢 谷歌FCM"
time="2022-06-11T01:30:38+08:00" level=info msg="Start initial compatible provider 🛑 全球拦截"
time="2022-06-11T01:30:38+08:00" level=info msg="Start initial compatible provider 📲 电报信息"
time="2022-06-11T01:30:38+08:00" level=info msg="Start initial compatible provider ♻️ 自动选择"
time="2022-06-11T01:30:38+08:00" level=info msg="Start initial compatible provider 🚀 节点选择"
time="2022-06-11T01:30:38+08:00" level=info msg="Start initial compatible provider Ⓜ️ 微软服务"
time="2022-06-11T01:30:38+08:00" level=info msg="Start initial compatible provider 🌍 国外媒体"
time="2022-06-11T01:30:38+08:00" level=info msg="Start initial compatible provider 🐟 漏网之鱼"
time="2022-06-11T01:30:38+08:00" level=info msg="Start initial compatible provider 🎯 全球直连"
time="2022-06-11T01:30:38+08:00" level=info msg="Start initial compatible provider 🍃 应用净化"
time="2022-06-11T01:30:38+08:00" level=info msg="Start initial compatible provider 🍎 苹果服务"
time="2022-06-11T01:30:38+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2022-06-11T01:30:38+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
time="2022-06-11T01:30:38+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"

**Comment by alsojin0806** [comment]
tun 没启动 我是用go 源码 Mac VS code 调试的

**Comment by MetaCubeX** [comment]
@alsojin0806 调试开了权限了吗？

**Comment by alsojin0806** [comment]
VS code 怎么开启权限 大佬指点一下

**Comment by alsojin0806** [comment]
我编译成文件 用sudo su 也不行

**Comment by alsojin0806** [comment]
已经解决了 谢谢老板提醒

**Comment by alsojin0806** [comment]
device: utun0 ，这里utun0我写的是utun3，我看clashx 获取是utun4,我用管理员启动clash，设置utun0 说啥busy,后面换成utun3 就可以了，这个clashx  再次启动变成了utun4 ,大佬device这边如何判断是否在使用了，我目前用的版本是Clash.Meta 1.10.0  这个版本

**Comment by alsojin0806** [comment]
这个跟leaf 有点类似的

**Comment by MetaCubeX** [comment]
@alsojin0806 请直接上alpha
