### ISSUE TITLE
osx 启动 meta,创建tun 显示operation not permitted 

### ISSUE THREAD

**Issue by alsojin0806** [MetaCubeX/Clash.Meta#89]
日志如下
Failed to start TUN interface: can't open tun: create tun: operation not permitted 

创建的时候有没有方法加权限，查go 没有相关记录，是否有其他方案，不懂go

**Comment by Skyxim** [comment]
@alsojin0806 tun 需要root权限

**Comment by alsojin0806** [comment]
go 这边有方法直接添加不？就是获取root权限进行添加

**Comment by Skyxim** [comment]
@alsojin0806 sudo 啊

**Comment by alsojin0806** [comment]
写代码里面的，我看他代码

func CreateTUN(name string, mtu int) (Device, error) {
	ifIndex := -1
	if name != "utun" {
		_, err := fmt.Sscanf(name, "utun%d", &ifIndex)
		if err != nil || ifIndex < 0 {
			return nil, fmt.Errorf("Interface name must be utun[0-9]*")
		}
	}

	fd, err := unix.Socket(unix.AF_SYSTEM, unix.SOCK_DGRAM, 2)
	if err != nil {
		return nil, err
	}

	ctlInfo := &unix.CtlInfo{}
	copy(ctlInfo.Name[:], []byte(utunControlName))
	err = unix.IoctlCtlInfo(fd, ctlInfo)
	if err != nil {
		unix.Close(fd)
		return nil, fmt.Errorf("IoctlGetCtlInfo: %w", err)
	}

	sc := &unix.SockaddrCtl{
		ID:   ctlInfo.Id,
		Unit: uint32(ifIndex) + 1,
	}

	err = unix.Connect(fd, sc)
	if err != nil {
		unix.Close(fd)
		return nil, err
	}

	err = unix.SetNonblock(fd, true)
	if err != nil {
		unix.Close(fd)
		return nil, err
	}
	tun, err := CreateTUNFromFile(os.NewFile(uintptr(fd), ""), mtu)

	if err == nil && name == "utun" {
		fname := os.Getenv("WG_TUN_NAME_FILE")
		if fname != "" {
			os.WriteFile(fname, []byte(tun.(*NativeTun).name+"\n"), 0o400)
		}
	}

	return tun, err
}

**Comment by alsojin0806** [comment]
https://git.zx2c4.com/wireguard-go/tree/tun/tun_darwin.go?id=ef5c587f782d944005971c7ba5da88405f9b000b#n128

**Comment by skill7899** [comment]
直接sudo ./clashMeta 或者用launchd去启动clashMeta
