### ISSUE TITLE
Rules PROCESS-NAME on Android not working

### ISSUE THREAD

**Issue by JeelsBoobz** [MetaCubeX/Clash.Meta#91]
Rules PROCESS-NAME by packagename app not working for Android
Example:
```- PROCESS-NAME, com.whatsapp, PROXY```

**Comment by MetaCubeX** [comment]
@JeelsBoobz enable-process: true

**Comment by JeelsBoobz** [comment]
@MetaCubeX thanks sir

**Comment by JeelsBoobz** [comment]
@MetaCubeX give me example sir?

**Comment by MetaCubeX** [comment]
@JeelsBoobz - UID, 123456, PROXY

**Comment by JeelsBoobz** [comment]
@MetaCubeX get uid from command line ```ls -lna /data/data | grep com.whatsapp```
Right?

**Comment by JeelsBoobz** [comment]
@MetaCubeX thanks sir
Already solved

**Comment by cikezlf** [comment]
请问怎样解决方法 Rules PROCESS-NAME on Android not working

**Comment by sinoon** [comment]
hi ，我发现用 UID 会报错的，提示是 can not get uid from {IP}

```
[PKG] 172.19.0.1:49481 --> 112.25.103.105:443 by 10413[com.tencent.mm]
[UID] could not get uid from 112.25.103.105
```

**Comment by huangdog** [comment]
没有自动的方法吗，由clash根据PROCESS-NAME获得app的uid，再以这个uid应用规则。全程让clash处理。
