### ISSUE TITLE
osx 后台启动显示这个错误？

### ISSUE THREAD

**Issue by alsojin0806** [MetaCubeX/Clash.Meta#95]
time="2022-06-15T23:52:36+08:00" level=info msg="Start initial configuration in progress"
time="2022-06-15T23:52:36+08:00" level=warning msg="Auto detect interface: route: writing to routing socket: not in table\n"
time="2022-06-15T23:52:36+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2022-06-15T23:52:36+08:00" level=info msg="Initial configuration complete, total time: 115ms"
time="2022-06-15T23:52:36+08:00" level=info msg="Use interface name: route: writing to routing socket: not in table\n"
time="2022-06-15T23:52:36+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9091"
time="2022-06-15T23:52:36+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7897"
time="2022-06-15T23:52:36+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7898"
time="2022-06-15T23:52:36+08:00" level=warning msg="Failed to start TUN interface: can't open tun: create tun: GetSockoptString: bad file descriptor"
time="2022-06-15T23:52:36+08:00" level=error msg="Start TUN listening error: can't open tun: create tun: GetSockoptString: bad file descriptor"
time="2022-06-15T23:52:36+08:00" level=info msg="Start initial compatible provider 🎯 全球直连"
time="2022-06-15T23:52:36+08:00" level=info msg="Start initial compatible provider 🛑 全球拦截"

**Comment by skill7899** [comment]
tun没有权限启动，要加sudo 或者 launchd去启动
