### ISSUE TITLE
可以考虑支持trojan-go的mux多路复用吗？

### ISSUE THREAD

**Issue by skill7899** [MetaCubeX/Clash.Meta#96]
不然使用trojan-go就感觉费了一半~

**Comment by Skyxim** [comment]
@skill7899 trojan-grpc

**Comment by bash99** [comment]
服务端也是trojan-go吗？

grpc协议也自带mux复用，但是现在只有一个连接，碰上线路差容易卡，线路过得去的时候倒是挺顺滑的。

**Comment by skill7899** [comment]
> 

对服务端也是trojan-go

**Comment by skill7899** [comment]
> 服务端也是trojan-go吗？
> 
> grpc协议也自带mux复用，但是现在只有一个连接，碰上线路差容易卡，线路过得去的时候倒是挺顺滑的。

对服务端也是trojan-go

**Comment by moranno** [comment]
mux的效率可能远没有grpc高，可以看这里的讨论：
https://github.com/e1732a364fed/v2ray_simple/issues/128

**Comment by skill7899** [comment]
> mux的效率可能远没有grpc高，可以看这里的讨论： [e1732a364fed/v2ray_simple#128](https://github.com/e1732a364fed/v2ray_simple/issues/128)

@moranno 我已经用了hy协议
