### ISSUE TITLE
使用v2ray订阅导入，vmess和vless可以显示节点，但无法连接

### ISSUE THREAD

**Issue by zvzl** [MetaCubeX/Clash.Meta#97]
v1.11.2使用v2ray订阅导入，vmess和vless可以显示节点，但无法连接；trojan正常连接。请问是vmess和vless暂时不支持用订阅链接导入吗？

**Comment by MetaCubeX** [comment]
@zvzl 蛙蛙的吧，等修复

**Comment by zvzl** [comment]
蛙蛙是什么意思？
同样的订阅链接，导入电脑上的v2rayN，vmess、vless和trojan都正常使用。

**Comment by MetaCubeX** [comment]
@zvzl 尝试最新alpha版本

**Comment by zvzl** [comment]
`time="2022-06-21T08:47:33+08:00" level=warning msg="initial proxy provider xxxxx error: proxy 6 error: 'ws-opts.path' expected type 'string', got unconvertible type '[]string','ws-opts.headers[Host]' expected type 'string', got unconvertible type '[]string'"`
换alpha版本后报错，识别不了任何节点

**Comment by MetaCubeX** [comment]
@zvzl 这是VLESS还是VMESS报错？

**Comment by zvzl** [comment]
vmess

**Comment by zvzl** [comment]
最新的alpha版本vmess、vless和trojan都正常了

**Comment by Mannokia** [comment]
Добрый день. На  v1.19.20 таже самая проблема только наоборот. При импорте подписки VLESS все работает корректно, а при импорте TROJAN по подписке он не работает, но если этот же конфиг  прописать вручную, то он работает.

Подскажите пожалуйста как решить проблему?
